### ISSUE TITLE
סוג עוסק במעבר מישראל לחו"ל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#104]
כאשר אני משנה את המורה מישראל לחו"ל או ההפך, שדה סוג עוסק אבל הטופס לא מחייב לבחור אחד הסוגים אלא נקלט ללא סוג.

**Comment by tom-hollander** [comment]
הגדרת שמדובר בשדה חובה ?

2015-08-11 15:53 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
זה אכן שדה חובה.. כשהוא מאוכלס נכון ומנסים להוריד אותו, הטופס לא מאפשר. 

נשלח מה-iPhone שלי

‫ב-11 באוג׳ 2015, בשעה 15:57, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬
