### ISSUE TITLE
עמלת סוכן שכיר

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#105]
במצב בו הסוכן שכיר (לא מקבל מע"מ) והמורה ישראלי (משלם מע"מ) עמלת הסוכן לא מחושבת נכון, היא כוללת מע"מ במקום לא לכלול.
הדוגמה המספרית נמצאת באקסל שבדרופ בוקס
הקמתי קופון במחיר 41 ש"ח

![image](https://cloud.githubusercontent.com/assets/6491631/9198083/29a1ea4a-4042-11e5-86e0-859f9f64d165.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9198003/9765572a-4041-11e5-94d2-04dfa5bbff8c.png)

**Comment by tom-hollander** [comment]
בדקתי את החישוב, הוא תואם לאקסל, הסוכן לא היה מוגדר שכיר.

**Comment by natan1957** [comment]
אני יודע שמנהל מתחזה לא יכול לעדכן סוג עיסוק.
ייתכן וטעיתי.. קורה אפילו לי...
