### ISSUE TITLE
הקמת קופון תושב חו"ל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#106]
אם אני משנה את מקום המגורים של המורה לחו"ל אני לא מצליח להקים קופון

**Comment by tom-hollander** [comment]
אני צריך עוד נתונים,  איזה מורה ? איזה שיעור ? לאן שינית ? איזה הודעת שגיאה
?

2015-08-11 16:09 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
כרגע את כל הבדיקות אני עושה עם mo4444 זה גם השם וגם הסיסמה. הסוכן הוא so4444 והתלמיד ta4444. השיעור הוא של המורה כמובן, השלישי ברשימת שיעורים וחבילות. לא משנה לאיזו מדינה. העברתי לארב״ב ולצרפת, אותו דבר. 

נשלח מה-iPhone שלי

‫ב-11 באוג׳ 2015, בשעה 16:17, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
אין הודעת שגיאה, זה נתקע לאחר לחיצה על צור קופון.
