### ISSUE TITLE
תרגום עמלת סוכן לדולר וחישוב עמלת המרה לסוכן

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#107]
הקמתי קופון עם השחקנים הקבועים(מורה, שיעור, סוכן..) כאשר שיניתי לסוכן את המטבע לדולר במטרה לייצר עמלת המרה. מחיר לתלמיד 41 ש"ח
המורה תושב ישראל - משלם מע"מ והסוכן עוסק מורשה - מקבל מע"מ
האירוע - zNZTxlL5x1
תקלה אחת מסומנת באדום - עמלת סוכן צריכה להיות 1.8 ש"ח וכאן היא מופיעה כ 1.8 דולר  זה צריך להיות מתורגם לערך הדולרי
תקלה שנייה מסומנת בכחול - עמלת ההמרה לסוכן מוצגת כאפס, היא צריכה להיות דומה לזיכוי עמלת המרה לאתר שזה 0.018 ומוצג בצורה מעוגלת 0.02

![image](https://cloud.githubusercontent.com/assets/6491631/9205287/ec8f0886-4069-11e5-88af-4ac40c9dc649.png)

**Comment by natan1957** [comment]
עמלת סוכן היא 10% = 1.8 אבל בשקלים ולא בדולרים.
הערך הדולרי היה צריך להיות 0.45 כרגע הוא למעשה 7.2 ש"ח.
אירוע DAzhH1HDS4
השחקנים הקבועים, מורה לא משלם וסוכן לא מקבל מע"מ, מורה בשקלים וסוכן בדולרים.
![image](https://cloud.githubusercontent.com/assets/6491631/9303560/a0cb7434-44e7-11e5-9c7e-7118482d91cb.png)
![image](https://cloud.githubusercontent.com/assets/6491631/9303579/cbce6646-44e7-11e5-946b-65bb0f9e118d.png)

**Comment by natan1957** [comment]
בניסיון להקים קופון בתנאים של הקופון הקודם אני מקבל את ההודעה הבאה:
![image](https://cloud.githubusercontent.com/assets/6491631/9329177/160a5e74-45b8-11e5-8ebe-5ccf86aea878.png)

**Comment by tom-hollander** [comment]
המשתמש של maamBalanceAccount  נמחק.
כנס לטבלת commissions ולחץ על הקישור בשדה maamBalanceAccount , זה יוביל לרשומה ריקה.
ברגע שתחזיר את הקישור , זה יעבוד

**Comment by natan1957** [comment]
כבר היינו בסרט כזה.. איך זה קורה? זה ממש מטריד..

נשלח מה-iPhone שלי

‫ב-20 באוג׳ 2015, בשעה 20:10, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
איזה מהתקלות זה גרם?

נשלח מה-iPhone שלי

‫ב-20 באוג׳ 2015, בשעה 20:10, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
לאחרונה, 
הורדתי הרשאות מחיקה מכל טבלת המשתמשים

**Comment by natan1957** [comment]
הוספתי את המשתמש מע"מ יתרות
