### ISSUE TITLE
אירוע שלא הסתיים..

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#108]
מה עושים עם הסטטוס הזה ?
איפה זה נעצר?
האם המנגנון ל"תיקון" אירועים יכול לעזור ?
 אירוע - jpsod5AB6m

![image](https://cloud.githubusercontent.com/assets/6491631/9209575/f681d95c-407f-11e5-957c-5044673e77c8.png)

**Comment by tom-hollander** [comment]
שאלתך לא ברורה לי

**Comment by natan1957** [comment]
האירוע הזה לא הסתיים תקין. השאלה מה בוצע ומה לא.. לשם כך בנית(עוד לא ראיתי) מנגנון לאיתור ותיקון אירועים מסוג זה. אז יש לך פה דוגמה אמיתית להפעיל עליה את המנגנון..

נשלח מה-iPhone שלי

‫ב-12 באוג׳ 2015, בשעה 06:51, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
אתה יכול להפעיל

**Comment by natan1957** [comment]
איך?

**Comment by tom-hollander** [comment]
בצע לוגין בתור אדמין (natan)
כנס לקישור
http://mymentor/admin/transactionerrors

**Comment by natan1957** [comment]
ביצעתי לוגין אדמין
![image](https://cloud.githubusercontent.com/assets/6491631/9268715/926509ca-426a-11e5-8dbd-75c5f50e3669.png)

**Comment by tom-hollander** [comment]
http://mymentorapp.com/admin/transactionerrors

**Comment by natan1957** [comment]
הפעלתי את התהליך. לא ברור לי מה קרה שם.
כשמילאתי מספר אירוע ואחזרתי, הוא ביקש מזהה טרנזקציה של פיפל.
בכל מקרה לא הצלחתי לאחזר רשומה בודדת.
כשרוקנתי את שדות הקלט קיבלתי רשימה של מסך שלם של אירועים שלא הסתיימו.
הקשתי פיקס, עבד, עבד, עבד ורוקן את הרשימה.
כשבדקתי מה הסטטוס של האירוע הספציפי,שצריך להפוך ל
success_recovered
בפועל הוא הפך ל 
![image](https://cloud.githubusercontent.com/assets/6491631/9273853/19a50db2-4299-11e5-8109-7d78e3ecd3f3.png)
