### ISSUE TITLE
מחייב סוג עוסק למרות שקיים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#109]
אני נכנס כמנהל לטופס עדכון פרטים של
more88@gmail.com
אני מנסה לשייך אותו לקבוצה/תת קבוצה.
בעדכון מתקבלת הודעת שגיאה.. למרות שהשדה מאוכלס ממקודם.

![image](https://cloud.githubusercontent.com/assets/6491631/9233171/53951de2-413a-11e5-9c9e-7235c564f11b.png)

**Comment by tom-hollander** [comment]
יש לנקות cache בדפדפן

**Comment by natan1957** [comment]
אם אתה מתכוון ל
Ctrl - f5
אז זה לא עוזר.
