### ISSUE TITLE
מטבע ברירת מחדל 

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#114]
מטבע ברירת מחדל אצל מי שנרשם מהאפליקציה בעברית צריך להיות ש"ח
![image](https://cloud.githubusercontent.com/assets/6491631/9308352/322e1afc-450c-11e5-8843-64790facfb29.png)

**Comment by tom-hollander** [comment]
1. האם מדובר בדרישה חדשה  או בבאג?
2. לפי מה יודעים שהמשתמש נרשם דרך האפליקציה בעברית ?

**Comment by natan1957** [comment]
הקמת משתמש דרך האפליקציה לא מאכלסת מטבע.
אלא שטופס עדכון פרטי המשתמש מכניס כברירת מחדל את המטבע לירה שטרלינג. זה לא  נדרש ומפריע.
הטופס צריך להשאיר למשתמש לבחור, ובמידה ואיננו בוחר, להציג שגיאה הואיל ומדובר בשדה חובה.

**Comment by tom-hollander** [comment]
לא ברור לי מה אתה מבקש, יש כאן 2 דרישות סותרות
1. הכנסת שח כברירת מחדל 
2. לא להכניס ערך כברירת מחדל ולאלץ את המשתמש לבחור.
מה מהם אתה רוצה לממש ?

**Comment by natan1957** [comment]
משתמש מוקם דרך האפליקציה ללא מטבע.
כשהוא נכנס לפורטל בפעם הראשונה הוא רואה את הפורטל עם מטבע לירה שטרלינג.
כשהוא מגיע לטופס עדכון הפרטים, מוצג לירה שטרלינג כברירת מחדל
למעשה, בביצוע לוגאין, אם מסתבר שהמשתמש הוקם באפליקציה, יש להקפיץ אותו מיד לטופס עדכון פרטים.
בטופס זה אין להציג מטבע אלא לחייב את המשתמש לבחור

**Comment by tom-hollander** [comment]
עדיין לא ברור מה אתה מבקש לבצע.  כתוב בבקשה מה אתה מצפה לראות ונגד מה אתה רואה בפועל
למה המשתמש רואה את הפורטל עם מטבע שטרלינג ? מה זה אומר שהמשתמש נכנס פעם ראשונה , ביצע לוגין ? תוכל לצרף את הדרישה מקורית, אני לא רואה אותה באפיונים

**Comment by natan1957** [comment]
אני לא מוצא , זה קשור לרישום דרך האפליקציה.
הדרישה היא פשוטה.
ברגע שמשתמש מבצע לוגאין והסטטוס שלו = אפפ, יש להציג לו הודעה ולהעביר אותו  לטופס עדכון פרטים.
בטופס הזה אין להציג כל מטבע בשדה המטבע.
אם לא יבחר מטבע יש להציג הודעת שגיאה הואיל וזה שדה חובה.

פעולה זו שלמעשה מתבצעת כיום ממספר מקומות למעשה תייתר אם הפעילות במקומות אלה כולל מקומות שזה עדיין לא בוצע כמו נושא 113.
כמובן שלאחר העדכון הסטטוס משתנה, כך שזה יקרה פעם אחת בלבד.

**Comment by tom-hollander** [comment]
איזה הודעה יש להציג למשתמש ?

מה קורה אם המשתמש מותר על השלמת הפרטים ומנסה להגיע לדפים אחרים באתר ?

**Comment by natan1957** [comment]
ראה ההתכתבות.
[image: Inline image 1]
משתמש לא יוכל להתקדם אלא לאחר שישלים פרטי רישום.

2015-08-21 9:05 GMT+03:00 tom-hollander <notifications@github.com>:

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/9402291/40bcfaae-47e4-11e5-8ba4-f9f78fdacddd.png)

**Comment by natan1957** [comment]
משתמש חדש שהוקם דרך האפליקציה ונכנס לראשונה לפורטל צריך להיות מופנה לעדכון והשלמת פרטים.
בפועל הוא מצליח לראות שיעורים וחבילות וכשמנססה לראות את החשבון שלי מתעופף לדף רישום.
ראה
user= temp11@co.il pw= temp11

**Comment by tom-hollander** [comment]
תוקן, אנא מחק קאש מהדפדפן לפני הבדיקה( ctrl + f5)

**Comment by natan1957** [comment]
המשתמש אמנם מופנה לטופס השלמת פרטים, אבל הוא יכול להקליק על האיקון של מיימנטור ולהגיע לתפריט הראשי..
שם הוא יכול לראות שיעורים וכו..

**Comment by tom-hollander** [comment]
אם משתמש אנונימי יכול לראות שיעורים למה שמשתמש רשום הגם שהוא מאפליקציה לא
יוכל?

**Comment by natan1957** [comment]
אם הוא אנונימי, ולא ביצע לוג אין, אין בעיה. אבל אם ביצע לוג אין זה כבר מצב שונה..
ברשימת שיעורים ישנן עוד אפשרויות שצריך לחסום. הוספה לסל והזמנת דמו כבר חסומים, אבל יש גם שליחת מכתב למורה, הצגת פרטי מורה ותהיה פונקציונליות נוספת שיהיה צורך לחסום.אם לא השלים פרטים.
במקום כל זה, אם מבצע לוגאין, יש לחייב להשלים פרטים כדי להמשיך למערכת.
אם הוא לא רוצה, שיגלוש כאנונימי.

**Comment by tom-hollander** [comment]
אוקי

**Comment by natan1957** [comment]
או קי, כרגע עובד בשיעורים וחבילות ובחשבון שלי.
בהמשך יהיה צורך להוסיף את הבדיקה ב מורים, השיעורים שלי וכו
