### ISSUE TITLE
שיפוצים קוסמטיים בחשבון שלי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#117]
כמה שינויים קוסמטיים שהמתינו. אני מניח שיימצאו בהמשך עוד..
 
יש להחליף בין החלונות.. חלון האירוע צריך להופיע בלחיצה על עמודת  פעילות  וחלון קופון בעמודת פריט בשורת קופון. (בשורות עם פריט שיעור/חבילה תוצג חלונית אחרת)  א..

בחלון הצגת קופון, התשלום לא מחושב נכון כמו כן חסר תשלום בשקלים בנוסף לתשלום במטבע התשלום.
האם ניתן להגביל רוחב חלונית ולהגליש שורות ארוכות,או שזה בשטח של בוריס?

![image](https://cloud.githubusercontent.com/assets/6491631/9427325/509dc596-4980-11e5-8cf1-bb58eb0e409c.png)

יש להגביל את כל המחירים בחלון הצגת קופון למקסימום שתי ספרות אחרי הנקודה. אם אין כלום אחרי הנקודה, כמובן שאין צורך להציג אפסים.

![image](https://cloud.githubusercontent.com/assets/6491631/9427222/824c97e0-4979-11e5-9ba4-7ca5d0c713af.png)

יש להציג את הסכומים עם 2 ספרות אחרי הנקודה ושהכל מוצמד ימינה 

![image](https://cloud.githubusercontent.com/assets/6491631/9427449/cd2b98f8-4986-11e5-8ab6-f6c7b02d2544.png)

יש להצמיד תוכן עמודות פעולה ופריט ימינה ובאנגלית בהתאמה שמאלה. 
כאן אני מתלבט, בהתאם לנראות של התוצאה, ייתכן ובהמשך אבקש לחזור למרכוז.

![image](https://cloud.githubusercontent.com/assets/6491631/9427458/3145ff04-4987-11e5-8020-21ec5081e9fd.png)

בממשק האנגלי יש לקבוע את המטבע מימין לסכום , גם כאן שתי ספרות אחרי הנקודה ומוצמד ימינה.

![image](https://cloud.githubusercontent.com/assets/6491631/9427467/452366c8-4988-11e5-90b2-bc1fa2f7696a.png)

**Comment by tom-hollander** [comment]
כל הנושאים פרט לנקודה העשרונית ןנתונים חסרים
הם בשטח של בוריס.
מה עןשים עם ערכים כגון 0.004 הם יופיעו כאפסים

**Comment by natan1957** [comment]
כן. שיופיעו כאפסים. כמובן שבטבלה יושב בערך הנכון ובחישובים, סיכומים וכו' הוא בא לידי ביטוי.
האם העניין של פתיחת חלונות שונים  בעמודת הפריט,  חלון קופון בשורת קופון וחלון שיעור בשורת שיעור וכו' זאת לוגיקה של בוריס? 
מאיפה הוא יודע מה יש בשורה ?
מה עם הסכום השגוי של התשלום שמוצג בחלונית האירוע ?

**Comment by tom-hollander** [comment]
לגבי הסכום השגוי אנסה לשחזר את הבעיה אבל חסרים את הנתונים שבד"כ
חסרים...ושהיו מקלים עלי לשחזר ולהבין את הבעיה.
"מאיפה הוא יודע מה יש בשורה ?" - השאלה לא ברורה לי.
שאר הדברים הם אצל בוריס כיוון שהם קשורים לנראות העמוד.

2015-08-23 12:54 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
הסכום שגוי בכל האירועים בהם יש תשלום פייפל. קח אירוע שאתה הקמת ושהיה בו תשלום ותוכל לראות את זה.

לגבי השורה.. בעמודת פריט הופיעו עד כה רק קופונים. כי רכישת שיעורים וחבילות טרם פותחה.
בלחיצה על הפריט, נפתח חלון קופון.
בקרוב, יופיעו בעמודה זו גם שיעורים וגם חבילות. בלחיצה על אחד מהם צריך להיפתח חלון רלוונטי לפריט.. קופון, שיעור או חבילה.. המידע מה יש בשורה ידוע לך ולא לבוריס. אתה תצטרך להפעיל לוגיקה שפותחת את החלון הנכון.

**Comment by tom-hollander** [comment]
מהו הסכום הנכון ואיך מגיעים אליו?

**Comment by natan1957** [comment]
הטעות היא לא בחלונית האירוע אלא בתצוגת הטרנזקציה.
פתחתי על זה נושא נפרד.
העברתי לבוריס
אני סוגר את הנושא הזה
