### ISSUE TITLE
רכישת קופון לשיעור ביורו

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#118]
mo4444 ta4444 so4444 lesson= bgXgOECLHV event = OkzhKR3ERh
מחיר השיעור 23.6 יורו = 118 ש"ח
מחיר לתלמיד 41 ש"ח הפרש לתשלום 18 ש" פייפל גבה 18 ש"ח
בתנועת החיוב והזיכוי של המורה מופיע הסכום 90 ש"ח שזה 18 כפול 5 - שער היורו..

כמו כן לא מופיע זיכוי האתר בסך 18 ש"ח

![image](https://cloud.githubusercontent.com/assets/6491631/9428003/57d53bd8-49a2-11e5-9b01-2a6a6eb02801.png)
![image](https://cloud.githubusercontent.com/assets/6491631/9428009/970bd438-49a2-11e5-8dd9-fdff2ea5454c.png)

**Comment by tom-hollander** [comment]
זה לפי מטבע השיעור

**Comment by natan1957** [comment]
זה במטבע המורה (ש"ח) וזה אמור להיות 18 ש"ח. במקום זאת  מופיע 90 ש"ח

ובנוסף, חסרה תנועת זיכוי של האתר בסך 18 ש"ח.

**Comment by tom-hollander** [comment]
מתוך האפיון
זיכוי המשלם בגין התשלום
אם paymenTransaction > אפס, 
יש לרשום בטבלת העו"ש* ( AccountStatement ) תנועה חיובית לרוכש, עם ערך  paymenTransaction מחושב באקסל בשורה 195 , מפתח הרוכש = user
paymenTransaction = credit
סוג אירוע = תשלום בגין רכישה
TransactionType   = "Coup_buyer_Payment"
•	

זיכוי אתר בערך הרכישה
•	יש לרשום תנועה *לזכות חשבון האתר. עם הערך זיכוי אתר – SitePaymentCredit מחושב באקסל שורה 212. 
includingVAT = אפס
מפתח האתר = user
TransactionType  = "Coup_Site_Credit"
SitePaymentCredit = credit 
ערך מקביל בשקלים ל creditNIS

איפה ההתייחסות למטבע ? בעבר דיברנו על זה ואמרת לי שקופון הינו שלוחה של שיעור ולכן יש לחשב לפי מטבע השיעור.
לאני מבקש שתעדכן את האפיון כך שבכל המקומות שיש בהם כתיבה של סכום לתשלום,  יצויין באיזה מטבע יש לבצע את התנועה

**Comment by natan1957** [comment]
נכון, בהקמת קופון לשיעור יש לרשום את הסכומים במטבע השיעור.
אבל אין לזה קש רישום למשתמשים השונים. כל טרנזקציה שנרשמת למשתמש, כולל לאתר, למע"מ, למורה, לסוכן וכו' צריכה להיות מתורגמת למטבע שלו והירשם במטבע שלו ובנוסף גם בשקלים.
בכל מקרה, גם לשיטתך, אני לא מבין איך הגעת מ 18 שקלים ל 90 שקלים.
להלן קטע מהאפיון שנמצא בדף הראשון:
![image](https://cloud.githubusercontent.com/assets/6491631/9428877/5a726770-49c6-11e5-9c90-a235d2ce1d27.png)
