### ISSUE TITLE
כתיבת טרנזקציות בהתאוששות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#124]
יצרתי קופון תקין באירוע 
4KhRyHpdZk
שיניתי את סטטוס האירוע ל"התחיל" ומחקתי את הטרנזקציות של האירוע.
הפעלתי את ההתאוששות.
להלן תמונה של האירוע המקורי ואחריו תמונה של האירוע המשוחזר.
מכייון שלא שיניתי את היתרות של השחקנים, היתרות החדשות מתחשבות מצב היתרה הקיים.

![image](https://cloud.githubusercontent.com/assets/6491631/9680363/0a62983a-52ff-11e5-9e32-1c4192227cd5.png)
![image](https://cloud.githubusercontent.com/assets/6491631/9683186/950a2388-5316-11e5-9f6d-a85330b6e8d9.png)

**Comment by tom-hollander** [comment]
אנא פרט מה הבאג

2015-09-04 15:11 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
יתרות האתר מחושבות כולן ביחס ליתרה הקודמת ולא מצטברות כפי שאמור לקרות בחישובי יתרה.
היתרה הקודמת היא 1564.24
1564.24 + 15.245 = 1579.49
1564.24 - 1.525 = 1562.71
1564.24 + 0.015 = 1564.25

אותו הדבר עם הסוכן.

כמו כן יש לוודא שהתנועות יירשמו בסדר המקורי כפי שהיו צריכות להירשם מלכתחילה.

**Comment by natan1957** [comment]
העניין טרם טופל אבל נמצא בנושא 123
אני סוגר.
