### ISSUE TITLE
לא מצליח לעדכן

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#128]
אני מנסה למחוק שיעור שהשתרבב לתוך חבילה של מורה אחר..
אני מקבל הודעת תקלה
חבילה
9ybisIcApm
more11@gmail.com pw= more11 
חפש יתרו עליה שנייה
![image](https://cloud.githubusercontent.com/assets/6491631/9787219/87cf06c2-57c9-11e5-9aee-daedfc1ffb16.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9787235/aa1ab53c-57c9-11e5-84c9-c4c72516d9e8.png)

**Comment by tom-hollander** [comment]
במחיקת השיעור מתעדכן שדה מתעדכנים 2 שדות למטרת שיפור ביצועים.
השיעור לא של המורה והוא שוייך לחבילה ,על השיעורים ישנם הרשאות שרק מנהל או מורים יכולים לערוך אותם ולכן כשנכנסת בתור המורה , לא היתה לך הרשאה למחוק את השיעור. 
אני לא יודע איך השיעור שוייך לחבילה. הממשק יציג לך רק שיעורים של המורה, יתכן ושוייך לפני

**Comment by natan1957** [comment]
איך שוייך לחבילה.. פשוט מאוד.
אני נכנס כמנהל, מציג שיעורים להוספה ומקבל מכל טוב
העניין הוא שעכשיו אני לא יכול להיכנס לעדכון חבילה, בכפתור לא מגיב וגם מחיקת חבילה לא עובדת..
כנס עם המשתמש 
natan 123456
לחבילה של השיעור הראשון שמוצג כרגע נסה להיכנס לעדכון חבילה או למחיקה.
![image](https://cloud.githubusercontent.com/assets/6491631/9833576/8ce24ca0-59a4-11e5-8493-5f28578c2345.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9833563/eaea1c3e-59a3-11e5-8bd0-5969ef68733a.png)

**Comment by tom-hollander** [comment]
אם אתה נכנס כמנהל אתה אמור לשייך רק שיעןרים של אותו המורה? אנא נסה לכתוב
באגים באופן מובנה.מה הפעולה.מה אתה מצפה לקבל .מה קיבלת בפועל.

**Comment by tom-hollander** [comment]
אני מצליח.
נכנסתי לחבילה של השיעור הראשון, לחצתי על כפתור עדכון חבילה, החלון עדכון פרטי חבילה נפתח. לחצתי על שמור, החבילה נשמרה.
לחצתי על כפתור מחיקת חבילה, קבלתי הודעת אישור. לא מחקתי אבל כפתור מגיב.

**Comment by tom-hollander** [comment]
תוקן , מוצגים שיעורים רק של המורה של החבילה ( אני מקווה שזה מה שרצית )

**Comment by natan1957** [comment]
זו חבילה שכוללת שיעורים לא של המורה.
שאריות עבר..
אבל, אני לא מצליח לא לעדכן וגם לא למחוק.
אני נכנס עם המשתמש שלי נתן 123456
חפש בשם המורה ירחם ותמצא את השיעור שמחובר לחבילה.
בבקשה לעדכן הוא מתעלם ובניסיון למחוק הוא מציג את זה
![image](https://cloud.githubusercontent.com/assets/6491631/9888239/a57e2130-5bfc-11e5-96b8-31d0bdc198ff.png)

**Comment by tom-hollander** [comment]
אני לא רואה שיש לשיעור חבילות, ביצעתי מספר תיקונים בתהליך הוספת שיעורים לחבילה, בדקתי שניתן ליצור למחוק ולשנות חבילה כמורה וכאדמין

**Comment by natan1957** [comment]
לא מבין מה המצב כרגע.
מצד אחד טבלת החבילות ריקה..
מצד בטבלת רשרים קליפים-חבילות יש 10 רשומות.
מצד שלישי, שיעור שכתוב עליו שיש לו חבילה, לא נמצא בטבלת הקשרים
![image](https://cloud.githubusercontent.com/assets/6491631/9962412/49762c6e-5e2e-11e5-952d-940db117043b.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9962359/108e170e-5e2e-11e5-9224-eae06bf630ef.png)
![image](https://cloud.githubusercontent.com/assets/6491631/9962383/2a8f9bc8-5e2e-11e5-96c3-62cbbebdf41e.png)

**Comment by tom-hollander** [comment]
עשיתי קצת שינויים בשמירת החבילה. מחקתי רשומות קישור.

**Comment by natan1957** [comment]
ראיתי שהקמת חבילה בסטטוס "חדש", ניסיתי לעדכן אותה וקיבלתי שגיאה
בנוסף יש שיעורים שמציגים שהם בחבילה כאשר בפועל הם אינם. האם זה "זבל" שיש לנקות ? מוצג למטה
מה כוללת הטבלה של השדה הבא, אני חייב להבין כדי לבדוק תקינות
![image](https://cloud.githubusercontent.com/assets/6491631/9977074/42878eb8-5f03-11e5-8384-35c23828cf77.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9977038/fa7fbe84-5f01-11e5-94ed-4c94e7cb13fc.png)
![image](https://cloud.githubusercontent.com/assets/6491631/9977042/3586cedc-5f02-11e5-91d0-7af76f43051e.png)

**Comment by tom-hollander** [comment]
השעורים שמופיעים כשייכים לחבילה הם שאריות, הכי פשוט ליצור חבילה חדשה שכוללת אותם ואז למחוק ואז האינדיקציה תמחק.

הרשומה כוללת צמד של מזהה מורה ומזהה חבילה

 

לגבי השגיאה, לא הצלחתי לשחזר , הקמתי חבילה והצלחתי לעדכון גם כמורה וגם כאדמין. אנא צרף את מזהה החבילה על מנת שאוכל לשחזר

**Comment by natan1957** [comment]
החבילה כפי הנראה נמחקה על ידך, הואיל וכרגע ישנה רק חבילה אחת שהקמת היום.
כך שאינני יכול לבדוק את החבילה שהייתה קודם.
אכן ניתן לעדכן אות הנוכחית אבל.. ניסיתי להוסיף לה שיעור שאיננו פעיל והצלחתי.. למרות שהחבילה פעילה וזה לא תקין
נכנסתי עם המשתמש של מורה11 מדובר בחבילה היחידה הקיימת כרגע 
jsp4EQwXne
![image](https://cloud.githubusercontent.com/assets/6491631/9977684/b0f4605a-5f18-11e5-9679-933a3bcf65d2.png)

**Comment by tom-hollander** [comment]
כעת לא ניתן להוסיף שיעור לא פעיל לחבילה פעילה

**Comment by natan1957** [comment]
זה כולל מניעת הורדת סטטוס שיעור(ללא פעיל) שנמצא בחבילה פעילה?

נשלח מה-iPhone שלי

‫ב-22 בספט׳ 2015, בשעה 08:27, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
כן

**Comment by natan1957** [comment]
חתימה טובה. 

נשלח מה-iPhone שלי

‫ב-22 בספט׳ 2015, בשעה 12:37, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬
