### ISSUE TITLE
הוספת שיעור לא פעיל לחבילה פעילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#129]
המערכת מאפשרת למרות שזה אמור להיות חסום.
משתמש 
more1111@gmail.com     more1111
![image](https://cloud.githubusercontent.com/assets/6491631/9833660/f03077e8-59a7-11e5-8412-05839bdf6887.png)

**Comment by natan1957** [comment]
לפי מה שראיתי, סיננת מתוצאות החיפוש את השיעורים שאינם פעילים.
זה נכון באופן חלקי..
ניתן להוסיף שיעור בבדיקת מורה לחבילה בבדיקת מורה.
שינוי סטטוס חבילה לפעיל מחייב שכל השיעורים יהיו פעילים
שינוי סטטוס שיעור מפעיל ללא פעיל מחייב שהחבילה (חבילות) שהוא בתוכה תהיה לא פעילה
כל זה כדי לאפשר למורה להקים חבילות לא פעילות לבדיקה לשם בדיקה ואז להעבירן לסטטוס פעיל.
שיעור שהחבילות שלו לא ב]עיל לא צריך להציג שהוא נמצא החבילה..

**Comment by tom-hollander** [comment]
זה דרישה חדשה ?
בדקתי את האפיון "הקמה ועדכון חבילה ", כל שמפורט שם לגבי זה היא השורה הבאה
"אין לצרף לחבילה עם סטטוס "פעיל" שיעורים שאינם בסטטוס פעיל. "

**Comment by natan1957** [comment]
לא חדש. זה נמצא באפיון:
![image](https://cloud.githubusercontent.com/assets/6491631/9897114/6dbd2984-5c4d-11e5-89a8-5240692a325c.png)

**Comment by tom-hollander** [comment]
"ניתן להוסיף שיעור בבדיקת מורה לחבילה בבדיקת מורה." - איפה זה מצויין ?

**Comment by natan1957** [comment]
זה נגזר מהאיסורים הקיימים
אבל נראה לי שאופן המימוש הכולל סימון שיעורים הכלולים בחבילה עלול לסבך את העניין.. 
הרעיון היה לאפשר למורה להכין חבילות עם סטטוס בבדיקת מורה הכוללות שיעורים עם סטטוס כזה לפני ההעברה לסטטוס פעיל..
זה בא לידי ביטוי בשורה המסומנת.
אם זה מורכב למימוש תגיד מה אפשרי..
![image](https://cloud.githubusercontent.com/assets/6491631/9898321/09c83ee8-5c5a-11e5-9129-1132ec910286.png)

**Comment by natan1957** [comment]
מה טופל ?

**Comment by tom-hollander** [comment]
כעת ניתן לשייך שיעורים בסטטוס שאינו פעיל לחבילות לא פעילות
