### ISSUE TITLE
תנועות ללא פריט

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#130]
בין 11 ל 12/9 יש מספר תנועות ללא פריט קופון
האם מדובר בתקלה ידועה שטופלה? או שצריך לחפש ממה זה נובע ?
![image](https://cloud.githubusercontent.com/assets/6491631/9889217/0aedbc6a-5c02-11e5-90b3-223472e418bd.png)

**Comment by tom-hollander** [comment]
זה טופל
