### ISSUE TITLE
חלוניות פרטים לא מופיעות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#131]
אצל המשתמשים 
mo4444     so4444
לא ניתן להציג את חלוניות הפרטים של הקופונים ושל האירועים.
ייתכן ומדובר בשיבוש של הרשומות.

**Comment by tom-hollander** [comment]
אני רואה את חלונית, אם תתן פרטים יותר מדוייקים לגבי התקלה אוכל לבדוק זאת יותר לעומק

**Comment by natan1957** [comment]
טעות שלי.
אני סוגר את הנושא
