### ISSUE TITLE
חישוב מע"מ יתרות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#133]
אירוע bvPTSvnQVZ
רכישת קופון ע"י מו4444 מחיר לתלמיד 38 ש"ח 
למורה יתרה של 10 ש"ח
התשלום הנדרש 21 ש"ח מתוך זה 10 ש"ח קיזוז ו11 ש"ח תשלום בפועל.
יש לחשב מע"מ יתרות על ה 10 ש"ח שקוזזו מהיתרה הערך צריך להיות 1.67 ולא6.1 כפי שחושב.
החישוב נמצא בשורה 212ב באקסל.
האקסל כולל כרגע את הערכים של האירוע הזה.
![image](https://cloud.githubusercontent.com/assets/6491631/10039481/224a5056-61db-11e5-8de7-55284b5210c7.png)

**Comment by tom-hollander** [comment]
היתה בעיה בהמרת מטבע שתיקנתי. כעת זה כמו באקסל אבל לא 1.67 כפי שציינת אלא 1.53

**Comment by natan1957** [comment]
נכון, טעיתי אבל בשורה.
1.53 זה טוב.
כשאבדוק אסגור.
