### ISSUE TITLE
שפת הממשק של פייפל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#136]
ממשק פייפל מופיע בעברית.
אבל מיד לאחר הכנסת הסיסמה הוא מתחלף לאנגלית

![image](https://cloud.githubusercontent.com/assets/6491631/10663650/bd67966a-78c5-11e5-97f3-7ffa8aad6077.png)
![image](https://cloud.githubusercontent.com/assets/6491631/10663669/d681d3f4-78c5-11e5-9351-889766477dc1.png)

**Comment by tom-hollander** [comment]
נכון זה לוקח את הגדרות המשתמש בפייפאל.

**Comment by natan1957** [comment]
אבל למה זה עובר לאנגלית ?

**Comment by tom-hollander** [comment]
כי המשתמש שאיתו אתה מבצע את התשלום מוגדר בפייפאל ששפת הברירת מחדל היא אנגלית

**Comment by natan1957** [comment]
השפה של מו4444 היא עברית.
הטופס הראשון של פייפל מוצג בעברית.
עם הכנסת המשתמש והסיסמה של פייפל, עובר הממשק לאנגלית.

**Comment by tom-hollander** [comment]
לא מדובר על mo4444 מדובר על המשתמש בpaypal שאיתו אתה מבצע לוגין

2015-10-22 17:50 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
השפה של mo4444 היא עברית. אז למה ממשק פייפאל מציג עברית אבל אחרי הלוגאין לפייפאל עובר לאנגלית?

**Comment by tom-hollander** [comment]
כי אחרי הלוגין לפייפאל, אתה נכנס עם משתמש שהוא שייך לאתר פייפאל לא לאתר מיימנטור ולכן אתה תחת ההגדרות שהוגדרו באתר פייפאל
