### ISSUE TITLE
אי חיוב מע"מ למשלם ישראלי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#139]
אירוע u0IX8wNmjW
שיניתי את המורה והסוכן לתושבי ישראל.
החישוב לא מציג גביית מע"מ
השחקנים הקבועים..
![image](https://cloud.githubusercontent.com/assets/6491631/11339960/90ee81fe-9204-11e5-88c0-fef85c0d5676.png)

**Comment by tom-hollander** [comment]
צרף בהקשה את המשתמשים. עבר זמן אני לא זןכר

**Comment by natan1957** [comment]
mo4444
so4444
ta4444
lesson = bgXgOECLHV
מחיר לתלמיד 41 ש"ח

**Comment by tom-hollander** [comment]
![image](https://cloud.githubusercontent.com/assets/7689853/11451238/a15f13e4-95c6-11e5-9939-9ef6ac195bf9.png)

**Comment by natan1957** [comment]
למה אני מתעופף כשאני מנסה לאחזר את האירוע שאתה הקמת ?

sEQemnbkVj

**Comment by tom-hollander** [comment]
תוקן . הסיבה לשגיאה היא שעשיתי בדיקות  וייצרתי מצב שיש בו קופונים כפולים. המערכת שינתה את הסטטוס של הקופון לWas_Duplicate. אבל לא היתה רשומה בעבור סטטוס זה בטבלת couponStatus ולכן המערכת נפלה. הוספתי רשומה אבל בעקרון לא צריכים להגיע למצב כזה
