### ISSUE TITLE
לא מחשב מחיר מינימום לחבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#141]
בהקמת חבילה, לא מציג את מחיר המינימום
הקמתי חבילה עם שלושה שיעורים מסוג הפטרה למשתמש נתן
![image](https://cloud.githubusercontent.com/assets/6491631/11347427/1b6f49b0-922a-11e5-8da7-582f7539d216.png)

**Comment by tom-hollander** [comment]
לא מצליח לשחזר , אני רואה מחיר מינימום

**Comment by natan1957** [comment]
הצלחתי לשחזר.
קיימת התנהגות מבלבלת בתהליך הקמת חבילה
עם לחיצה על צור חבילה, מופעי טופס החבילה.
אם עוברים להוספת שיעורים ובוחרים מספר חורג של שיעורים להוספה, מתקבלת הודעת השגיאה הבאה ולא מחושב מחיר מינימום.
![image](https://cloud.githubusercontent.com/assets/6491631/11456279/47c5b000-968d-11e5-9b9d-16da92f3e02d.png)
אבל, שים לב ששני שיעורים כן נוספו לרשימה, למרות שבחרתי יותר.המקסימום המותר כרגע הוא שלושה שיעורים.
מנקודה זו, אף אחד לא מפריע לי לרשום כל מחיר שמתחשק לי ולהקים את החבילה.
משתמש שלא שם לב להודעת השגיאה פשוט ממשיך ומקים את החבילה שלא כוללת את כל השיעורים שביקש והוא אפילו לא מודע לכך.

הדרך הנכונה הייתה לעצור את הוספת השיעורים החורגת עוד בשלב הלחיצה על "הוסף שיעורים" ברשימת הבחירה. ולא להוסיף אף שיעור. לתת למורה להחליט על אילו שיעורים הוא מוותר בגלל מגבלת הכמות.

בכל מקרה לא לאפשר הקמת חבילה שמחיר מינימום טרם חושב.

**Comment by tom-hollander** [comment]
השינוי שאתה מציע הוא נכון אבל מדובר בשינוי לא קטן משום שמספר הקליפים מגיע יחד עם הקריאה לברור מחיר המינימום.
בכל מקרה התהליך הוא לא אופטימאלי מבחינת חויית משתמש משום שהמשתמש לא יודע מראש כמה קליפים מותר לו לשייך. כרגע תיקנתי ככה שאם הוא בוחר מעל הכמות המותרת, מחיר המינימום יוצג יחד עם השיעורים שלא חורגים מהמקסימום המותר.

**Comment by natan1957** [comment]
אם כך, במקרה כזה יש להוסיף הודעה: ״שים לב!  לא כל השיעורים שנבחרו נוספו לחבילה, מספר השיעורים בחבילה הגיע למקסימום האפשרי״.

**Comment by tom-hollander** [comment]
יש כזו הודעה 
![image](https://cloud.githubusercontent.com/assets/7689853/11768387/32f99f72-a1d4-11e5-9642-37557188d8fd.png)

**Comment by natan1957** [comment]
ההודעה הזאת נמצאת מתחת לראדר, היא לא עוצרת את המשתמש מלבצע שמירה. משתמש סביר לא ישים לב ויקים חבילה עם פחות שיעורים ממה שי=חשב.
יש להציג את ההודעה בחלונית ולדרוש ממנו להקיש "הבנתי".
את נוסח ההודעה לקחת מטבלת הטקסטים.

**Comment by tom-hollander** [comment]
כעת מוצגת הודעה + הטקסט נילקח מהטבלה
PORTAL_TOO_MANY_CLIPS_IN_BUNDLE

**Comment by natan1957** [comment]
במקרה של הצגת ההודעה ולאחר לחיצה על אישור, אין להוסיף אף אחד מהשיעורים לחבילה
הטקסט צריך להיות
לא ניתן להוסיף שיעורים אלה לחבילה, מספר השיעורים בחבילה מוגבל ל ___
![image](https://cloud.githubusercontent.com/assets/6491631/11975795/1ede46ca-a97a-11e5-8e1a-450e5717347f.png)

**Comment by tom-hollander** [comment]
למה הורדת את התגיות טופל ?

**Comment by natan1957** [comment]
כנראה ששכחתי לרשום..
בלחיצה על אישור אין לסגור את טופס הוספת שיעורים אלא להשאיר אותו במצבו הנוכחי.
