### ISSUE TITLE
איטיות עד כדי עצירה בהקמת קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#143]
בחזרה מפייפל להצגת הקופון
![image](https://cloud.githubusercontent.com/assets/6491631/11456619/50740fc6-9697-11e5-851a-ed740d03d3d5.png)

![image](https://cloud.githubusercontent.com/assets/6491631/11456628/8bb44c86-9697-11e5-93fd-7245215926d7.png)

![image](https://cloud.githubusercontent.com/assets/6491631/11456642/643de8e6-9698-11e5-9593-e6aeaf56914c.png)

**Comment by tom-hollander** [comment]
ישנם הרבה דברים שקורים לאחר החזרה מפייפאל.
1. מתבצעת גישה נוספת לפייפאל לביצוע התשלום בפועל( ככה המנגנון שלהם עובד, הגישה הראשונה רק מבצעת ואלידציה)
2. מתבצעות מספר כתיבות לparse על מנת לעדכן את כל התנועות.
מהבדיקה שלי התהליך לוקח בין 5-9 שניות, זה לא מעט במושגים של אינטרנט אבל השתמש מקבל חיווי מהמערכת שהפעולה מתבצעת.
אני מניח שנפלת על מקרה שבו ארעה שגיאה באחד מהתהליכים(אם זה סביבת הבדיקות של הpaypal שהיא לא הכי יציבה) או שהכתיבה לparse התעכבה מעבר לרגיל.  במקרה כזה משתמש הקצה ירענן את הדף
וזה המקום שיש לנו את מנגנון הטיפול בשגויים.
זה לא אופטימאלי אבל כרגע זה פחות או יותר מה שיש בהתחשב באילוצים של הparse
