### ISSUE TITLE
תקלה בהקמת חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#148]
הקמתי חבילה וקיבלתי הודעת שגיאה. בפועל החבילה הוקמה אבל באחד השיעורים לא מופיע לינק לחבילת מבצע.

השיעור gr8MjBc1kU
חבילה tE4yDjtILH
משתמש more11@gmail.com  pw= more11
![image](https://cloud.githubusercontent.com/assets/6491631/11531230/fda8bf2a-9903-11e5-9b2a-287cd529e580.png)

**Comment by tom-hollander** [comment]
מה השגיאה שקיבלת?

**Comment by natan1957** [comment]
הודעה טקסטואלית: חלה תקלה נא לפנות למנהל המערכת..

2015-12-02 15:06 GMT+02:00 tom-hollander <notifications@github.com>:

> מה השגיאה שקיבלת?

**Comment by tom-hollander** [comment]
היתה בעיה במנגנון הלוגים, אני לא רואה מה הבעיה, אנא עדכון שוב אם זה קורה בצירוף תאריך ושעה
