### ISSUE TITLE
לא מציג את החבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#149]
בלחיצה על הקישור החבילה לא מוצגת.
![image](https://cloud.githubusercontent.com/assets/6491631/11538754/ff9fabb8-992b-11e5-8d68-d9555fc3ac33.png)

**Comment by tom-hollander** [comment]
מדובר בחבילה חדשה שיצרת או שזה קשור לבאג שבו קיבלת הודעת שגיאה ביצירת
החבילה?

**Comment by natan1957** [comment]
אני לא יצרתי משהו חדש. נכנסתי, ראית ששלוש השיעורים קשורים לחבילות. הקלקתי וכלום לא קרה..

**Comment by tom-hollander** [comment]
אז יכול להיות שזה קשור לבאג הקודם (משהוא לא נוצר כמו שצריך ) ? אני לא מצליח לשחזר את זה

**Comment by natan1957** [comment]
עכשיו אני רואה שהחבילות של מו4444 אינן בסטטוס אקטיב.
זו סיבה טובה בגללה אני לא מצליח להציג אותן.
אלא שבסטטוס זה, הלינק לא היה אמור להיות מוצג כלל.
![image](https://cloud.githubusercontent.com/assets/6491631/11561746/16027272-99d2-11e5-8d1d-01bc2edb0a85.png)

**Comment by natan1957** [comment]
שתי החבילות האלה נמצאות בסטטוס לא פעיל. הן מוצגות כרגע ע"י המורה
ולמרות זאת, השיעורים שקשורים מוצגים למשתמשים אחרים ולאורחים עם לינק לחבילה. לחיצה על הלינק לא עושה כלום.
user= mo4444 pw= mo4444
![image](https://cloud.githubusercontent.com/assets/6491631/11975634/8352968a-a978-11e5-9249-277ad7cebd73.png)
![image](https://cloud.githubusercontent.com/assets/6491631/11975645/a222a3ca-a978-11e5-9582-ac6f84561796.png)

**Comment by tom-hollander** [comment]
אכן היתה לי טעות בשאילתה, כעת תקין

**Comment by natan1957** [comment]
כרגע השיעור המסומן קשור לחבילה פעילה אבל לא מציג לינק
![image](https://cloud.githubusercontent.com/assets/6491631/12017489/f8b55c92-ad5f-11e5-8b48-284becfb7f8d.png)
![image](https://cloud.githubusercontent.com/assets/6491631/12017498/15469aec-ad60-11e5-89a0-d56f34e1ebcc.png)

**Comment by tom-hollander** [comment]
זה נובע מבאג אחר, כאשר מעדכנים חבילה מקבלים שגיאה. השגיאה קוראת כאשר המערכת מנסה לעדכן את הסימון של שיוך לחבילות על השיעורים. זה טופל

**Comment by natan1957** [comment]
כרגע, השיעור המסומן קשור לשתי חבילות אבל לא מוצג בו לינק "הצג חבילות נוספות"
למען פשטות הכללים:
כל השיעורים בחבילה יציגו לינקים.
שיעור שקשור לחבילה אחת בלבד יציג - הצג חבילת מבצע
שיעור שקשור ליותר מחבילה אחת יציג - הצג חבילות נוספות
![image](https://cloud.githubusercontent.com/assets/6491631/12074583/64d60cc0-b164-11e5-93a5-564b9efb0f10.png)

**Comment by tom-hollander** [comment]
אני לא רואה בעיה , פריט שמקושר ליותר מחבילה אחת מציג קישור. אולי לוקח לזה כמה שניות להתעדכן. אני לא מבין למה צריך להציג קישור "הצג חבילת מבצע" כאשר בפועל אתה כבר רואה את חבילת המבצע.

**Comment by natan1957** [comment]
כדי להעלות את השיעור למעלה וכדי לפשט את הלוגיקה.

2016-01-08 10:02 GMT+02:00 tom-hollander <notifications@github.com>:
