### ISSUE TITLE
הצגת יתרה קודמת

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#152]
ניתן לראות שהיתרה לפני 28/11 היא אפס.
אבל כאשר אני חותך מתאריך זה היתרה הקודמת לא נכונה
ברשומה, הערך הקודם נכון. 
![image](https://cloud.githubusercontent.com/assets/6491631/11586754/d5160f6a-9a7d-11e5-8776-4653960b8cfb.png)
![image](https://cloud.githubusercontent.com/assets/6491631/11586810/2c130840-9a7e-11e5-9aa5-bf97aa800c32.png)

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/11917879/85ee8bae-a722-11e5-9984-d419957e9c07.png)

**Comment by tom-hollander** [comment]
תוכל לפרט

**Comment by natan1957** [comment]
התצוגה הנוכחית חתוכה מ 19 עד 20 בדצמבר.
יתרה קודמת שמוצגת היא אפס. זה לא נכון.
אם לדוגמה תחתוך מתחילת החודש, תוכל לראות שהיתרה לפני ה 19 גדולה מ אפס.
ניתן להבין את זה גם מהעובדה שלא ייתכן שבעקבות הוספת 1.9 ש"ח היתרה תקפוץ מ אפס ל 54 .

בנוגע לדפדוף, היה ברור יותר אם היתרה המוצגת בראש הדף הייתה מציגה את היתרה של התנועה האחרונה של דף קודם ולא של תחילת השליפה.
הערך נמצא למעשה ברשומת תנועה הראשונה המוצגת בדף וקל לקחת אותו משם.למעשה זאת אחת הסיבות שהשדה ערך קודם נמצא שם.

**Comment by natan1957** [comment]
יש פה איזה בלאגן בחישוב יתרה קודמת
איך היא מחושבת  ?
האם היא נלקחת מהיתרה של הרשומה הקודמת? או מהיתרה שברשומת המשתמש ?
שמתי לב שליד היתרה ברשומת המשתמש אין מטבע ואין יתרה שקלית. יש להוסיף

**Comment by tom-hollander** [comment]
בעת כתיבת הרשומות (ביצירת הקופון ) הרשומה נלקחת מהמשתמש מטבלת adminData.
אנא הרחב לגבי הדרישה "שמתי לב שליד היתרה ברשומת המשתמש אין מטבע ואין יתרה שקלית"

**Comment by natan1957** [comment]
בכל טבלה במערכת בה מופיע ערך כספי, יש גם מטבע והערך השקלי.
הוספת ברשומת המשתמש (לא ברור לי למה זהברשומת נתוני אדמין..) שדה כספי, בלי תוספות אלה. לכן יש להשלים.
כרגע יש בלאגן בהצגת יתרה קודמת יש לי תחושה שזה גם בגלל בלאגן במטבעות.

**Comment by tom-hollander** [comment]
הסיבה שהשדה מופיע בנתוני האדמין היא בגלל מגבלה של הparse שלא מאפשר למשתמשים לעדכן נתונים של משתמשים אחרים ,ולכן כאשר השדה היה ברשומת המשתמש , לא ניתן היה לעדכן אותו.
הוספתי balanceNis ואני מעדכן אותו ביצירת הקופון

**Comment by natan1957** [comment]
ביקשתי להוסיף גם מטבע...

**Comment by tom-hollander** [comment]
אנא פרט.להבנתי מדובר במטבע המשתמש

**Comment by natan1957** [comment]
במערכת אידאלית אני מסכים שמטבע המשתמש מספיק..
אבל מכיוון שיש איזה בלאגן במה שקשור להצגת יתרה קודמת, אני חושב שכרגע שדה מטבע יכול לעזור במציאת התקלה..
