### ISSUE TITLE
מחיר תמיכה מרחוק לא מופיע בקופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#154]
מקים קופון לשיעור
bgXgOECLHV
על ידי מו4444 עבור תה4444.
מחיר השיעור 100 מחיר התמיכה 18
אני מקים קופון עם תמיכה. כל החישובים נכונים אבל ברשומת הקופון המחיר המקורי הוא 100 במקום 118
דוגמה לקופון כזה אפשר לראות ב 
R5XNLpjYH0

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/11917792/33fd312c-a71f-11e5-9bb5-0ec326586330.png)

**Comment by tom-hollander** [comment]
תוכל לפרט

**Comment by natan1957** [comment]
סליחההתמונה ששלחתי לא שייכת
כרגע אני רואה שמחיר הקופון + תמיכה לא מופיע במכתבים
![image](https://cloud.githubusercontent.com/assets/6491631/11917867/4582fd98-a722-11e5-9ec8-68a1695477c9.png)
