### ISSUE TITLE
מחיר חבילה חייב להיות קטן לפחות ב 10% ממחיר השיעורים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#155]
![image](https://cloud.githubusercontent.com/assets/6491631/11912863/493e45ba-a659-11e5-8ab8-dfd58c8451a0.png)

**Comment by tom-hollander** [comment]
נרכז תוספות בנפרד

**Comment by natan1957** [comment]
למיטב זכרוני זה קיים באפיון המקורי.
