### ISSUE TITLE
תוספת לשם חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#157]
בממשק אנגלי מתווספת התןספת העברית במקום האנגלית
בנוסף, שם הטופס לא באנגלית
![image](https://cloud.githubusercontent.com/assets/6491631/11917968/f720db76-a725-11e5-8329-52f8d53c6628.png)

**Comment by natan1957** [comment]
בפועל שם החבילה מקבלת את השדה האנגלי הנכון.
האם הקוד שמחשב את השם משוכפל ?
![image](https://cloud.githubusercontent.com/assets/6491631/11917999/569129a2-a727-11e5-9373-cc4ef770319a.png)

**Comment by tom-hollander** [comment]
יש טיפול גם בצד הדפדפן (על מנת להציג את השינויים ) וגם בצד השרת על מנת לבצע ואלידציות ולהכניס לבסיס הנתונים

**Comment by natan1957** [comment]
עניין התוספת לשם חבילה תוקן.
יש להחליף גם את כותרת הטופס מעברית לאנגלית
