### ISSUE TITLE
לא מצליח לעדכן שיעור

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#159]
אני (מורה4444) מנסה לשנות את הסטטוס של השיעור הזה לפעיל והוא נתקע בהודאת "המתן" ולא מסיים את הפעולה
![image](https://cloud.githubusercontent.com/assets/6491631/12001258/98c1be80-aaed-11e5-96b0-a54800a773c6.png)

**Comment by tom-hollander** [comment]
ראיתי בלוג הודעת שגיאה מהparse . אני בודק כעת ונראה שזה עובד
