### ISSUE TITLE
מספר פריטים בסל לא נכון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#162]
![image](https://cloud.githubusercontent.com/assets/6491631/12002453/f00c3f1c-ab06-11e5-96c7-d3c80fe55ad0.png)

**Comment by tom-hollander** [comment]
איך מגיעים לכזה מצב ? אני לא מצליח לשחזר

**Comment by natan1957** [comment]
כאשר מוחקים שורה בקופה, המונה לא יורד באחד.

**Comment by natan1957** [comment]
בלוג אין היו שתי שורות.
הוספתי אחת ע"י בחירת קופון והמספר קפצ ל 4
ta4444 ta4444

**Comment by tom-hollander** [comment]
מה קורה אם מוחקים חבילה שנמצאת כעת בסל של משתמשים ?
(זו הסיבה לבאג ) כרגע אני מתעלם ממנה אבל נשאר זבל בבסיס הנתונים.

**Comment by natan1957** [comment]
אתה צודק.
יש למנוע את זה..
אבל אז, אם מישהו מעביר לסל ולא עושה עם זה כלום.. זה עלול לתקוע את החבילה..
מה דעתך ?

2016-01-08 9:48 GMT+02:00 tom-hollander <notifications@github.com>:

**Comment by tom-hollander** [comment]
לדעתי צריך לאפשר את המחיקה ולעדכן בטבלת הרכישות את כל הרשומות שהן בסטטוס לפני קניה שהן אינן זמינות יותר ולספק חיווי מתאים בממשק המשתמש

**Comment by natan1957** [comment]
ומה אם החבילה כבר נרכשה? האם ניתן למחוק? מה יוצג בחשבון שלי בשורת של הרוכש בשורה?
זה נכון גם לגביי שיעורים (האם יש אופציה למחוק שיעור?). 
מה דעתך על הלוגיקה הבאה:
אם שיעור/חבילה נרכשו, אי אפשר למחוק. רק להוריד סטטוס. 
אם שיעור/חבילה נמצאים בסל (סטטוס = נמצא בסל או דמו) יש לתת התראה למוחק אבל ניתן למחוק ואז זה ימחוק גם את הרשומות שבסל. לא צריך לתת חיווי זה פשוט ייעלם מהסל. זה לא יכול לעשות לרוכש נזק.

**Comment by tom-hollander** [comment]
אתה צודק, אי אפשר למחוק . אולי אפשר לאפשר מחיקה במידה והחבילה עוד לא נכנסה לסל קניות או נקנתה כדי בכל זאת לאפשר מחיקה בלי לזבל את בסיס הנתונים.
