### ISSUE TITLE
כפתור הוסף קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#165]
הוסף קופון והסר קופון מאוד דומים.
מבקש להחליף את הוסף קופון  לפי הדוגמה
![image](https://cloud.githubusercontent.com/assets/6491631/12002780/447de018-ab12-11e5-9f12-3dc1b7ac3f6f.png)
![image](https://cloud.githubusercontent.com/assets/6491631/12002785/5de9dbf6-ab12-11e5-9ff0-b9ca11e2cb17.png)

**Comment by tom-hollander** [comment]
אנא הפנה לבוריס בנושא עיצוב

**Comment by natan1957** [comment]
הועבר לבוריס
