### ISSUE TITLE
ערבוב עברית אנגלית

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#168]
ברירת המחדל של מו4444 הוא אנגלית.
כאשר הוא במצב אנגלית, שהיא ברירת המחדל
לאחר עדכון חבילה חוזר דף עם תוכן אנגלי וממשק שמאל לימין עם תוכן עברי
![image](https://cloud.githubusercontent.com/assets/6491631/12015765/d5efe0ee-ad49-11e5-9f07-bbb3439d98e7.png)

**Comment by tom-hollander** [comment]
לא מצליח לשחזר
