### ISSUE TITLE
תקלה ברכישת קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#169]
ניסיתי להקים קופון לפי הפרטים בתמונה
במקום מסך פייפל קיבלתי מיד את ההודעה על היצירה.
נפתח אירוע, הסטטוס שלו - תשלום נכשל
![image](https://cloud.githubusercontent.com/assets/6491631/12546770/bbabc222-c354-11e5-825e-9239c96e3add.png)
![image](https://cloud.githubusercontent.com/assets/6491631/12546785/daebca92-c354-11e5-9d7f-ef2e80bd89d7.png)

**Comment by natan1957** [comment]
זה קרה שוב.
תקלה יציבה...
![image](https://cloud.githubusercontent.com/assets/6491631/12547077/c630e874-c356-11e5-9db5-70b0266293f0.png)
![image](https://cloud.githubusercontent.com/assets/6491631/12547146/38bb89f8-c357-11e5-8b05-902c810f08b7.png)

**Comment by tom-hollander** [comment]
בדקתי את הלוגים, יש בעיה בממשק מול paypal. אבדוק בערב מה קרה שם. יכול להיות
שזה משהוא זמני .
זו סביבת הפיתוח שלהם ולכן היא פחות יציבה

**Comment by tom-hollander** [comment]
פייפאל שינו את הקוד שלהם, הייתי צריך לשדרג את ה
sdk
כעת זה עובד
*sdk זה הקוד שעובד מול פייפאל. זו ספרייה שמורידים מהאתר שלהם
