### ISSUE TITLE
תקלה בעדכון שערים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#174]
משהו לא טוב קורה בטבלה
CurrencyExchangeRate
השער האחרון נכתב מספר פעמים
rateDate
מוצג לא נכון
![image](https://cloud.githubusercontent.com/assets/6491631/14241887/da1f1e3c-fa56-11e5-91cc-171fb868880c.png)

**Comment by tom-hollander** [comment]
מה זה אומר לא מוצג נכון ?

**Comment by tom-hollander** [comment]
אילו נתונים שנכתבו בזמן הפיתוח, אין צורך להתייחס אליהם. שם לב שהנתונים האחרונים נכתבים באופן תקין

**Comment by natan1957** [comment]
ההסטוריה לא נצברת נכון

**Comment by natan1957** [comment]
תראה כמה רשומות הוקמו ב 3 לאפריל.
זה לא בזמן הפיתוח זה שלשום

**Comment by tom-hollander** [comment]
צודק תוקן
