### ISSUE TITLE
רישום ועדכון משתמשים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#176]
אני לא מצליח לפתוח משתמש חדש ונתקל בשגיאות בעדכון קיים.
![image](https://cloud.githubusercontent.com/assets/6491631/14981276/b8e0b5d6-1136-11e6-97b8-4086bf04373f.png)

**Comment by natan1957** [comment]
רישום מהאפליקציה מצליח.
השלמת פרטים + בקשה להירשם כמורה לא מתפקדת

**Comment by tom-hollander** [comment]
איזה משתמש ניסית לעדכן ?

**Comment by natan1957** [comment]
נסה להקים משתמש בממשק האנגלי.
בפעם הראשונה הוא מודיע שהאותיות של הקפצ'ה לא מתאימות
אז צריך לרשום מחדש את הסיסמאות ולמלא את הקפצ'ה. ואחרי שליחה הוא לא מגיב.
רק אחרי שליחה נוספת, מודיע על הקמה.

**Comment by natan1957** [comment]
סדר הפעולות:
רישום משתמש בממשק אנגלי
כניסה לעדכון פרטי משתמש והוספת כתובת.
כניסה לעדכון פרטי משתמש וסימון "מבקש להירשם כמורה
זה מה שמתקבל
![image](https://cloud.githubusercontent.com/assets/6491631/15848646/d4ee850c-2c96-11e6-8ea3-9eab730f00d6.png)
