### ISSUE TITLE
מנהל לא מצליח להציג אירוע של רכישת חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#177]
ביצעתי רכישת חבילה האירוע
coo8RxlVzy
כשאני נכנס כמנהל לראות את האירוע ב"חשבון שלי" אני עף.
![image](https://cloud.githubusercontent.com/assets/6491631/15093051/3cf6a20e-1484-11e6-994c-3adef76313c2.png)

**Comment by tom-hollander** [comment]
איזה משתמש? Natan?

**Comment by natan1957** [comment]
Ta5555


נשלח מה-iPhone שלי

‫ב-7 במאי 2016, בשעה 19:11, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

> איזה משתמש? Natan?

**Comment by natan1957** [comment]
המנהל הוא natan

**Comment by tom-hollander** [comment]
אני לא מצליח לשחזר את השגיאה
