### ISSUE TITLE
חישובים ברכישת שיעור

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#178]
תה5555 רוכש שיעור מ מו5555.
למו5555 יש סוכן סו5555
אצל המורה ואצל הסוכן העמלות הרלוונטיות = 999. כך שצריך להילקח מהרשימה הגלובלית.

אמורות להיות מוקמות רשומות זיכוי למורה ולסוכן ורשומות חיוב עם אותם הסכומים לאתר.
זה לא קורה.

אירוע 
1OBZRvVIqd

**Comment by tom-hollander** [comment]
מה זה רשומות זיכוי ? אנא הפנה לסעיפים הרלוונטיים באפיון שלא מתקיימים

**Comment by natan1957** [comment]
הואיל ויש מורה ויש לו סוכן והעמלות שלהם = 999 ז"א מטבלה גלובלית, צריכים להירשם תנועות זיכוי מורה וסוכן וחיוב האתר:

כתיבת רשומת זיכוי עמלת מכירה למורה 
כתיבת רשומת חיוב עמלת מורה לאתר
כתיבת רשומת זיכוי עמלת סוכן לסוכן 
כתיבת רשומת חיוב  עמלת סוכן לאתר 

הואיל ולמורה ולסוכן מטבעות שונים מאשר לתלמיד המשלם צריכים להירשם גם תנועות עמלת המרה:

כתיבת רשומת חיוב עמלת המרה למורה 
כתיבת רשומת זיכוי עמלת המרה לאתר 
כתיבת רשומת חיוב עמלת המרה לסוכן 
כתיבת רשומת זיכוי עמלת המרה סוכן לאתר
