### ISSUE TITLE
תצוגה בחשבון שלי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#182]
אירוע Kt6YuNLZoh
אין להציג פריט ספציפי בשורות המתייחסות לרכישת הסל כולו - שורות 4-5 7-10
השורת רכישה (האחרונה) , בלחיצה יש להציג חלונית שיעור או חלונית חבילה בהתאם לתוכן.
פירוט החלונית מתואר בקובץ סקיצה לדף החשבון שלי , שקופיות 9 10 
לחיצה על שורה בעמודת הפעולה צריכה להציג את חלונית סוג הפעולה שמתוארת בשוקפית 4 וכבר פועלת באירועים מסוג רכישת קופון
בשורה 8 החיוב צריך להיות לחשבון האתר ולא לחשבון הסוכן. זו כפי הנראה לא תקלה בתצוגה אלא בתוכנית החישוב.

![image](https://cloud.githubusercontent.com/assets/6491631/15254771/2a6ba49c-1941-11e6-8e03-cc6aada9f087.png)

**Comment by tom-hollander** [comment]
דף החשבון שלי מתאר קופון. אני מבקש  לאפיין את התצוגה במצב של רכישות סל

**Comment by natan1957** [comment]
אין אפיון של רכישת סל.. החשבון שלי מציג אוסף שורות ולכל סוג שורה יש אפיון.
תאור הפריט מוסבר ב"חשבון שלי - תיאור תהליך":
![image](https://cloud.githubusercontent.com/assets/6491631/15267605/20c2c11c-19cf-11e6-930c-43219ad56acd.png)

החלוניות המוצגות מתוארות ב"סקיצה לדף החשבון שלי" שקופית 9 - שיעור, שקופית 10 - חבילה.
![image](https://cloud.githubusercontent.com/assets/6491631/15267629/834bd56c-19cf-11e6-8c51-127bbf977f5d.png)

![image](https://cloud.githubusercontent.com/assets/6491631/15267636/98002e72-19cf-11e6-9baf-3785a1e48d34.png)

**Comment by natan1957** [comment]
הבקשה שלי לבטל את הצגת השיעורים/חבילות בשורות הייתה טעות.
הואיל ושורות אלה לא מתייחסות לסל כולו אלא לפריט ספציפי. בסל.
כמובן שלשורות המתייחסות לכל הסל כגון תשלום, חיוב בגין קבלה ומע"מ אין להציג פריט
 לכן אני מבקש להחזיר את  הפריט לשורות .
זה חשוב במיוחד כשיש כמה פריטים בסל וצריך לדעת מה שייך למי.

**Comment by natan1957** [comment]
האם הצגת השיעור/חבילה הוחזרה ?

**Comment by tom-hollander** [comment]
כן אבל עדיין לא העלתי
