### ISSUE TITLE
מפתח החבילה נרשם ברשומת הרכישה במקום לא נכון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#184]
במקום לשדה הזה
![image](https://cloud.githubusercontent.com/assets/6491631/15274806/4fea0e28-1ac4-11e6-9709-7c68412a7b9f.png)
יש להעביר לשדה הזה
![image](https://cloud.githubusercontent.com/assets/6491631/15274812/79436f8a-1ac4-11e6-829a-494418d38aab.png)
זאת הפקודה ב"טיפול חבילה"
![image](https://cloud.githubusercontent.com/assets/6491631/15274775/89d8b220-1ac3-11e6-907c-321a5746b1c6.png)

**Comment by natan1957** [comment]
לא טופל.
ראה גם נושא 211

**Comment by tom-hollander** [comment]
מבדיקה שלי השדה inbundle מתאכלס במפתחות השיעורים שבחבילה, אנא פרט מה בדיוק לא עובד ומהם השלבים לשחזור כולל שם משתמש, ומזהה חבילה.

**Comment by natan1957** [comment]
החבילה לא מוצגת בחלונית שיעור. לכן כתבתי שייתכן ומדובר רק בתצוגה כפי שמופיע בנושא 211. 

נשלח מה-iPhone שלי

‫ב-10 ביוני 2016, בשעה 13:24, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬
