### ISSUE TITLE
מתעופף בנסיון להציג כמנהל אירוע

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#185]
אירוע wXoEXwwzWZ

![image](https://cloud.githubusercontent.com/assets/6491631/15274960/f16ae918-1ac7-11e6-93a1-65fcc50635f3.png)

**Comment by tom-hollander** [comment]
כנראה אירוע ישן , חסר שם מידע.

**Comment by natan1957** [comment]
איך ישן.. פתחתי אותו היום. 

נשלח מה-iPhone שלי

‫ב-15 במאי 2016, בשעה 21:11, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
אז תכתוב איך כדי שאוכל לשחזר

**Comment by natan1957** [comment]
לא ברור לי מה אתה רוצה לשחזר
בצעתי רכישה של  חבילה + שיעור, בצעתי תשלום(אתה יכול לראות את התשלום באירוע 183) כשאני מנסה לאחזר את האירוע אני עף.
אתה יכול לראות ב parse
רשומות רכישה של שיעורים שהוקמו באירוע ורשומת רכישה של חבילה שעודכנה באירוע
כמו כן אוסף של טרנזקציות כספיות בטבלה 
AccountStatement.
כך שיש רשומות שהשאילתה אמורה להציג.
משום מה היא מתעופפת כפי הנראה מאיזו רשומה מלוכלכת שנוצרה בתהליך.
יש לאתר את סיבת ההתעופפות ולתקן את הליקוי.
אין שום סיבה להפעיל את תהליך הרכישה שוב.

**Comment by tom-hollander** [comment]
מי המשתמש ?, איזה שיעור קנית ?
יכול להיות שההוספה לסל התרחשה לפני מספר ימים ?

**Comment by tom-hollander** [comment]
ראיתי את הבעיה, זה קשור לרכישת חבילה,כעת ברכישות חדשות זה אמור להיות בסדר

**Comment by natan1957** [comment]
כן.
המשתמש ta5555
החבילה של mo5555. מחפשים שיעורים של 5555 ומוצאים שני שיעורים שמחוברים
בחבילה. מוסיפים אותה לסל.
כמו כן הוספתי את ברכות ההפטרה שמופיע כרגע שני ברשימה odgrlAID2Y
בצעתי רכישה ואני מנסה להציג את האירוע.
