### ISSUE TITLE
זיכוי סוכן ברכישת קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#189]
עם אותם נתונים של התקלה הקודמת
שיניתי את העמלות של מו5555 ו סו5555 מ 999 ל 0.3 למורה ו 0.1 לסוכן
האירוע 
7q2zQB9QWj

משום מה לא נוצרת עמלת סוכן
![image](https://cloud.githubusercontent.com/assets/6491631/15287439/761f47dc-1b6b-11e6-8124-86e440210056.png)

**Comment by tom-hollander** [comment]
מה זו התקלה הקודמת ? מה זו עמלת סוכן ? אנא הפנה לסעיף באפיון שחסר וספק בבקשה את כל הנתונים באותו באג

**Comment by natan1957** [comment]
לפי בדיקות שביצעתי, עולה כי עמלת סוכן נלקחת מהרשומה הגלובלית כשהערך ברשומת הסוכן הוא אפס במקום שזה יתנהג כך כשהערך הוא 999.
בנוסף, כאשר הערך הוא גדול מאפס, 0.2 לדוגמה, החישוב מתייחס כאילו אפס ולא מחייב את הסוכן.
אותו הדבר גם לגבי הערך 999.

**Comment by tom-hollander** [comment]
לא מצליח לשחזר ראה אירוע YNBfsNcNGZ. אנא כתוב במסודר את כל השלבים לשחזור התקלה

**Comment by natan1957** [comment]
עמלת סו4444 כרגע היא אפס
באירוע rjdFdQpaPk
ביצע מו4444 רכישת קופון.
למרות שעמלת הסוכן אפס ניתן לראות שחושבה לו עמלה של כ 19 ש"ח.
עמלה זו מהווה 10 אחוז ז"א שזה נלקח מרשומת העמלות הגלובלית.
גישה לרשומה הגלובלית צריכה לקרות רק כאשר בעמלת הסוכן יש ערך של 999.

**Comment by natan1957** [comment]
עדיין לא תקין

**Comment by tom-hollander** [comment]
לא ברור

**Comment by natan1957** [comment]
עמלת סוכן אמורה להילקח מרשומת הסוכן אלא אם היא 999 ואז נלקחת מרשומת עמלות גלובלית.
במקרה שעמלת הסוכן ברשומת הסוכן = 999 העמלה אכן נלקחת מהרשומה הגלובלית. זה טוב.
אבל במקרה והיא שונה מ 999 לדוגמה 0.15 (שזה 15%),  החישוב מתייחס כאילו העמלה היא אפס ולא מזכה את הסוכן בעמלתו.
ניתן לשחזר ע"י רכישת קופון כלשהו ע"י מו5555.
סו5555 הוא סוכן של מו5555 ואמור לקבל עמלה בגובה 15%. אבל הוא לא מקבל כלום.
אם תשנה את עמלת בסוכן ברשומה של סו5555 ל 999 ותבצע שוב את הרכישה, תוכל לראות ש סו5555 מקבל עמלה של 10% שזו העמלה הנקובה ברשומה הגלובלית.

**Comment by tom-hollander** [comment]
אני לוקח את עמלת הסוכן משדה acpTeacherCommission זה נכון ?

**Comment by natan1957** [comment]
כן, מרשומת הסוכן אלא אם הערך 999 ואז מרשומת העמלות הגלובלית
