### ISSUE TITLE
המרת מטבעות בפייפאל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#192]
ברכישת קופון המשתמש צריך לשלם 60 סטרלינג.
הופיע ממשק פייפל חדש שממיר את הסטרלינג לדולר
לא מצאתי דרך לשנות את זה בפייפאל חזרה לסטרלינג
למה המיר לדולר? זה יבלבל את המשתמש

**Comment by tom-hollander** [comment]
כי המשתמש מוגדר לדולרים בpaypal . צריך להכנס להגדרות המשתמש
