### ISSUE TITLE
מתעופף בתצוגת אירוע

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#193]
event = bUYOmBWjVn
user = ta5555
נרכשו שני שיעורים וחבילה
![image](https://cloud.githubusercontent.com/assets/6491631/15449753/7ca9d84c-1f8f-11e6-8e06-da9e4f18fcf6.png)

**Comment by natan1957** [comment]
האירוע עדיין מתעופף בהצגה

**Comment by tom-hollander** [comment]
לא עלה עדייו

**Comment by natan1957** [comment]
תודיע כשיעלה. 

נשלח מה-iPhone שלי

‫ב-21 במאי 2016, בשעה 21:54, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
כעת תקין
