### ISSUE TITLE
תצוגת שיעור

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#194]
event = osMU6ffLgJ
שיעור שמוצג כפריט ברשומת עו"ש צריך להופיע עם תראר כפי שמופיע ברשומת רכישה.
חלונית שיעור נפתחת רק כשמקישים על שורת עו"ש ולא על שורת רכישה. צריכה להיפתח גם ברשומת רכישה.
מורה רוכש ומקבל צריכים להיות מוצגים עם קו תחתון ולחיצה מעתיקה את התוכן למשתמש

![image](https://cloud.githubusercontent.com/assets/6491631/15449891/3899c730-1f93-11e6-94bc-50297cb9d858.png)

![image](https://cloud.githubusercontent.com/assets/6491631/15449873/a69b5254-1f92-11e6-9109-9187d48208fb.png)

**Comment by tom-hollander** [comment]
"שיעור שמוצג כפריט ברשומת עו"ש צריך להופיע עם תראר כפי שמופיע ברשומת רכישה."  לא ברור , לקחתי לפי השדות שתיארת במצגת, מאיזה שדה יש לקחת את התיאור ?

**Comment by natan1957** [comment]
מופיע בעמוד 2 במסמך "החשבון שלי - תאור תהליך" בדרופ-בוקס
לפי התאור הזה הכנת את התצוגות הקודמות, ניתן להשתמש גם כאן.

![image](https://cloud.githubusercontent.com/assets/6491631/15479000/985897de-2126-11e6-822e-dc94a5985076.png)

**Comment by tom-hollander** [comment]
לא מצליח להבין מה לעשות

**Comment by natan1957** [comment]
זה אמור להיות פשוט.
אתה אמור להציג את השיעור בשורת העו"ש כפי שאתה מציג אותו בשורת הרכישה
ואת החבילה ברשומת העו"ש כפי שאתה מציג אותה בשורת רכישה
במעבר עכבר צריך להופיע פופאפ של שם הפריט ובהקלקה להיפתח חלונית רלוונטית
![image](https://cloud.githubusercontent.com/assets/6491631/15483221/3a57bc9e-213c-11e6-87a1-2854acbd4357.png)
