### ISSUE TITLE
מיון שורות 

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#200]
בהצגת טרנזקציות של  מו5555 במיון יורד יש שיבוש בסדר ההצגה.
במיון עולה זה עולה זה מוצג תקין

![image](https://cloud.githubusercontent.com/assets/6491631/15625473/5c32bfb8-24b0-11e6-8ba5-628289ccf279.png)

![image](https://cloud.githubusercontent.com/assets/6491631/15625459/f81c96ac-24af-11e6-8c02-8e2c7d71e5d6.png)

**Comment by tom-hollander** [comment]
מה לא בסדר במיון ?

**Comment by natan1957** [comment]
הסדר למעלה היה צריך להיות 
60.78
100.78
101.12

אבל הוא 
60.78
101.12
100.78
