### ISSUE TITLE
חישוב  זיכוי בגין רכישה ברכישת חבילה כשהיתרה שלילית

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#205]
event Onh0nGwvVB
נתוני הבסיס: עלות חבילה 690 יתרה מינוס 180 לתשלום 870.
כך גם חוייב בפייפל.
אבל בחישוב מוצג כאילו חוייב 1050 שזה 870 פלוס 180.
זה מייצר למשתמש יתרה חיובית

![image](https://cloud.githubusercontent.com/assets/6491631/15627063/f567bb4a-24e0-11e6-90de-a4f60b6e4305.png)

![image](https://cloud.githubusercontent.com/assets/6491631/15627081/7ff15eba-24e1-11e6-93d0-4d5cf51fab0f.png)

**Comment by natan1957** [comment]
עדיין לא תקין
event = pJQtVmpbf1
![image](https://cloud.githubusercontent.com/assets/6491631/15635184/4e27d8b4-25e0-11e6-971c-ea7799f48353.png)

**Comment by tom-hollander** [comment]
מה לא תקין

**Comment by natan1957** [comment]
מצורפות שלוש דוגמאות של אכלוס לא נכון של הערך 
basketPrice
בסעיף כתיבת רשומת חיוב משלם בגין קבלת התוכן  
שים לב שהשדה אמור להתאכלס בתחילת התוכנית מאחד הערכים סה"כ לתשלום(ערך הסל) או לאחר הנחת קופון אם יש קופון.
![image](https://cloud.githubusercontent.com/assets/6491631/15641896/8bcb5896-264c-11e6-96f0-92ee3e6cbe58.png)

החיצים בירוק מציגים את האכלוס הנכון שאם היה מתבצע היה מאפס את יתרת המשתמש בסוף הטרנזקציה
אחרי התיקון של זה אבדוק את השאר.
![image](https://cloud.githubusercontent.com/assets/6491631/15641881/6ce08d5c-264c-11e6-963a-483e7aac4378.png)

**Comment by tom-hollander** [comment]
לא מבין את הבעיה, וגם לא סיפקת נתונים לבדיקה, אתמול בלילה הכנסתי תיקון לreduceFromBalance. ממתי הדוגמאות האלו ?

**Comment by natan1957** [comment]
הבעיה היא באכלוס לא תקין של השדה basketPrice
שתי דוגמאות מהבוקר ואחת מאתמול. כולן מצביעות על אופן האכלוס הנכון. 

נשלח מה-iPhone שלי

‫ב-30 במאי 2016, בשעה 10:42, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
אם האיכלוס נכון, אז מה הבעיה ?
אתה יכול לצרף את הנתונים לבדיקה ? אני לא יכול לשחזר את זה לפי צילום מסך.
זה מאוד יעזור אם כל פעם שאתה פותח באג, תכלול את כל הנתונים
אם אין לך זמן באותו רגע, עדיף שלא תכתוב כלום מאשר שאנסה כל פעם להבין חלקי משפטים, אנא כבד גם את הזמן שלי
מה המשתמש
מה השיעור שרכש
מה ציפית לקבל
מה קיבלת
אני לא מבין מה הקשר בין המשפט "שים לב שהשדה אמור להתאכלס בתחילת התוכנית מאחד הערכים סה"כ לתשלום(ערך הסל) או לאחר הנחת קופון אם יש קופון." לבין האפיון שצירפת
איזה שדה? מה זה אחד הערכים סה"כ לתשלום ?

**Comment by natan1957** [comment]
האיכלוס לא נכון. החיצים הירוקים בדוגמאות מציגים את האיכלוס הנכון.
שני האירועים הראשונים הם
event 1FEyODww7n
event s1rJ9gznuj
השלישי ישן. אין לי אותו.
בתחילת ההודעה נאמר שמדובר בשדה 
basketPrice
האפיון מציג איך יש לאכלס אותו.

**Comment by tom-hollander** [comment]
סליחה אבל אני לא מצליח להבין את הבעיה, אני כנראה לא מבין מה המשמעות של החיצים

**Comment by natan1957** [comment]
נדבר. 

נשלח מה-iPhone שלי

‫ב-30 במאי 2016, בשעה 12:17, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬
