### ISSUE TITLE
תצוגת קופון חלונית קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#206]
event = jQ3FZ5gh5P
יש לוודא שפריט קופון מוצג באותה צורה גם בשורות מסוג עו"ש וגם בשורות מסוג קופון.
צריכ לכלול "עבור שיעור/חבילה"
מעבר על קופון בכל סוג שורה צריך להקפיץ פופאפ
הקלקה על קופון בכל סוג שורה צריך לפתוח חלונית קופון.
כרגע יש שונות בהתנהגויות
![image](https://cloud.githubusercontent.com/assets/6491631/15632486/e380705a-259b-11e6-8772-ef273f6035ff.png)

**Comment by tom-hollander** [comment]
לא ברור
יש לוודא שפריט קופון מוצג באותה צורה גם בשורות מסוג עו"ש וגם בשורות מסוג
קופון.
צריכ לכלול "עבור שיעור/חבילה"

2016-05-29 12:50 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
אתה יכול לראות שאותו הקופון מוצג באופן שונה בשורה מסוג עו"ש ובצורה מסוג קופון
![image](https://cloud.githubusercontent.com/assets/6491631/15632798/9f484494-25a5-11e6-9398-a06e7ec86946.png)

**Comment by natan1957** [comment]
עכשיו החלוניות מוקפצות בסדר אבל תיאור הקופון עדיין שונה. לא מוצג אם הקופון לשיעור או לחבילה
event = mb2hhch9vq
![image](https://cloud.githubusercontent.com/assets/6491631/15635355/59e37d5c-25e5-11e6-8e33-2ae972893f4d.png)
