### ISSUE TITLE
מיון תנועות כספיות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#208]
סדר הטרנזקציות מופיע הפוך. היתרה צריכה להיות אפס ולא 600
ניתן לראות שבהצגת האירוע שכולל את אותן טרנזקציות הסדר המוצג הוא נכון
event = sbIRsClbLn  user = ta5555

![image](https://cloud.githubusercontent.com/assets/6491631/15735018/c5361f46-289d-11e6-8114-08a26ac816c0.png)

![image](https://cloud.githubusercontent.com/assets/6491631/15734991/9431e060-289d-11e6-880d-f0d9c853a546.png)

**Comment by tom-hollander** [comment]
יש כאן מגבלה טכנית בגלל הparse. ההסבר: הסיבה שזה ממויין כמו שצריך באירוע היא שבאירוע השליפה ממויינת לפי עמודת order. בשליפה לפי משתמש אני ממיין לפי עמודת createdAt , עמודת תאריך. בעת עדכון הרשומות נשלחות לparse בbatch מטעמי ביצועים, והparse כנראה רושם אותם כחבילה  ולכן הסדר לפעמים נקבע שרירותית בהפרשים של של מילישניות. אז במקרה הנדון הרשומה הראשונה נרשמה 2016-06-02T05:24:41.681Z והשניה 2016-06-02T05:24:41.682Z (הפרש של מילישניה). אפשר לסדר את זה ע"י עדכון של כל רשומה בנפרד אבל תהיה לזה השפעה מאוד גדולה על הביצועים. אפשרות שניה היא להוסיף עוד עמודה סידורית שתכיל את מספור שורות בעבור כל משתמש  לפני פעולת העדכון אבל הבעיה כאן היא שלא ניתן לנעול טבלאות כמו בבסיס נתונים רלציוני ולכן בזמן הוספה של רשומות למשתמש אחד תאורתית ניתן להוסיף מתהליך אחר רשומות לאותו המשתמש וליצור בילבול במיספור. יש לך רעיון ?
