### ISSUE TITLE
הערות על מכתב למנהל על מכירת פריט

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#216]
המכתב צריך להישלח למנהל ולא לתום

הכותרת צריכה להיות: הודעה למנהל על רכישת שיעור - מס שיעור  באירוע - מספר אירוע
כמובן שבמקרה של חבילה צריך להופיע חבילה.
הוספתי את הטקסט "הודעה למנהל על" לאפיון

חסר סמל מטבע בעמלת אתר בקופון ועמלת מורה בקופון

יש למחטק את המילה בקופון

בעמלת המרה יש להוסיף מורה וסוכן. עדכנתי באפיון

![image](https://cloud.githubusercontent.com/assets/6491631/16376648/0add1de4-3c6a-11e6-90a7-25fb4e6cc72f.png)

**Comment by tom-hollander** [comment]
ניתן לשנות את הכתובת בממשק של הפארס תחת הגדרות (אשלח מייל הסבר)
הכותרת היא כפי שרצית באפיון, השינוי צריך להיות מתומחר כנל הוספה של עמלות המרה.
הסיבה שחסר סמל מטבע היא שביקשת שזה יהיה מטבע של הקופון, היות ואין קופון אין מטבע.

**Comment by natan1957** [comment]
לא שלחת את ההסבר על הכתובת
לא נדרש תוספת לכותרת אבל היא צריכה להופיע בעברית לא משובשת: רכישת חבילה(או שיעור)  א באירוע - ב.
בנוגע לעמלות ההמרה, בסך הכל להוסיף את המילה "למורה" בעמלת מורה כך שיהיה  כך שיהיה "עמלת המרה למורה" ולא כמו עכשיו
ובהתאמה להוסיף את המילה "לסוכן" בעמלת ההמרה לסוכן

באירוע ySfnTttQLc
יש מכירת שיעור  
4dwe69ToGo
לא ברור לי למה לא מוצג מע"מ
![image](https://cloud.githubusercontent.com/assets/6491631/16545240/9f46da84-412d-11e6-98dd-af49cc60d0a3.png)

**Comment by natan1957** [comment]
הכותרת עדיין משובשת.
על פי האפיון זה צריך להיות: רכישת שיעור(או חבילה) אאא באירוע - בבב
![image](https://cloud.githubusercontent.com/assets/6491631/16661146/468d0706-447a-11e6-97e1-df28f517a56b.png)
כרגע המילה שיעור מוצגת אחרי קוד השיעור במקום לפניו
![image](https://cloud.githubusercontent.com/assets/6491631/16661252/c1158138-447a-11e6-81a9-5afd8911bb3f.png)

**Comment by tom-hollander** [comment]
לא מצליח לשחזר , אני מקבל כותרת תקינה

**Comment by natan1957** [comment]
גם אני קיבלתי תקין.
סוגר בשלב זה
