### ISSUE TITLE
הערות על מכתב סיכום אירוע

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#218]
סכום זיכוי אתר מאופס

תאור הפריט נכון! שיעור ולא חבילה

המכתב נשלח לתום. צריך להישלח לכתובת האתר. כדי שתוכל לראות את המכתבים הוספתי שדה 
allLettersInbox
בטבלת העולמות
מכתבים למורה לסוכן ולמשתמש ותלמיד יישלחו עם העתק נסתר לכתובת האתר
מכתב מכירת פריט וסיכום מכירה יישלחו לכתובת האתר
כל המכתבים יישלחו עם העתק נסתר לכתובת שרשומה בשדה 
allLettersInbox
ברשומת טבלת עולמות
אתה תוכל לצפות במכתבים בתיבת דואר זו
![image](https://cloud.githubusercontent.com/assets/6491631/16379769/1fb92e08-3c7c-11e6-9c76-df0d89427c98.png)

**Comment by tom-hollander** [comment]
סכום זיכוי טופל.
שאר הדברים כרוכים בשעות פיתוח שצריך לשלם עליהם היות וזה לא היה בתמחור
