### ISSUE TITLE
הצגת חלונית פריט

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#219]
בכניסה כמנהל והתחזות למשתמש, אני מנסה להציג חלונית פריט ולא מצליח. מופיע רק הפופ-אפ.
user = yeroham
לעומת זאת חלונית הפעולה (אירוע) מוצגת תקין
בתצוגת אירוע החלונית מוצגת תקין.
![image](https://cloud.githubusercontent.com/assets/6491631/16412074/06b68254-3d33-11e6-8ae2-7b1ae6e36042.png)

**Comment by tom-hollander** [comment]
זה לא עובד בלי קשר להתחזות. כנראה בגלל מחיקת הרכישות או שיעורים. יצרתי רכישה חדשה , שם החלונית מופיעה

**Comment by natan1957** [comment]
אתה לא יודע בוודאות למה זה לא מציג?
לפי דעתי אני לא מוחק שיעורים. אני משנה להם את הסטטוס. צריך לדעת כדי להימנע מפעולה לא נכונה. 

נשלח מה-iPhone שלי

‫ב-29 ביוני 2016, בשעה 18:22, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
אותו שיעור שמוצג תקין בתצוגת אירוע
event = wCexwlEEK0
לא מוצג בתצוגת תנועות משתמש
![image](https://cloud.githubusercontent.com/assets/6491631/16479118/d4d6da98-3ea6-11e6-94a5-1682ebc44cc0.png)
![image](https://cloud.githubusercontent.com/assets/6491631/16479134/f1e06b86-3ea6-11e6-8d89-fc2728cdfe7c.png)

**Comment by tom-hollander** [comment]
טופל, זה חייב רשומת Purchace ולכן אם מוחקים אותה , החלונית לא תופיע

**Comment by natan1957** [comment]
צילמתי שני מצבים של הצגת אותה שורה.  באחד החלונית נפתחת (ז״א שיש רשומת רכישה) ובשני החלונית לא נפתחת. למרות שכאמור יש רשומת רכישה. 

נשלח מה-iPhone שלי

‫ב-1 ביולי 2016, בשעה 17:47, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
במקרה המצולם, ברשומות accountstatements  שלevent שלהם יש purchase  מופיעה לחלונית

**Comment by natan1957** [comment]
התשובה משובשת.. תכתוב או בעברית או באנגלית אבל לא במעורב. בכל מקרה, לא ברור לי למה אותה רשומה מאפשרת הצגת חלונית פריט בתצוגת אירוע ולא מאפשרת בתצוגת חשבון משתמש. 

נשלח מה-iPhone שלי

‫ב-2 ביולי 2016, בשעה 07:41, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬
