### ISSUE TITLE
הצגת אירוע מתעופפת

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#221]
event = h5fF0XyG1Y
לא ניתן להציג את האירוע. מתעופף

בנוסף, שם אחד הפריטים לא מופיע במכתבים
![image](https://cloud.githubusercontent.com/assets/6491631/16540172/6388d8aa-4063-11e6-958e-9e073f6bc796.png)

**Comment by tom-hollander** [comment]
בעיית ההתעופפות נגרמת בגלל שברכישת חבילה , כאשר החבילה מפורקת לרכישות של שיעורים, הרכישה של שיעור לא מקבלת נתון של מטבע המשתמש. תיקנתי את זה ,
לגבי הנתון החסר במכתב, מהם הפריטים שרכשת? אם אתה נתקל בבעיה, תכתוב את כל הפרטים כי זה חוסך מלא זמן

**Comment by natan1957** [comment]
השיעור החסר הוא 
4dwe69ToGo
מה שמיוחד בו זה שעמלת המורה אפס.
לכן אין טרנזקציות כספיות למורה וזה בסדר.
אבל שם השיעור צריך להופיע.
אני מצרף צילום של המכתב למורה. גם שם שם השיעור חסר.
![image](https://cloud.githubusercontent.com/assets/6491631/16541012/f09891be-4080-11e6-97e0-36b30596001e.png)

**Comment by tom-hollander** [comment]
זה טןפל
