### ISSUE TITLE
הערות על חשבונית/קבלה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#222]
להוסיף את המילה תאריך ולהעביר לראש הדף
לבטל את ההצגה בשקלים(במטבע האתר) ולהציג רק במטבע המשלם.
להציג במע"מ רק שתי ספרות אחר הנקודה
להוסיף קו תחתון במקום החתימה
לרווח את השורות בדומה לאפיון

![image](https://cloud.githubusercontent.com/assets/6491631/16544358/febf6160-410b-11e6-98e9-7dbf1c05bd86.png)

**Comment by tom-hollander** [comment]
העימוד הינו כפי שביקשת באפיון וכפי שמתאפשר בhtml שנתמך במייל. היות ועברתי את מכסת השעות(בהרבה מאוד) אני לא מבצע שינויים במסגרת התכולה. לאחר סגירת השעות נוכל לתמחר את השינויים שאתה מבקש

**Comment by natan1957** [comment]
בשלב זה אני מוותר על הזזת התאריך.
הקידומת "תאריך - " הייתה באפיון המקורי
ביטול הצגת השדות 
"(", basketPriceNISLetter , siteCurrencySymbolLetter , ")".
זה לא שינוי בעימוד, זה סתם מחיקת שדה שהשתרבב בטעות...

**Comment by natan1957** [comment]
המע"מ עדיין מוצג לא תקין
שתי ספרות אחרי הנקודה
המטבע צריך להופיע משמאלו
![image](https://cloud.githubusercontent.com/assets/6491631/16662914/877c3d74-4482-11e6-8159-1345f40d2028.png)

**Comment by natan1957** [comment]
תצוגת המע"מ לא טופלה
![image](https://cloud.githubusercontent.com/assets/6491631/16977993/2c6ff346-4e62-11e6-8eb5-126d4939f8c1.png)

**Comment by natan1957** [comment]
ייתכן והמע"מ טופל אבל אני רואה פתאום  מחיר חבילה לא מעוגל.. יש לוודא שכל הסכומים יהיו מעוגלים לרמה של אגורות.

![image](https://cloud.githubusercontent.com/assets/6491631/17077688/d4065128-50e1-11e6-9a75-884d81001827.png)
