### ISSUE TITLE
דפדוף בחשבון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#224]
מספר הדפים המוצג בחשבון לא נכון 
maam2
תאריכים 
1/5/16 - 3/7/16

![image](https://cloud.githubusercontent.com/assets/6491631/16547571/8ada10d6-417b-11e6-884f-00bcc49d7e18.png)

**Comment by tom-hollander** [comment]
?מה הסיסמה של המשתמש

**Comment by natan1957** [comment]
אתה לא צריך סיסמה. אתה נכנס כמנהל ומתחזה ל 
maam1
או ל
maam2
שזה מע״מ יתרות

נשלח מה-iPhone שלי

‫ב-4 ביולי 2016, בשעה 07:00, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
כנראה שהיתה תקלה נקודתית בפארס, אני לא מצליח לשחזר את התקלה כעת

**Comment by natan1957** [comment]
כרגע שחזרתי.
אני נכנס כמנהל ומתחזה למעמ2 חותך את התאריכים הנ"ל
![image](https://cloud.githubusercontent.com/assets/6491631/16681198/e9b57e14-44fb-11e6-8f2d-c652cca30938.png)
