### ISSUE TITLE
הצגת שעה בחלונית אירוע וקביעת שעת מערכת

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#227]
event ySfnTttQLc 
user ta5555
לפי בסיס הנתונים האירוע נוצר בשעה 22:16 ובחלון הוא מוצג 10:16. יש לתאם את התצוגה.

השעון של הפרס מכוון לשלוש שעות לפני שעת ישראל.
האירוע הזה נוצר לפי שעון ישראל ב 3/7 בשעה 1:16 אחר חצות. באותו הזמן שעון בסיס הנתונים נמצא ב 12/7 22:17 ז"א יום לפני כן.
כתוצאה מזה, מוצגת כוכבית בשורת העו"ש.
לשם כך יש לוודא שהערך 
today
שמועבר ל 
duedate
יהיה זמן הפרס ולא זמן ישראל.
אלא אם אתה מוצא שזה יפריה במקום אחר...

![image](https://cloud.githubusercontent.com/assets/6491631/16707202/292bb5b2-45cf-11e6-9b2d-e93b8e9e7d22.png)

![image](https://cloud.githubusercontent.com/assets/6491631/16707216/7d62aa50-45cf-11e6-984c-5e7067e68a6f.png)

![image](https://cloud.githubusercontent.com/assets/6491631/16707248/199dc2d8-45d0-11e6-9382-c9a4f12d358c.png)

**Comment by tom-hollander** [comment]
הפארס שומר את התאריכים ב
UTC
הכנסתי תיקון שבו אני מסב את התאריך 
dueDate
ל
UTC
אבל זה לא יהיה מדוייק במידה והזמן על השרת (היכן שמאוכסן האתר) לא בדיוק תואם את הזמן של שרת הפארס.

**Comment by natan1957** [comment]
לא ברורה לי המשמעות. המערכת צריכה לעבוד עם שעון אחד לשרת ולבסיס הנתונים. אחרת נוצרות אנומליות. לא ברור לי מה התיקון עושה ומתי לא יתפוס. 

נשלח מה-iPhone שלי

‫ב-16 ביולי 2016, בשעה 16:07, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
בד"כ שרתים מסונכרנים דרך שירות רשת כך שהם אמורים להיות תחת שעון אחד. בפועל אני לא יכול להתחייב שparse או הספק עושים את זה. למה בעצם עובדים עם 
dueDate 
ולא משווים 
created ו
updated ?

**Comment by natan1957** [comment]
זה נועד למקרה שהתהליך נופל באמצע ולא כל הרשומות נכתבות לבסיס הנתונים. 
תהליך שחזור/תיקון שיכול להיות מופעל לאחר כמה ימים אמור לכתוב את הרשומות. תאריך היצירה יהיה יום הכתיבה. אבל תאריך הערך (התאריך הנכון בו בוצעה העסקה) הוא תאריך שרשום ברשומת האירוע ששומרת את כל הנתונים. 

נשלח מה-iPhone שלי

‫ב-19 ביולי 2016, בשעה 16:52, ‏‏Tom Hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
שדה ה
Updated
מתעדכן אוטומטית והןא יתעדכן כאשר התהליך התאוששות יעבוד.אז למה לא להשתמש
בזה? ככה יהיה שעון אחד בתהליך

**Comment by natan1957** [comment]
תהליך ההתאוששות במקרים רבים כותב רשומות שלא נכתבו בתהליך שכשל. לכן תאריכי הפרס יהיו גדולים מהתאריך בו בוצעה הרכישה.
הטרנזקציה הכספית בוצעה שלשום.. והכתיבה נכשלה אז היום מתבצע שחזור.
תאריכי ההקמה והעדכון של הפרס יהיו של היום אבל תאריך הטרנזקציה היה שלשום.
לכן יש צורך לשמור את תאריך הטרנזקציה ברשומה בנוסף לתאריכי הפרס.
בהצגת החשבון שלי מוצגות הטרנזקציות לפי סדר הכתיבה הפיזי (תאריכי פרס) אבל אם יש הפרש בינם לתאריך הטרנזרציה מוצגת כוכבית וחלונית עם תאריך הטרנזקציה(שלשום).
הבעיה היא שעון פרס מוקדם יותר ב 3 שעות משעון השרת. לכן  לדוגמה רכישה באחת אחר חצות הדיו-דייט מקבל את התאריך של היום החדש אבל הפרס מתנהל שלוש שעות אחורה והתאריך של כתיבת הרשומה הוא של אתמול.
זה כאמור מדליק כוכבית למרות שאין פה פערי זמן אמיתיים.

הצעה לפתרון:

מה שאני מציע זה שהכוכבית תידלק רק במקרים בהם תאריך הכתיבה(פרס) גדול מתאריך הטרנזקציה(דיו-דייט) ולא שונה כפי שהיום.
זה ימנע מהמקרה שבדוגמה להדליק את הכוכבית הואיל ובמקרה זה תאריך הפרס קטן מתאריך הטרנזקציה.

**Comment by natan1957** [comment]
תצוגת השעה עדיין לא טופלה.
צריך להיות מוצג 22 ולא 10
![image](https://cloud.githubusercontent.com/assets/6491631/17077565/0fccb8fa-50dd-11e6-8c51-4f3bfa174cbc.png)
