### ISSUE TITLE
לא מסכים לקבל תאריך למרות שהוא עתידי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#228]
clip = gdNTFlmsos
![image](https://cloud.githubusercontent.com/assets/6491631/16772342/870b99c4-485c-11e6-950b-fb09239e8bd8.png)

![image](https://cloud.githubusercontent.com/assets/6491631/16772267/4b21d54a-485c-11e6-86e5-2461558c8bcd.png)

**Comment by tom-hollander** [comment]
חשוב לנקות קש בדפדפן
