### ISSUE TITLE
בלאגן ברכישת קופון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#230]
תקלה מוזרה בתהליך שכבר מזמן עבד נכון
event H22vOISIyY
user ta4444
רוכש קופון עבור תה5555
שיעור של המורה אלעד
לתה5555 מגיע מכתב לתה4444 לא מגיע
בחשבון של תה4444 לא מוצגת טרנזקציית החיוב.
מבדיקה בפרס מצאתי את האירוע והצגתי אותו.
האירוע מציג כאילו אלעד ביצע את הרכישה עבור תה4444
בפועל הקופון נמצא בדף הרופה של תה5555
בלגאן
![image](https://cloud.githubusercontent.com/assets/6491631/17057847/9bc50dd4-5025-11e6-8423-a925d6b1b626.png)
![image](https://cloud.githubusercontent.com/assets/6491631/17057867/be2aad0c-5025-11e6-83cb-7457c8b9c100.png)
![image](https://cloud.githubusercontent.com/assets/6491631/17057898/ed36bf1e-5025-11e6-868c-6b1cc8e0633f.png)
![image](https://cloud.githubusercontent.com/assets/6491631/17057926/10b2794c-5026-11e6-8ac6-c5dc3a8c777b.png)
![image](https://cloud.githubusercontent.com/assets/6491631/17058016/9027c024-5026-11e6-8850-490eefe95bd3.png)

**Comment by tom-hollander** [comment]
אני מנסה לבדוק עם ta4444  ולא מצליח לבצע לוגין ,מהי הסיסמה?
לעניין שליחת המייל, אני רואה שאמור להשלח מייל למשתמש ולמורה , כך זה תמיד היה אין מייל שלישי
לעניין מי ביצע את הרכישה , על איזה שדה מדובר ?

**Comment by natan1957** [comment]
ta4444 pw= 123ta444456
אני מבצע בדרך כלל את הפעולות ע"י התחזות ואז לא צריך סיסמה
למיטב זכרוני העתק המכתב לתלמיד אמור להישלח למורה
עד עכשיו לא בדקתי את משלוח המכתבים אבל עכשיו פתחתי תיבות לכל המשתמשים כדי לבדוק את זה.
העתקים סמויים צריכים להישלח לכתובת האתר כמו בתהליך הקופה.
לא הבנתי את השאלה האחרונה

**Comment by natan1957** [comment]
מתוך האפיון
![image](https://cloud.githubusercontent.com/assets/6491631/17059404/9c948e9e-502d-11e6-8a92-e96889a874ab.png)

**Comment by tom-hollander** [comment]
התחזות זה נתון מאוד חשוב לבאג , זה מסוג הדברים שאתה צריך לספר לי
לפי מה אפשר לדעת שאלעד ביצע את הרכישה ? איך מבינים את זה מהארוע, מהם שמות השדות שעליהם אתה מסתמך ?
