### ISSUE TITLE
חישוב קופון מנהל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#231]
יצרתי קופון מנהל 
coupon = to0FqotxFp
בקופון מנהל חישוב עמלת אתר ועמלת מנהל מתבצעת על פי שורות אקסל 230 240.
החישוב מקטין באופן פרופורציוני את עמלת האתר ועמלת המורה.
ז"א שאם עמלת המורה היא 30% = 120 ש"ח ואז עמלת האתר  70% = 280 ש"ח, אם אקטין את המחיר לתלמיד  מ 690 ל 100, עמלת המורה תהיה 15% = 30ש"ח ועמלת האתר 35%. = 70ש"ח
בקופון שהקמתי נרשם למורה עמלה אפס ולאתר  100ש"ח
להלן מכתב רכישה שעשה שימוש בקופון ומציג את היחס השגוי בין עמלת מורה לעמלת אתר
![image](https://cloud.githubusercontent.com/assets/6491631/17077772/6e5c49be-50e5-11e6-8853-de8306970f7d.png)

**Comment by tom-hollander** [comment]
זה 0 מכיוון שבשדה
tcpTeacherComission 
שמממנו נלקח הערך בעבור המשנה teacherCommission
בטבלת 
AdminData
של המשתמש
natan
יש 0

**Comment by natan1957** [comment]
אבל יצירת קופון ע"י מנהל לא אמורה להתייחס לעמלת המנהל אלא לעמלת המורה שהוא בעל השיעור.
לפי החישוב בשורות 230 ו 240 באקסל

**Comment by natan1957** [comment]
זה עדיין לא תקין. ראה קופון מנהל
QLar5HAeW9
lesson = rRwbPUwZbV
teacher = elad
teacher commision = 0.2
lesson price = 100 nis
cpupon price = 50 nis
site fee = 50   teacher fee = 0
sould be:
site fee = 40 teacher fee = 10

**Comment by tom-hollander** [comment]
נכנסתי כמנהל, יצרתי קופון לשיעור rRwbPUwZbV והערכים הם  40 10 כפי שאתה מבקש אז או שבזמן שבדקת התיקון עדיין לא עלה או שאתה מבצע משהוא נוסף. אנא בדוק שוב ופרט את כל השלבים
