### ISSUE TITLE
חישוב שגוי במכתב רכישת חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#232]
event = 1mE1PZ3ZhH
![image](https://cloud.githubusercontent.com/assets/6491631/17077784/298198c0-50e6-11e6-8a5c-afb0606f495f.png)

**Comment by tom-hollander** [comment]
זה לפי האפיון:
•	siteFee <= מרשומת הקופון siteCouponFee מתורגם ממטבע הקופון למטבע האתר
•	siteFee => siteCouponFeeNISLetter מתורגם ממטבע האתר לשקלים
במכתב :
עמלת אתר בקופון –   siteCouponFeeLetter, couponCurrencySymbolLetter  , siteCouponFeeNISLetter,   siteCurrencySymbolLetter

ולכן כאשר מטבע האתר הוא שקלים ומטבע הקופון הוא לא , השדות siteCouponFee וsiteCouponFeeNis  יכילו את אותו הסכום ובגלל שאתה מבקש שבמכתב יופיע המטבע של הקופון אז נוצרת הבעיה

שיניתי כך שבמקום מטבע הקופון , יופיע מטבע האתר במכתב

**Comment by natan1957** [comment]
אבל הערך צריך להופיע במטבע הקופון ולא במטבע האתר
