### ISSUE TITLE
ממשק פייפל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#233]
למה ברכישת קופון מופיע ממשק פייפל אחד וברכישת קופה אחר ? לטעמי הראשון יותר נוח כי הוא מציג את רשימת הפריטים בלי לחפש ולפתוח אותה.
![image](https://cloud.githubusercontent.com/assets/6491631/17077828/14a71c2a-50e8-11e6-95e8-4d64e445c8e7.png)
![image](https://cloud.githubusercontent.com/assets/6491631/17077851/1b90fad2-50e9-11e6-810f-8c59cabb54ea.png)

**Comment by tom-hollander** [comment]
זה לא בשליטתי
