### ISSUE TITLE
יתרת מעמ יתרות התאפסה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#236]
user = maam2
פתחנו פה לשטן...
![image](https://cloud.githubusercontent.com/assets/6491631/17078101/d4efc546-50f1-11e6-9292-3303ecca2eab.png)

**Comment by tom-hollander** [comment]
הצלחתי לשחזר את זה כאשר מדובר בסל קניות עם מספר פריטים שיוצרים מספר רב של פעולות. לאחר התיקון הרצתי שוב את אותם הסלים ולא הצלחתי לשחזר את הבעיה.

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/17136875/6e9c8576-5340-11e6-81f2-bc1bd64e4a38.png)

**Comment by tom-hollander** [comment]
אתה יכול לשחזר את הפעולות שביצעת ?

**Comment by tom-hollander** [comment]
ראיתי בעיה נוספת בקוד, אמור להיות תקין כעת

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/17270919/9c596d38-5676-11e6-9e5d-10a95c24d3e3.png)

![image](https://cloud.githubusercontent.com/assets/6491631/17270929/cae2387e-5676-11e6-844e-1c1ccf1f0754.png)

**Comment by tom-hollander** [comment]
אני יודע , ראיתי את זה היום, למעשה היא התאפסה ב28 ורק ב30 התבצעה רכישה. נמשיך לעקוב אחרי זה

**Comment by natan1957** [comment]
מעמ1 התאפס ב 28 כתוצאה מרכישת קופון ב 28
מעמ2(יתרות) התאפס ב 30

**Comment by tom-hollander** [comment]
לא , כפי שאמרתי הוא התאפס ב28 , אני ביצעתי רכישה היום לאחר שבדקתי את הבלנס שלו שהיה 0

**Comment by natan1957** [comment]
![image](https://user-images.githubusercontent.com/6491631/28618999-2edcf74c-720f-11e7-8443-4936c38fc208.png)

**Comment by natan1957** [comment]
פותח בנושא חדש
