### ISSUE TITLE
רכישת שיעור עם קופון מנהל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#245]
הקמתי קופון מנהל עבור תה4444
coupon = wYX6JZgKuG
ביצעתי רכישה ע"י התחזות ל תה4444. עשיתי כך עשרות פעמים בעבר.
הרכישה הזתיימה בהצלחה אבל, הקופון לא עודכן וכך גם רשומת הרכישה. כך שהשיעור לא התווסף לתלמיד
כמו כן, יש טרנזקציית זיכוי סוכן אבל אין טרנזקציית חיוב האתר בגין פעולה זו.
event = 8o2aAwkElR
![image](https://cloud.githubusercontent.com/assets/6491631/17727618/513cbe40-6463-11e6-957a-ace98a8e1e3e.png)

**Comment by natan1957** [comment]
אותו הדבר קרה באירוע
event = XWDq674o4o
coupon = UZIo9HhtEu
הפעם עם תה5555 ללא התחזות אלא כניסה ישירה.

**Comment by natan1957** [comment]
לא תוקן.
coupon = ezo6BgvTrF
event = Z4gmsLo7HL
![image](https://cloud.githubusercontent.com/assets/6491631/17801894/945847ba-65f5-11e6-8e31-5a63b12a8e52.png)

**Comment by tom-hollander** [comment]
אני תיקנתי אנא פרט מה לא תקין

**Comment by natan1957** [comment]
כפי שניתן לראות באירוע שיצרתי היום, הקופון לא מוצג, רשומת הרכישה לא מוצגת. 
זאת אומרת שהקופון לא עודכן ולא שויך לאירוע וכך גם רשומת הרכישה.
בנוסף,  וגם טרנזקציית חיוב אתר בגין עמלת סוכן לא מוצגת.
בדיוק אותה התופעה שהייתה קודם.

**Comment by tom-hollander** [comment]
כנראה שהתיקון לא עבר, העברתי שוב ובדקתי כעת מופיע קופון ורשומת רכישה

**Comment by natan1957** [comment]
נבדק ונמצא תקין
