### ISSUE TITLE
מודיע ששיעור כבר נרכש

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#253]
למרות שלא נרכש
lesson = odgrlAID2Y
user = ta5555
pw = ta5555

**Comment by tom-hollander** [comment]
אנא ציין באיזה עמוד הוא ובאיזה שורה

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/19251701/4dcc16aa-8f49-11e6-98d0-e8200d3aefcb.png)
