### ISSUE TITLE
תהליך רכישה מודיע שלא הסתיים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#254]
הכנתי סל, צריך לבצע את הרכישה.
user = ta5555
pw = ta5555

**Comment by tom-hollander** [comment]
אני הצלחתי לבצע תשלום, בלוגים אני רואה שהיתה בעיה מול השרת של paypal
2016-10-10 08:48:19.4035 ERROR PayPal.HttpException: The remote server returned an error: (503) Server Unavailable.

**Comment by natan1957** [comment]
מה השורה התחתונה ?
גם אצלי הפעולה בוצעה, לא בטוח אם במלואה.
והופיעה הודעה שהתהליך לא הושלם.

**Comment by natan1957** [comment]
פעולת הרכישה בתשלום עדיין לא מסתיימת.
אחרי ביצוע תשלום, ואחרי שמסך ה פייפל נעלם, מופיע הקופה עם אותו פריט שהיה בקופה קודם.
נפתחה רשומת אירוע שנשארה בסטטוס סטארט
user = ta5555
pw = ta5555
event = A5bKfKp9UE
