### ISSUE TITLE
מורה לא מצליח לעדכן שיעור

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#270]
פתחתי מורה 
un= itzik19790@walla.co.il pw=  itzik1979
הקמתי שיעורים שלו. השיעורים מוקמים בסטטוס "בבדיקת מורה". זה טוב.
אבל כשאני מנסה לעדכן את סטטוס השיעור לפעיל, אני מקבל הודעה שהמורה לא נמצא.
מורים אחרים מצליחים .
לא יודע אם זה קשור, אבל השדה
fullNameForSearch
לא אוכלס אצל המורה החדש. זה גם לא מתאכלס בעדכון פרטים. זו תקלה בפני עצמה.
![image](https://cloud.githubusercontent.com/assets/6491631/22181781/de59f612-e09b-11e6-82a2-d4d5f724e262.png)

**Comment by natan1957** [comment]
פתחתי מורה בסביבת הטסט
un=mo6666 pw=mo6666
בעזרת המורה הזה הקמתי שיעור תות בראשית, בראשית הפטרה.
כשאני נכנס עם החשבון של המורה ומנסה לעדכן סטטוס שיעור מתקבלת ההודעה מורה לא קיים
גם כאן כמו בייצור השדה "שם מלא לחיפוש" לא אוכלס. אבל לא ברור לי אם יש קשר להודעה שהמורה לא נמצא.
![image](https://cloud.githubusercontent.com/assets/6491631/25358850/92484564-294b-11e7-8270-0769aef9a87a.png)

**Comment by igoro1975** [comment]
זה באמת קשור לשדה fullNameForSearch.
כדי להבין מה הבעיה אני צריך לדעת איך יוצרים מורה ולראות למה השדה לא מתמלא.

**Comment by natan1957** [comment]
ראשית אני מציע שתקים תלמיד.
בסוף טופס התלמיד יש צ'קבוקס "מעוניין להירשם כמורה.
אז נפתח טופס עם נתונים נוספים ובסופו יש לשלוח את הטופס.

כדי המורה יהיה פעיל, יש להיכנס כמנהל, להתחזות למורה ולהיכנס לטופס עדכון
פרטים.
בסוף הטופס יש אזור מנהל, שם יש להפוך את הסטטוס לפעיל יגם את  סטטוס העלאת
שיעור.

לאחר שתסיים, תיתן לי את המשתמש והסיסמה ואני אכין תחת החשבון שלו שיעור.

לאחר מכן נבדוק האם המורה יכול לעדכן (להפוך לסטטוס פעיל ) את השיעור.

**Comment by igoro1975** [comment]
מה הלוגיקה לשדה הזה? מה הנתונים שאמורים להיות בו?

**Comment by igoro1975** [comment]
נתן, האם אתה מצליח ליצור משתמש חדש? אני לא.

**Comment by natan1957** [comment]
לתוך השדה הזה משורשים שם פרטי ומשפחה של המורה בעברית ובאנגלית. 
הוא משמש לחיפוש שיעורים לפי שם מורה בשיעורים וחבילות. 
משום מה הוא לא מתאכלס, החשש שלי שיחד איתו לא מתאכלסים שדות נוספים שגורמים לכך שמורה לא מצליח לעדכן שיעורים שלו.

**Comment by natan1957** [comment]
אני הצלחתי ליצור משתמש ואחר כך להפוך אותו למורה. 
בסביבת הטסט. 
איפה נתקעת? אנחנו יכולים לעשות את זה יחד

**Comment by igoro1975** [comment]
תסתכל בבקשה לתהליך שאני עושה: https://drive.google.com/file/d/0B7X8_aC3kKj6WjlHcjh0amJZcDA/view

**Comment by natan1957** [comment]
אין לי מושג. זה לא צריך לקרות. שים לב שזה חוזר לערך ta5555.
אולי תרענן את הדפדפן עם ctrl f5.
אצלי זה לא קורה..

**Comment by igoro1975** [comment]
האם זה עובד עכשיו אצלך? אתה יכול לבדוק בבקשה?

**Comment by igoro1975** [comment]
הגרע הצלחתי לא כמורה וזה הצליח. מוזר מאוד.

**Comment by natan1957** [comment]
עכשיו תיכנס עם המשתמש של התלמיד לעדכון פרטי תלמיד, סמן את הצ'קבוקס מעוניין
להירשם כמורה ושלח עדכון.
יפתח טופס להשלמת פרטי מורה.

**Comment by natan1957** [comment]
אני רואה שפתחת 
ta9999
תשאיר אותו תלמיד לטסטים שלך
עבור מורה תקים משתמש שמתחיל ב 
mo
לדוגמה
mo9999

**Comment by igoro1975** [comment]
היתה בעיה עם אחלוס השדה. תיקנתי את זה.

**Comment by natan1957** [comment]
נפתרה הבעיה של עדכון שיעור ע"י מורה ?

**Comment by igoro1975** [comment]
רק אם אתה יוצר מורה חדש או קודם תעדכן את המורה וזה יסדר את הבעיה.

**Comment by natan1957** [comment]
אני מבין שבעדכון שיעור מתבצע חיפוש לפי שם והואיל והשם לא אוכלס הוצגה הודעה שהמורה לא קיים.
שאלה ראשונה: למה שם מורה לא אוכלס ? הרי זה כבר עבד.. מה גורם לזה פתאום להפסיק לעבוד?
שאלה שנייה: למה מתבצע חיפוש מורה בעדכון שיעור? למה החיפוש מתבצע לפי שם מורה ולא לפי מפתח מורה שקיים בשיעור?

**Comment by igoro1975** [comment]
1) שם מורה מלא לא מאוכלס כי זה עבד לפי לוגידה שעדיין עובד בייצור. בסביבת הטסט לפי דעתי (וגם אחרי התייעצות עם תום) זה לא עבד.
2) בעדכון שיעור מחפשים מורה לפי שם מלא. למה? זה כבר קיים ואין לי תשובה מה היתה החלטה מי שפיתח את זה. תמיד אפשר לתקן.
public Task<ParseUser> FindUserByName(string userFullName)
        {
            var query = ParseUser.Query.WhereContains("fullNameForSearch", userFullName.ToLower());
            return query.FirstOrDefaultAsync();
        }

**Comment by natan1957** [comment]
זה לא עבד ביצור. לא רק בטסט.
אם החיפוש לפי שם נועד לבדוק קיום או להביא נתון מסוים, במקרה של שני מורים עם אותו שם, עלול להתרחש בלגן.

**Comment by igoro1975** [comment]
אתה מציע לתקן את זה כדי שיחפש לפי מזהה?

**Comment by igoro1975** [comment]
עכשיו החיפוש לפי מזהה מורה.
