### ISSUE TITLE
לא מצליח להקים חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#273]
![image](https://cloud.githubusercontent.com/assets/6491631/23173342/8c458dc2-f861-11e6-92f5-33156325c1b0.png)

**Comment by natan1957** [comment]
הקמת חבילה מתבצעת ע"י מנהל.
נכנסים לשיעור, לוחצים על הקמת חבילה, מופיע טופס.
לוחצים על הוסף שיעור, ממלאים קטגוריות ומבצעים חיפוש. מתקבלת רשימה.
בוחרים שיעור או שניים ולוחצים הוסף שיעורים. השיעורים מתווספים לרשימה בחבילה.
ממלאים מחיר, אפשר לשנות שם אבל זה לא עקרוני.
לוחצים שמור.
פה מופיעה ההודעה.
זה מופיע רק בייצור. בטסט זה עובד תקין.

**Comment by igoro1975** [comment]
אולי זה תוקן אבל לא הועבר לייצור? 
אבקש אותך לבדוק את זה כאשר אעדכן את הייצור עם הקוד המעודכן.
אם עדיין יופיע אז אבדוק את ההבדלים בסביבות.

**Comment by natan1957** [comment]
זה לא עובד גם לאחר שהעברת לייצור.

**Comment by igoro1975** [comment]
רק לוודא עוד הפעם - בטסט זה כן עובד?

**Comment by igoro1975** [comment]
טיפלתי. הבעיה היתה בכמות הנתונים שעוברים ברשת בפורמט JSON.
