### ISSUE TITLE
עזרה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#278]
בשיעורים וחבילות, כאשר עומדים על שיעור, מופיע סימן שאלה וכאשר עומדים עליו מופיע חלון עזרה. בשיעורים שלי זה לא נמצא. 
יש להוסיף גם בשיעורים שלי ולאפשר לרשום תוכן עזרה לפעולות במסך.
![image](https://cloud.githubusercontent.com/assets/6491631/25080372/4eaf24f8-234c-11e7-9af6-2e9ae89b3e9d.png)

**Comment by igoro1975** [comment]
הוספתי שתי רשומות לטבלת סטרינגס:
PORTAL_MY_LESSON_FAQ
PORTAL_MY_BUNDLE_FAQ
התוכן שלהם רואים בשיעורים שלי. כרגע שמתי TBD.

**Comment by natan1957** [comment]
לא ברור לי מה תפקיד ההודעה של החבילה (בנדל..). בהצגת השיעורים שלי אין חבילות.
כל השאר בסדר

**Comment by igoro1975** [comment]
צודק, דיברנו שאין חבילות אבל אולי יהיה בעתיד. הוספתי כאפשרות.
