### ISSUE TITLE
הודעות אזהרה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#279]
הודעות האזהרה צריכות להשתמש באובייקטים קיימים המערכת ולא בברירת המחדל של הדפדפן
![image](https://cloud.githubusercontent.com/assets/6491631/25081081/d1b3f8d4-2350-11e7-987a-4fcd77ee6b14.png)

תוכן ההודעות צריך להילקח מטבלת הסטרינגים. פתחתי שלוש הודעות. יש להשתמש בעברית או אנגלית לפי שפת הממשק. הפניה לטבלה היא ע"י השדה קוד ולא דרך מפתח הרשומה.
![image](https://cloud.githubusercontent.com/assets/6491631/25080993/47693414-2350-11e7-814d-618b179e24e2.png)

**Comment by igoro1975** [comment]
איפה אני יכול לראות דוגמא של הודעת האזהרה הקיימת?

**Comment by natan1957** [comment]
אני לא בבית ולא ליד מחשב. אשלח לך ברגע שאוכל. 

נשלח מה-iPhone שלי

‫ב-18 באפר׳ 2017, בשעה 12:29, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
להלן שתי דוגמאות.
הטקסט צריך להגיע מטבלת הסטרינגים.
כפתורי הבחירה צריכים להיות "כן"  ו "לא"  בהתאם גם באנגלית

הודעה לאחר הוספת שיעור לסל
![image](https://cloud.githubusercontent.com/assets/6491631/25219260/79b02398-25b6-11e7-9e5e-0b8da112e3b8.png)

הודעה לאחר עדכון שיעור
![image](https://cloud.githubusercontent.com/assets/6491631/25219420/23271256-25b7-11e7-9dd7-0335fa6dbfa0.png)
