### ISSUE TITLE
הצגת דף אחרון מתעופף

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#282]
במשתמש   שלי
un= natan  pw= 123456
מופיעים 9 דפים. בניסיון להציג את דף 9 התהליך מתעופף.

![image](https://cloud.githubusercontent.com/assets/6491631/25225037/cd60db2e-25c8-11e7-9d30-c737021cfebc.png)

![image](https://cloud.githubusercontent.com/assets/6491631/25225068/ea3ba9fe-25c8-11e7-8560-c3e76575a9cf.png)

**Comment by igoro1975** [comment]
אני רואה שיש רכישה עם מזהה שיעור שלא נמצא כבר (uYE0rzg2WY). בגלל זה הדף מתעופף. איך זה קרה? האם זה מצב תקין?

**Comment by natan1957** [comment]
זה מצב לא תקין.
החלפתי את מפתח הקליפ בקליפ קיים וזה לא מתעופף.
השאלה היא האם יש איזה פתרון גנרי שבמקרה של אי קיום רשומה, יגרום להצגת איזה הודעת שגיאה ולא להתעופף.
המצב הלא תקין הזה יכול לקרות בכל מיני מצבים.

**Comment by igoro1975** [comment]
אפשרי לטפל בזה אבל זה לא קשור לשיעורים שלי אלא לכל המערכת.

**Comment by natan1957** [comment]
נכון. אמחוק את רשומת הרכישה. 
אני סוגר את התקלה.
