### ISSUE TITLE
 10.	מניעת רכישה עם תמיכה כאשר מחיר תמיכה = אפס

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#285]
![image](https://cloud.githubusercontent.com/assets/6491631/26531582/a8c5b77c-43f4-11e7-9a9e-9e2475d09b5d.png)

![image](https://cloud.githubusercontent.com/assets/6491631/26531608/f6df0c38-43f4-11e7-905a-a930ba011ee5.png)

**Comment by natan1957** [comment]
![image](https://user-images.githubusercontent.com/6491631/27500217-28fd5758-5870-11e7-8819-a8039c376914.png)

**Comment by igoro1975** [comment]
Fixed.
