### ISSUE TITLE
1.	הפנייה ל FaceBook

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#287]
![image](https://cloud.githubusercontent.com/assets/6491631/26541619/0e9e95f4-445f-11e7-908b-53065a2dd53a.png)

**Comment by natan1957** [comment]
יש לפתוח את האתר בלשונית חדשה

**Comment by natan1957** [comment]
האם שוחררה הגרסה לטסט ?
כרגע זה עדיין לא תקין.

**Comment by igoro1975** [comment]
לא הוספתי "טופל + גרסה" - עוד לט העברתי לטסט. אולי מאוחר יותר היום...

**Comment by natan1957** [comment]
מה עם זה ?

**Comment by igoro1975** [comment]
העליתי לטסט

**Comment by natan1957** [comment]
נבדק. ניתן להעביר לייצור

**Comment by natan1957** [comment]
בייצור, אכלסתי את השדות של כתובות פייסבוק וזה לא מופיע בתפריט האתר

**Comment by igoro1975** [comment]
בטסט שם השדה
facebook_he_il_address
ובייצור
facebookAddress_he_il
לכן הוא לא מוצא בייצור

**Comment by igoro1975** [comment]
איך משנים שם השדה ב-PARSE?

**Comment by natan1957** [comment]
לא ניתן.
יש להקים שדה חדש ולמחוק את הישן

**Comment by igoro1975** [comment]
Fixed.

**Comment by natan1957** [comment]
נבדק ונסגר
