### ISSUE TITLE
2.	מדריכים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#288]
![image](https://cloud.githubusercontent.com/assets/6491631/26541656/3abad936-445f-11e7-88ab-dea17e824def.png)

**Comment by natan1957** [comment]
אין הבחנה בין מצב תלמיד למצב מורה.
בשני המצבים מציג את האיי פריים של התלמיד
ההבחנה בין עברית לאנגלית תקינה

**Comment by igoro1975** [comment]
האם ב-databaseמהקוד שונה? יש מצב שאני הזנתי את אותו קוד כי אין לי קוד לשני המקרים.

**Comment by natan1957** [comment]
אני לא מבין מה אין.
האם אין הבחנה בין תלמיד/אורח ל מורה/מנהל?
האם אתה לא יודע להבחין מה סוג המשתמש?

בטבלת העולמות יש ארבעה שדות שונים שמהם יש לקחת את הקוד של ה איי-פריים.
זה מפורט במסמך וגם כאן בראש ההתכתבות

**Comment by igoro1975** [comment]
התכוונתי שאין לי שני סוגי הקוד לאיי פריים. הפיתוח גמור, צריך רק שני סוגים
של הקוד. היה לי אחד ושמתי אותו גם למורה וגם לתלמיד. אם עדיין הסברתי את עצמי
לא ברור, מציע שנדבר.

12 июня 2017 г. 16:21 пользователь "natan1957" <notifications@github.com>
написал:

**Comment by natan1957** [comment]
אני הכנסתי את קוד האי-פריים ל 4 שדות ברשומת עולם התורה בטבלת העולמות
איזה קוד חסר לך ?
![image](https://user-images.githubusercontent.com/6491631/27041043-7e1c242c-4f9b-11e7-8757-0b008a2718ec.png)

**Comment by igoro1975** [comment]
עם איזה מורה אתה מנסה לבדוק את זה בטסט?

**Comment by igoro1975** [comment]
אני רואה שיש התיחסות בפיתוח וגם בנתונים למורים וגם לתלמידים. 
אני רוצה לדבג - עם איזה מורה אתה בודק בטסט?

**Comment by natan1957** [comment]
אתה יכול לנסות עם 
mo4444
תמחק את התוכן משדות המורה (אנגלית ועברית) ותראה אם יש הבדל. 
אל תמחק לגמרה, תעתיק לוורד כדי שתוכל להחזיר. 
המצב מורה או אדמין זה צריך להראות מסך ריק ללא מצגת. 
לחלופין אתה יכול למחוק את שדות הסטודנט ולראות האם זה ישפיע רק על סטודנט/אורח או גם על מורה/אדמין. 
אל תשכח לבצע מחיקת קש אחרי שאתה עושה שינוי בטבלת עולמות. 

נשלח מה-iPhone שלי

‫ב-13 ביוני 2017, בשעה 16:45, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
היי איגור.
חשבתי על פתרון שיהיה יותר פשוט למימוש ויותר נוח למשתמש.
להוסיף איי-פריים מתחת לזה הקיים במדריכים שיהיה מיועד למורה/אדמין.
לאיי-פריים הקיים תעביר את הקוד של התלמיד/אורח. לאיי-פריים החדש, תעביר את הקוד של מורה/אדמין.
אם המשתמש אייננו מורה/אדמין (זאת אומרת שהוא תלמיד/אורח) אין להציג את האיי-פריים השני.

נתן.

**Comment by igoro1975** [comment]
תשים לב, שעכשיו צריך לשים רק את הקישור בנתונים כדי לשמור על אחידות התצוגה.
לדוגמה
https://onedrive.live.com/embed?.................
