### ISSUE TITLE
6.	בחירת עולמות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#291]
![image](https://cloud.githubusercontent.com/assets/6491631/26541751/b28f9690-445f-11e7-94d3-887285184aab.png)

**Comment by natan1957** [comment]
אם אני סוגר את המערכת ומפעיל מחדש, אני לא מקבל את מסך בחירת העולמות.
רק אם אני סוגר את כל הדפדפן אני מקבל שוב את מסך הבחירה.
המסך צריך להופיע בכל הפעלה גם אם לא סגרתי את הדפדפן.

**Comment by igoro1975** [comment]
לא לגמרי נכון. 
החיים של העוגיות הם 20 דקות (SESSION). לכן כאשר אתה סוגר את הלשונית ולא עברו 20 דקות המערכת "חושבת" שאתה עדיין עובד, אפילו אם נכנסת בלשונית חדשה. 
אם זה לא מתאים (20 דקות) תגיד איך אתה רואה את הפתרון? על מה להתבסס כדי לזהות שהמערכת אמורה למחוק את העוגיות.

**Comment by igoro1975** [comment]
https://stackoverflow.com/questions/1921941/close-kill-the-session-when-the-browser-or-tab-is-closed

**Comment by igoro1975** [comment]
דפדפן זה client.
אתה לא יכול לנהל את השרת מ-client.

**Comment by natan1957** [comment]
היי איגור, ראשית הערה טכנית:
Github
ממש לא תומך טוב בעברית. לכן אם יש לך משפט עם מילים באנגלית, כמו סשן לדוגמא, אז או שתכתוב אותן בעברית, או בשורה נפרדת. עמו שכתבתי גיטהב קודם.
אחרת הכול מתבלגן.

אז אני מבין שזה לא עניין של עוגייה (שיודעת לחיות זמו רב) אלא של סשן שממשיך לחיות 20 דקות..
מניסיונות פשוטים שערכתי, אם אני סוגר את על הלשוניות, זאת אומרת את כל הדפדפן, ומפעיל שוב את המערכת, טופס הבחירה כן נפתח, למרות שחולפות 20 שניות ולא 20 דקות.

מצד שני, למיטב ידיעתי, בכל זאת קיימת עוגייה שנשמרת זמן רב ושומרת את עולם התוכן של משתמש שעשה לוג אין ובחר את אותו העולם.
מצד שני, אם המשתמש טרם ביצע לוג אין במחשב, והיה רק אורח, לא נרשמה עוגייה, למרות שבחר עולם עדי לעיין בו.
כאשר המערכת מופעלת, היא צריכה לחפש את העוגיה ולפעול בהתאם. אם יש, להפעיל את העולם הרלוונטי שרשום בה. אם אין, להציג את הטופס.
 מה שאתה אומר זה, שבתוך 20 דקות מהסגירה הקודמת, אם אני מפעיל את המערכת, היא למעשה לא "עולה" אלא נפתחת ממצבה הקודם ולא "מסתכלת" על העוגייה.
האם התאור הזה נכון?

**Comment by igoro1975** [comment]
כרגע אנחנו מגדירים את העוגיות ב
javascript
לכן אין אפשרות מהירה להעביר את זה לצד שרת.

**Comment by natan1957** [comment]
אני מבין שלא ניתן

**Comment by natan1957** [comment]
בנוגע לשלושת העולמות המופיעים בטופס, לא ברורה לי הלוגיקה..
העולמות אמורים להגיע מטבלת העולמות
אבל שיניתי את אחד השמות ולא ראיתי שזה משתנה
שיניתי סטטוס של אחד העולמות ולא ראיתי שהוא יורד מהטופס
הוספתי עולם והוא לא התווסף לטופס
האם זה בגלל שלא ריעננתי את הזיכרון, או שזה משהו אחר.

**Comment by igoro1975** [comment]
זה בגלל ה-
caching
צריך למחוק אותו או לחכות עד שהוא לא יהיה תקף.

**Comment by natan1957** [comment]
הוספתי עולם רביעי. הוא עדיין לא פעיל כי לא אכלסתי פרטים חשובים, אבל עשיתי את זה רק כדי לבדוק את טופס בחירת העולמות.
![image](https://user-images.githubusercontent.com/6491631/27587467-2e398220-5b4d-11e7-9b14-09678dd4020e.png)
מתוך התוצאה, אני מבין שהאייקונים המופיעים לשלוש העולמות הראשונים צרובים בתוכנה.. האם זה נכון?
אם כן, איפה הם נמצאים?
אני מניח שיהיה צורך להוציא אותם לטבלת העולמות וזה קשור למשימה7, נושא 292
