### ISSUE TITLE
7.	קישורים בדף הבית.

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#292]
![image](https://cloud.githubusercontent.com/assets/6491631/26541797/f00b203e-445f-11e7-89d0-08f0aa7330d3.png)

**Comment by natan1957** [comment]
פתאום אני רואה שיש אייקונים לעולמות אחרים.. זה מוצג בטופס בחירת עולמות.. מאיפה זה נלקח ? מה יקרה אם יהיה עולם רביעי וחמישי?
בכל מקרה ניתן לקחת את האייקונים האלה לטבלת העולמות לשם הצגתם בכותרת שיעורים וחבילות .
![image](https://user-images.githubusercontent.com/6491631/27334597-79c926bc-55d2-11e7-833b-b552698d4584.png)

**Comment by igoro1975** [comment]
את החלון לבחירת העולמות היה קיים ואני לא בדקתי מאיפה נלקחים התמונות. אבדוק.

2017-06-20 16:07 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
הוספתי עולם רביעי. הוא עדיין לא פעיל כי לא אכלסתי פרטים חשובים, אבל עשיתי את זה רק כדי לבדוק את טופס בחירת העולמות.
![image](https://user-images.githubusercontent.com/6491631/27587467-2e398220-5b4d-11e7-9b14-09678dd4020e.png)
מתוך התוצאה, אני מבין שהאייקונים המופיעים לשלוש העולמות הראשונים צרובים בתוכנה.. האם זה נכון?
אם כן, איפה הם נמצאים?
אני מניח שיהיה צורך להוציא אותם לטבלת העולמות

**Comment by igoro1975** [comment]
iconFileName 
בטבלת העולמות

**Comment by igoro1975** [comment]
מה עוד צריך לעשות בנושא הזה?

**Comment by natan1957** [comment]
אני רואה שהאייקון לא נמצא בטבלת העולמות אלא סטרינג עם השם שלו.
אני מניח שהאייקון עצמו נמצא באתר הפורטל.
יש לשנות ולהוציא את האייקון שישב פיזית בטבלת העולמות. בשדה מסוג קובץ.
בהתאם לעולם, יש להחליף באופן דינמי את האייקון המוצג במקומות הבאים:
![image](https://user-images.githubusercontent.com/6491631/27826816-3bf726d6-60bd-11e7-8b60-39d94935055d.png)
![image](https://user-images.githubusercontent.com/6491631/27826834-5120587a-60bd-11e7-88c6-1853022ca394.png)
גם הטקסטים "טקסט על העמוד" לא ברור מאיפה מגיעים. בשלב זה ניתן להוריד. גם בעברית וגם באנגלית.
![image](https://user-images.githubusercontent.com/6491631/27827577-9a6053ca-60c0-11e7-9872-a9cc43c24aad.png)

**Comment by igoro1975** [comment]
גם לכל ריבוע כזה ליצור שדה קובץ ב
database?

![iii](https://user-images.githubusercontent.com/4538009/28026800-ce18667e-659f-11e7-8a2d-45a04d5e18ab.png)

**Comment by natan1957** [comment]
רק לריבוע שיעורים וחבילות. הריבועים האחרים לא משתנים בעולמות תוכן אחרים. 
לא בטוח שכול הריבוע. צריך להחליף רק את האייקון של עולם התוכן שזה ספר התורה שבתוך הריבוע.

**Comment by igoro1975** [comment]
I added a new field: lessonsIconFile. The field can not be empty!

**Comment by natan1957** [comment]
לא ברור מה הסטטוס.
הקבצים שהוספת מכילים תמונה של המצביע של התורה...

**Comment by igoro1975** [comment]
הוספתי אותו קובץ כי השדה לא יכול להיות ריק. אתה יכול לעדכן את השדה למה שאתה רוצה אבל הפיתוח סיימתי. האם יש עוד משהו שאני אמור לעשות במשימה הזו?

**Comment by natan1957** [comment]
שלח לי את קבצי התמונה של קריאה ושל אנגלית עבור השדה 
lessonIconFile

האייקון צריך להשתנות גם בכותרת רשימת השיעורים
![image](https://user-images.githubusercontent.com/6491631/28245195-dd954676-6a09-11e7-8d16-143fb7cae7f0.png)

**Comment by natan1957** [comment]
האייקון של ספר התורה מופיע במערכת שלוש פעמים. בכל מקום בגודל אחר. המשימה היא להפוך אותו לדינאמי כך שיגיע מטבלת העולמות. בשלושת המקומות הוא מופיע בגדלים שונים. לכן בטבלת העולמות בכל שורה צריכים להיות שלושה שדות, עם אותו האייקון אבל בגדלים שונים שיתאימו למקומות במערכת. שניי שדות מימשת ואת השלישי עדיין לא. האם אייקון התורה קיים בספריות המערכת שלוש פעמים? אם כן שלח לי. לגביי האייקונים של הספר וה-AB, האם גם הם נמצאים במערכת בשלושה גדלים? אם כן שלח לי.
![image](https://user-images.githubusercontent.com/6491631/28404188-fcd6add4-6d30-11e7-9d80-d44db19eec4d.png)

**Comment by igoro1975** [comment]
אשמח לדבר על זה מחר בערב. יש כאן משהו שאני לא מבין.

**Comment by igoro1975** [comment]
סידרתי שבדף השעיורים מוצג אותו אייקון בשדה 
lessonsIconUrl
הבעיה שהאייקונים האלו לכל עולם בגודל קצת שונה ולכן זה טיפה משפיע על התצוגה (תסתכל בטסט).
נראה לי כדאי לעדכן את הקבצים.
מה אתה חושב?

**Comment by igoro1975** [comment]
אחרי שנחליט מה עושים (אני חושב להישאר עם הפתרון הזה) אעדכן גם אייקון בשיעורים שלי.

**Comment by natan1957** [comment]
בגלל שהגדלים שונים חשבתי על שלושה שדות שיכילו את האייקון בשלושת הגדלים.
אתה אמרת שמספיק שדה אחד ושאתה תשנה את הגדלים בזמן הטעינה (כך הבנתי..). 
אם זה לא עובד, אז אפשר שלושה שדות נפרדים. 

נשלח מה-iPhone שלי

‫ב-28 ביולי 2017, בשעה 8:11, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by igoro1975** [comment]
אני לא מתכוון גדלים של האייקונים של אותו עולם אלא אותו אייקון של העולמות
שונים. האם הצלחתי להסביר את עצמי?

28 июля 2017 г. 10:27 пользователь "natan1957" <notifications@github.com>
написал:

**Comment by natan1957** [comment]
הבנתי. אני אטפל בגדלים. 
למה קובץ האייקון נמצא בשדה בשם URL? זה עלול לבלבל.. היה יותר הגיוני משהו כמו worldIconFile...

נשלח מה-iPhone שלי

‫ב-28 ביולי 2017, בשעה 10:40, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
רק תגיד לי האם יש שלושה קבצים לכל עולם או אחד?

נשלח מה-iPhone שלי

‫ב-28 ביולי 2017, בשעה 10:40, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
נבדק בייצור
