### ISSUE TITLE
8.	צור קשר

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#293]
![image](https://cloud.githubusercontent.com/assets/6491631/26541837/16304fd2-4460-11e7-8e6c-7df00524d174.png)

**Comment by igoro1975** [comment]
PORTAL_CONTACT_SENT added to Strings table on test environment. 
TODO: on production

**Comment by igoro1975** [comment]
TODO: contactEmail to add to production

**Comment by natan1957** [comment]
![image](https://user-images.githubusercontent.com/6491631/27013523-5e2d88a2-4eee-11e7-9a89-3f45b6c1fb1e.png)

**Comment by natan1957** [comment]
ההודעה חזרה לפורטל לא מחזירה לפורטל אלא לטופס השליחה.
היא צריכה להחזיר לפורטל ולנקות את הטופס.
משתמש רשום שהשם והדוא"ל מתמלאים אוטומטית, לא יוכל לשנות את השדות האלה.
צריכה להינתן איזו אינדיקציה במייל האם זה ששלח הוא משתמש רשום או אורח.
אני מציע פשוט להוסיף 
Registrated User      Visitor
בהתאם למצב.
יש לשרשר את הנושא ואת הדוא"ל של הפונה ולהכניס לנושא של המייל

**Comment by igoro1975** [comment]
תיקנתי הכל חוץ מהבעיה של הסביבות.

**Comment by natan1957** [comment]
רק למחוק את המילה ויזיטור
![image](https://user-images.githubusercontent.com/6491631/27254445-bd980b5e-5390-11e7-946d-f61323148847.png)

**Comment by igoro1975** [comment]
למה פתחת את הבאג מחדש?

**Comment by igoro1975** [comment]
למה פתחת את הבאג מחדש?

**Comment by natan1957** [comment]
בשביל שתסמן "הועבר לייצור".
