### ISSUE TITLE
9.	הודעת המתן.

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#294]
![image](https://cloud.githubusercontent.com/assets/6491631/26541907/5fb5edc4-4460-11e7-9bc8-8f9a378195f0.png)

**Comment by natan1957** [comment]
שים לב שתשלום בפועל מתבצע תוך מעבר למסך של פייפל

**Comment by natan1957** [comment]
האם טיפלת גם ברכישת קופון?
שמתי לב שבסיום תהליך הרכישה, במקום לחזור לרשימת השיעורים שהוצגה קודם, מופיעה רשימה ריקה.
![image](https://user-images.githubusercontent.com/6491631/28086909-4a6ea082-6689-11e7-9dd7-46b0f20dbafe.png)

**Comment by igoro1975** [comment]
1. ברכישת קופון לא טיפלתי. אתה מתכוון להוסיף קופון כאדמין למשתמש וכאשר המשתמש רוצה להשתמש בקופון, לתת את ההודעה?
2. הקישור לא שיניתי, כמה שזכור לי תמיד היה נשאר בדף הזה. לאן צריך להפנות את המשתמש אחרי הרכישה?

**Comment by natan1957** [comment]
ברכישת קופון, כשלרוכש יש יתרה בחשבון הוא לא מגיע לתשלום בפייפל אלא מאשר שהסכום יירד מהיתרה.
במקרה כזה, בסיום הפעולה אפשר לראות שברקע נשארת התצוגה של השיעור שממנו ביצע את רכישת הקופון.
אותו דבר צריך להיות גם כשיש רכישה עם פייפל. אבל מוצגת רשימה ריקה כפי שניתן לראות בתמונה הקודמת.
![image](https://user-images.githubusercontent.com/6491631/28121695-9412f9b8-6724-11e7-8e6b-c1f0156754e9.png)

**Comment by igoro1975** [comment]
זה אמור להיות סגור?

**Comment by natan1957** [comment]
נבדק. ניתן להעביר לייצור

**Comment by natan1957** [comment]
עניין הצגת רשימת שיעורים אחרי תשלום רכישת קופון לא טופל
