### ISSUE TITLE
לא מצליח להיכנס לעדכון פרטי המשתמש

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#295]
בלחיצה על שם המשתמש - מתעופף
![image](https://user-images.githubusercontent.com/6491631/27028877-dfb59614-4f6e-11e7-93eb-17cbb0b76e90.png)

**Comment by igoro1975** [comment]
זה קשור לאותה בעיה של "ייצור - טסט" בלאגן, אני קודם כל מטפל בזה.
