### ISSUE TITLE
שליחת מכתבים לפי שפה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#299]
![image](https://user-images.githubusercontent.com/6491631/28995565-2da93d16-79f5-11e7-8f85-4f27977889d5.png)

**Comment by igoro1975** [comment]
נדרש הסבר נוסף. היום נשלחים המיילים לפי העוגיות של המשתמש באתר. 

אתה כותב "משתמשים" - אנא הוסיף הסבר נוסף אילו שינויים אתה רוצה? 

אני רואה שנשלחים מיילים לאדמין, למורה וגם לסטודנט. האם לכל אחד לשלוח בפשה שלו? זו הכוונה? תפרט בבקשה את המשימה. 

תודה.

**Comment by natan1957** [comment]
כן. 
העברתי לתום נוסחי מכתבים בעברית ובאנגלית. 
כאשר שולחים מכתב למשתמש, יש לבדוק מה השפה המועדפת שלו, זה נמצא ברשומת המשתמש. לפי זה יש לבחור את השפה של המכתב ולאכלס אותו בערכים ולשלוח. 

נשלח מה-iPhone שלי

‫ב-11 באוג׳ 2017, בשעה 21:29, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by igoro1975** [comment]
כלומר, האדמין מקבל בשפה שלו, המורה בשלו, והמשתמש (סטודנט) בשלו. נכון?

**Comment by natan1957** [comment]
נכון. 

נשלח מה-iPhone שלי

‫ב-11 באוג׳ 2017, בשעה 21:40, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by igoro1975** [comment]
הבנתי. תודה.

**Comment by igoro1975** [comment]
כאשר אני מחפש שפת אדמין במערכת, איך אני יודע מי האדמין כי יכול להיות שיש כמה אדמינים בקבוצת אדמינים. אולי לשלוח לאדמין תמיד באנגלית וזהו?

**Comment by natan1957** [comment]
כרגע יש שני מקומות בהם נמצאות כתובות:
האחד הוא סייט-אקאונט ברשומה של טבלה קומישנס.
זה מפתח של משתמש בשם סייט ולמשתמש הזה יש כתובת ושפת ממשק ברשומת המשתמש.
המקום השני זה בהדגרות הפרס, גם הוגדרה כתובת האדמין.
![image](https://user-images.githubusercontent.com/6491631/29243993-dba3d370-7fb5-11e7-804a-69d1b60af000.png)
זה לא טוב, כי אני רוצה הפרדה בין המכתבים שנשלחים לאדמין מהעולמות השונים.
לכן הוספתי לטבלת העולמות (בטסט) שדה אדמין-אימייל שקובע לאן לשלוח את ההודעה ו אדמין-לנגואיץ' שקובע באיזה שפה יש לשלוח לו את ההודעה.
בהמשך ייתכן וארצה כתובות נוספות אבל כרגע זה מספיק.
כל מכתב ששולחים למשתמש (בשפת המשתמש), יש לשלוח בעותק נסתר לאדמין העולם.
כל מכתב ששולחים לאדמין, יש לשלוח בשפת האדמין שנמצאת ברשומת העולם
לא לשנות כלום בטבלת קומישנס ובהגדרות הגלובליות.

**Comment by igoro1975** [comment]
תודה, אני ממשיך...

**Comment by natan1957** [comment]
אני רוצה לבדוק את זה.
לפני כן, אני רוצה לעשות סדר בכתובות המיילים כי גם אני התבלבלתי.
אני רוצה לוודא שכל המכתבים שנשלחים במערכת, נשלחים עם עותק סמוי לכתובת שבשדה 
AllLettersInbox.
זה שונה ממה שכתבתי קודם...
כמובן שכאשר מדובר בעותק, אז זה יהיה בשפה המקורית של היעד הראשי .
מכתבים שנשלחים לאדמין יישלחו לכתובת שבשדה 
adminEmail
עם השפה שבשדה
adminLanguage

יש לבדוק את כל המכתבים שיוצאים מהמערכת. אני זוכר את המכתבים הבאים:
מכתב למצטרף דרך האפליקציה
**ברכישת קופון:**
מכתב לתלמיד שנרכש עבורו קופון. מכתב זה נשלח עם עותק גם למורה.
מכתב לסוכן על רכישת הקופון, במידה והסוכן קיים
**ברכישת שיעור:**
מכתב לרוכש
מכתב למורה
מכתב לסוכן אם קיים סוכן. סוכן הוא זה שגייס את המורה ומקבל עמלות מהעיסקאות. אם יש סוכן, המפתח שלו נמצא ברשומת המורה, .
מכתב לתלמיד. אם התלמיד הוא הרוכש, אני מניח שיוצא רק מכתב לתלמיד

כמו כן יש לבדוק מכתבים שונים שנשלחים לאדמין.

**Comment by natan1957** [comment]
תודיע לי אחרי ביצוע.

**Comment by igoro1975** [comment]
מה זה השדה AllLettersInbox? איפה זה נמצא?

**Comment by igoro1975** [comment]
היום נשלח עותק למייל
site.admin@mymentorapp.com
שמוגדר ב
parse settings

**Comment by natan1957** [comment]
השדה נמצא בטבלת העולמות. הוספתי בטסט שדה בשם
allLettersOutbox
במקום 
AllLettersInbox
לכתובת שבשדה זה יש לשלוח עותק מוסתר של כל המיילים היוצאים.
זה אמור להיות רגיש לעולם בו מתרחשת השליחה.

**Comment by igoro1975** [comment]
היי נתן,
כרגע העליתי שינוי כדי שיישלחו מיילים גם למייל allLettersOutbox לפי העולם.

**Comment by natan1957** [comment]
מה שרואים פה זה שני מכתבים מרכישת שני שיעורים של מורים שונים. מורה אחד אנגלית ומורה שני עברית.
העברית תקין אבל באנגלית שובצו תכנים בעברית.
![image](https://user-images.githubusercontent.com/6491631/30951883-f0c9b0fc-a42d-11e7-910b-cb4c15539c9b.png)
ברכישה אחרת רואים מצב הפוך בו המכתב האנגלי תקין והעברי לא.
ייתכן וזה נובע מסדר הפוך של ההכנה והשליחה.
יש לוודא שלכל שפת מכתב, משבצים את התכנים בשפה המתאימה.
![image](https://user-images.githubusercontent.com/6491631/30951972-5a9e517c-a42e-11e7-872f-9990491ca981.png)

**Comment by natan1957** [comment]
מכתב לסוכן
![image](https://user-images.githubusercontent.com/6491631/30952064-cf1db15a-a42e-11e7-9ec7-00af3ac20847.png)

**Comment by igoro1975** [comment]
היי נתן,

1. אני טיפלתי בזה שלכל מקבל מיילים נבחרת שפה מתאימה - במערכת זה מוגדר על
ידי תבניות. אני רואה שהתבניות נשלחות תקין. זה טוב.

2. הדבר השני שבתבניות אנחנו מוסיפים תכנים (שמות וכו) וזה כרגע לא תקין בחלק
המקרים. זה כבר לא תלוי בתבניות ומוגדר בקוד במקום אחר. לכן אני צריך לבדוק
למה זה קורה ומה משפיע לבחירה הזו חוץ משפת המשתמש (כי השפה נבחרת תקין כנראה
יש עוד משהו נוסף). בודק.

האם אני הבנתי נכון? התבניות נשלחות תקין. נשאר לתקן את התוכן בתבניות.

איגור

2017-09-28 9:22 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by igoro1975** [comment]
אני כן צריך משתמש לרכישות כדי לשחזר את המצב ולמצוא בעיה.

28 сент. 2017 г. 11:24 AM пользователь "natan1957" <notifications@github.com>
написал:

**Comment by natan1957** [comment]
לידיעתך, אפשר לראות שביצירת המכתב מתבצעת הכנת הטקסטים לשני השפות.
אפשר לראות את זה בשדה 
letterData
בטבלת המכתבים.
לדוגמה המכתב הזה
![image](https://user-images.githubusercontent.com/6491631/31081558-ea509b5e-a794-11e7-9c74-74887311de3e.png)

שכולל תוכן עברי במקום אנגלי, יש לו רשומה בטבלת מכתבים עם התוכן העברי וגם האנגלי שסימנתי באדום
![image](https://user-images.githubusercontent.com/6491631/31081731-709dace2-a795-11e7-94f8-8e9e79064129.png)
לצערי נפלה שגיאה נוספת, במכתב, במקום מפתח המכתב מוצג מפתח הפריט. סימנתי בשחור. יש לסדר את זה.
זה לא קורה בכל המכתבים. שמתי לזה לב במכתב הזה..

**Comment by natan1957** [comment]
מכתב לסוכן באנגלית
![image](https://user-images.githubusercontent.com/6491631/31081949-2625dbac-a796-11e7-869a-6e40da553751.png)

**Comment by natan1957** [comment]
עדיין מכתבים נשלחים לייעדים לא נכונים.
כל המכתבים יישלחו עם העתק נסתר ל
allLettersOutbox
זה קורה וזה בסדר.

יש להפסיק לשלוח מכתבים למשתמש שבשדה 
siteAccount - Commisions.
יש לקחת שפת אדמין מהרשומה בטבלת עולמות ולפי שפה זו להפיק את המכתבים  ולשלוח לכתובת האדמין שברשומת עולם
![image](https://user-images.githubusercontent.com/6491631/31407953-7d7a4b34-ae0f-11e7-8f98-321b29f30a1a.png)
![image](https://user-images.githubusercontent.com/6491631/31407991-a20b9fca-ae0f-11e7-9430-fc5e80843684.png)

מכתב לרוכש נשלח בעברית בלבד. יש לשלוח באנגלית כששפת הרוכש אנגלית.
![image](https://user-images.githubusercontent.com/6491631/31408380-fb8db942-ae10-11e7-9af5-0b336b8acbd1.png)

אם זה בעברית, אז כל השדות צריכים להיות בעברית
![image](https://user-images.githubusercontent.com/6491631/31408566-b5531674-ae11-11e7-842b-2ead7d447d2a.png)

לא ברור אם זה מכתב בעברית או אנגלית. הכותרת באנגלית, התבנית בעברית, שמות משתמש באנגלית
![image](https://user-images.githubusercontent.com/6491631/31408698-200a0b94-ae12-11e7-8323-713e75a4ebc3.png)

**Comment by natan1957** [comment]
מכתב שמופק בעת רכישת קופון נשלח לתלמיד עבורו הופק הקופון והעתק למורה שרכש עבורו את הקופון.
זה מכתב אחד לשני נמענים.
שפת המכתב צריכה להיות לפי השפה של זה שעבורו נרכש הקופון ולא לפי השפה של זה שרכש את הקופון.
כרגע זה ההפך.
![image](https://user-images.githubusercontent.com/6491631/31433292-8b3477fa-ae81-11e7-83de-33979626420f.png)

**Comment by natan1957** [comment]
לא.
בתאריך יום ו׳, 13 באוק׳ 2017 ב-15:43 מאת Igor <notifications@github.com>:

**Comment by igoro1975** [comment]
תיקנתי מה שהוספת.

**Comment by natan1957** [comment]
כל המכתבים בתהליך הרכישה נשלחים בשפה הנכונה לפי שפת המקבל.
מכתבים הפסיקו להישלח עם העתק נסתר לכתובת שבשדה 
allLettersOutbox
הם צריכים להישלח בהעתק נסתר רק לכתובת שנמצאת בשדה זה. ולא לכתובת של היוזר
site.

המכתב סיכום אירוע צריך להישלח לכתובת האדמין שברשומת העולם והעתק נסתר לאאוט -בוקס.
המכתב רכישת שיעור צריך להישלח ל אאוט-בוקס לא נסתר.

להלן שדות המופיעים לא באופן נכון או בשפה לא נכונה או צריכים שינויים קלים

![image](https://user-images.githubusercontent.com/6491631/31589262-6a9fc880-b207-11e7-9f89-ff8a879dfc56.png)

![image](https://user-images.githubusercontent.com/6491631/31589295-fd9a002e-b207-11e7-89fe-78e4dbd8618e.png)

![image](https://user-images.githubusercontent.com/6491631/31589319-57beae88-b208-11e7-8fe7-d087780a5f03.png)


![image](https://user-images.githubusercontent.com/6491631/31589534-0a0bd932-b20c-11e7-9eae-6f2e2ffee94c.png)

![image](https://user-images.githubusercontent.com/6491631/31589431-fcfaa554-b209-11e7-86ae-1f00d464e85b.png)

![image](https://user-images.githubusercontent.com/6491631/31589465-9c66ce7e-b20a-11e7-9d0e-a72b14e8eb26.png)

**Comment by igoro1975** [comment]
הבנתי אותך. אבדוק הכל ואתקן.

2017-10-16 0:51 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by igoro1975** [comment]
היום תיקנתי את כל הדברים הקטנים תבניות.

2017-10-16 0:51 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
כל המכתבים שנשלחים בתהליך הרכישה **למשתמשים** יישלחו למשתמשים בשפת המשתמש עם עותק נסתר ל
allLettersOutbox.

מכתב רכישת שיעור יישלח בשפת האדמין שברשומת העולם ישירות ל
allLettersOutbox.

מכתב סיכום אירוע יישלח בשפת האדמין לכתובת 
adminEmail
עם עותר נסתר ל
allLettersOutbox

מכתב רכישת קופון נשלח לזה שעבורו נרכש הקופון ובשפתו, עותק גלוי לרוכש, עותק נסתר ל
allLettersOutbox.

מכתבים מצור קשר ומכתבי התראה על תקלות (כמו זה שנשלח כשלא נמצא סוכן) נשלחים בשפת האדמין לכתובת 
adminEmail
עם עותק נסתר ל
allLettersOutbox

יש עוד משהו ששכחתי ?

**Comment by igoro1975** [comment]
עדכנתי את סביבת הטסטים.

**Comment by natan1957** [comment]
מכתב למורה, לשלוח למורה ונסתר ל אול-לטרס בלבד. לבטל את העותק שנשלח לסייט.
![image](https://user-images.githubusercontent.com/6491631/32137454-f9c8ee3a-bc28-11e7-8df1-d8d423c69587.png)

**Comment by natan1957** [comment]
מכתב לסוכן, לשלוח לסוכן ונסתר ל אול-לטרס בלבד. לבטל את העותק שנשלח לסייט.
![image](https://user-images.githubusercontent.com/6491631/32137498-ea45098e-bc29-11e7-9f07-7ba74ea11718.png)

**Comment by natan1957** [comment]
סיכום אירוע לשלוח ישיר, ל
adminEmail
ברשומת עולם תוכן, העתק נסתר ל אול-לטרס זה מתבצע. וזה בסדר.
לבטל את האחרים
![image](https://user-images.githubusercontent.com/6491631/32137561-0771e86e-bc2b-11e7-87c9-30cb0fc5af7b.png)

**Comment by natan1957** [comment]
בחשבונית לרוכש באנגלית להחליף את המילה המסומנת ב
original
![image](https://user-images.githubusercontent.com/6491631/32137694-a9c205f2-bc2d-11e7-8a76-c0bcc8d4833e.png)

**Comment by natan1957** [comment]
לשנות בנושא מכתב למקבל השיעור באנגלית ובעברית לפי התמונות
![image](https://user-images.githubusercontent.com/6491631/32137767-ce9048b6-bc2e-11e7-9e00-1b164baecbd2.png)
![image](https://user-images.githubusercontent.com/6491631/32137775-f83cba6e-bc2e-11e7-9603-92fbfa7e32d7.png)

לבטל את השליחה ל סייט
![image](https://user-images.githubusercontent.com/6491631/32137800-65cbca16-bc2f-11e7-9ce2-6951bd3505ef.png)

**Comment by natan1957** [comment]
התוספת היא רק למכתב למקבל השיעור ולא לרוכש השיעור. גם בעברית וגם באנגלית.
![image](https://user-images.githubusercontent.com/6491631/32138040-997910f8-bc34-11e7-9f68-d8b12c4b3a3b.png)

**Comment by natan1957** [comment]
מכתב סיכום אירוע לשלוח ישיר, לכתובת שנמצאת בשדה
adminEmail
ברשומת עולם תוכן, כרגע יש שם את הכתובות הבאות:
nhelfman@gmail.com,igoro1975@gmail.com
העתק נסתר ל אול-לטרס זה מתבצע. וזה בסדר.

![image](https://user-images.githubusercontent.com/6491631/32233288-b4e8fb0c-be62-11e7-8175-408d08427c8a.png)

**Comment by natan1957** [comment]
בשליחת מכתב הודעה על קופון, שם השיעור לא מופיע במלואו אלא רק בחלקו. שם השיעור מורכב משני חלקים ומופיע רק החלק הראשון
גם בסוג הפריט מופיע "קופון" במקום "שיעור" ובמכתב האנגלי זה מופיע בעברית.
רכישת קופון יכולה להתבצע לשיעור או לחבילה. 
במקרה של שיעור צריך להופיע "שיעור" ושם השיעור בשני חלקים
במקרה של חבילה צריך להופיע "חבילה" ושם החבילה.
משום מה אני לא מצליח לבצע רכישת חבילה כך שאני לא רואה איך מוצג שם הפריט עבורו נרכש הקופון. אבל זו תקלה נפרדת...
![image](https://user-images.githubusercontent.com/6491631/32235522-5caa679a-be68-11e7-9794-30eee24565b1.png)
![image](https://user-images.githubusercontent.com/6491631/32236242-47b8cbf4-be6a-11e7-80e6-c98b1b257e29.png)

**Comment by natan1957** [comment]
בסביבת היצור כן מופיע שם הפריט למרות שסוג הפריט (שיעור או חבילה) לא מוצג נכון
![image](https://user-images.githubusercontent.com/6491631/32265982-1e67480a-beee-11e7-9faa-f453b8a5f14e.png)


בסביבת היצור גם הצלחתי להפיק קופון של חבילה מה שלא מצליח בסביבת הפיתוח.
![image](https://user-images.githubusercontent.com/6491631/32266061-87a165d0-beee-11e7-9dbc-9015b30a98a3.png)

**Comment by igoro1975** [comment]
תוקן.

**Comment by natan1957** [comment]
מה תוקן? הכול?
אתמול בהפרש של 6 דקות ביצעת רכישות יצאו שני מכתבי סיכום אירוע, הראשון לכתובת לא נכונה והשני לכתובת נכונה...
איך זה קורה?
![image](https://user-images.githubusercontent.com/6491631/32316982-f2dbfeec-bfba-11e7-8586-9be91fde01b7.png)
![image](https://user-images.githubusercontent.com/6491631/32317028-1b64772c-bfbb-11e7-94a2-e36769eaf663.png)
![image](https://user-images.githubusercontent.com/6491631/32317065-3ecbe614-bfbb-11e7-968f-634b0477c98c.png)

**Comment by igoro1975** [comment]
כי עבדתי בזמן הזה :)
1. בדקתי - לא תקין.
2. תיקנתי - תקין )

2017-11-02 10:48 GMT+02:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
שליחת מכתבים נבדק ונראה תקין למעט מכתב קופון לחבילה שלא עובד בטסט. יש על זה תקלה פתוחה. אשמח אם תטפל כדי שנוכל לסגור את עניין המכתבים. 

נשלח מה-iPhone שלי

‫ב-2 בנוב׳ 2017, בשעה 22:51, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬
