### ISSUE TITLE
אפשרות לאדמין לטפל במשתמש שלא השלים רישום

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#301]
![image](https://user-images.githubusercontent.com/6491631/28995586-8635a956-79f5-11e7-9ff9-2a0b40aede45.png)

**Comment by igoro1975** [comment]
עוד לפני השינויים שלי ראיתי ש-
Impersonation
לפעמים מתאפס. האם זה קרה גם לך?

**Comment by natan1957** [comment]
לא יודע מה זה...

נשלח מה-iPhone שלי

‫ב-18 באוג׳ 2017, בשעה 20:36, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
אהה הבנתי.. לא, זה לא מתאפס לי. לא ראיתי שזה קורה..

נשלח מה-iPhone שלי

‫ב-18 באוג׳ 2017, בשעה 20:36, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
אדמין לא מצליח להוסיף שיעור לסל ולהזמין דמו
![img_1102](https://user-images.githubusercontent.com/6491631/29487967-8ad49696-850a-11e7-8309-b7ef851313bd.PNG)

**Comment by igoro1975** [comment]
יש הרבה מקומות בפורטל בהם בודקים את הסטטוס (ולא פונקציה אחת) לכן כנראה
פספסתי.  אוסיף גם המקרה הזה.

19 авг. 2017 г. 18:17 пользователь "natan1957" <notifications@github.com>
написал:

**Comment by natan1957** [comment]
אותי מעניינות מספר פעולות שאני רוצה לבצע כאדמין על משתמש שטרם סיים רישום. 
אם אתקל בעוד, אוסיף..
האם אתה יודע להציג את כל המקומות בהם נבדק סטטוס נרשם באפליקציה?

**Comment by igoro1975** [comment]
1. הצגת שיעורים וחבילות
2. חשבון שלי
3. שיעורים שלי
4. הוספת פריט לסל

**Comment by igoro1975** [comment]
אני מנסה להבין האם המשימה הזאת הסתיימה?

**Comment by natan1957** [comment]
אדמין מתחזה למשתמש ולא מצליח להוסיף דמו  וגם לא להוסיף שיעור לסל
בהמשך אבדוק ביצוע רכישה ורכישת קופון ואם לא יאפשר, אבקש שתבדוק.
user = tempuser
![image](https://user-images.githubusercontent.com/6491631/30023613-d6d56852-9178-11e7-9f7a-ecb0217297ee.png)

**Comment by igoro1975** [comment]
כרגע טיפלתי גם במקרה הזה אבל עכשיו יש שגיאה בשמירת נתונים בשרת 
Parse
למשתמש כאשר אדמין מנסה לשמור. 
כאילו Parse
מנסה לחסום שמירת נתונים למשתמש על ידי משתמש אחר. נראה מוזר , מנסה להבין... 
האם זה עבד מתישהו?

**Comment by igoro1975** [comment]
לא מבין מה קורה אבל זה לא עבד עם שיעור מסויים, עם אחרים זה עובד.
תוקן הכל?
נשאר רק לבדוק את הרכישה?

**Comment by natan1957** [comment]
לא הבנתי איזה נתון השרת לא שמר. באיזה תהליך?
בתאריך יום ו׳, 8 בספט׳ 2017 ב-19:00 מאת Igor <notifications@github.com>:

**Comment by igoro1975** [comment]
אני בעצמי לא הבנתי מה קרה אבל ארי התיקון, לא הצלחתי להוסיף, כאדמין, שיעור אחד למשתמש שהאדמין מתחזה בו. אבל עכשיו הכל עובד ונראה זה היה פשוט עניין של ה-
cache.

**Comment by natan1957** [comment]
ישנה תקלה שלא מאפשרת לאדמין להוסיף שיעור לסל של תלמיד שטרם סיים רישום.
הסיבה שאני ראיתי היא שבהקמה לא אוכלס מפתח מטבע.
אני הקמתי דרך אפליקציית האנדרואיד. אתה דרך אפליקציית האייפון.
השאלה היא מי אחראי לאכלס את המטבע, האם התהליך להקמת משתמש (זה שבדקת את הסטטוסים) אמור להחליט איזה מטבע? או מי שמפעיל אותו צריך לספק את המטבע?

**Comment by igoro1975** [comment]
היום שדה המטבע לא מאוכלס כאשר הרישום דרך אפליקציות. בכלל. מי או מה אמור לאכלס - זה רק החלטה שלך.
אתה יכול לבקש ממפתחי אפליקציות להעביר את המטבע, יכול להגדיר מטבע ברירת מחדל במערכת...

**Comment by natan1957** [comment]
איזה נתונים ה ווב-סרוויס הזה מקבל מהאפליקציה ?

**Comment by igoro1975** [comment]
אני לא מבין את השאלה. זה מקבל מה שהאפליקציה שולחת.

**Comment by igoro1975** [comment]
public class UserMinimalRegistrationDto
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CultureName { get; set; }
        public string WorldContentTypeId { get; set; }
        public string OperatingSystem { get; set; }
        public string SoftwareVersion { get; set; }
        public string DeviceId { get; set; }
    }

**Comment by igoro1975** [comment]
זה הכל מה שאפשר לשלוח מהאפליקציה.

**Comment by natan1957** [comment]
מה זה ומה הוא עושה עם זה ?
CultureName

**Comment by igoro1975** [comment]
אין לזה שימוש. כנראה יצרתם מזמן ולא השתמשתם.
