### ISSUE TITLE
חסימת שינוי מטבע כשיש יתרה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#302]
![image](https://user-images.githubusercontent.com/6491631/28995608-d901d18c-79f5-11e7-8807-dddc4906a693.png)

**Comment by igoro1975** [comment]
מה המשמעות של השדה
lockCurrency
בטבלת
userAdminData?

**Comment by natan1957** [comment]
מאפשר למנהל לנעול את האפשרות של המשתמש להחליף מטבע. אבל עכשיו אני רוצה למנוע מכולם אם יש יתרה. 

נשלח מה-iPhone שלי

‫ב-9 בספט׳ 2017, בשעה 17:09, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by igoro1975** [comment]
אז אפשר לקבוע שמעכשיו השדה הזה יהיה 
True
אם קיימת יתרה?

**Comment by natan1957** [comment]
מתי תבצע את הבדיקה? בכול פעם שמשתנה היתרה? זה יכול לקרות בכמה מקומות.. כולל שינוי ידני דרך הדשבורד..
למה שלא תתיחס ליתרה שאינה אפס או ריק כמו ל true ותמנע את השינוי?

נשלח מה-iPhone שלי

‫ב-9 בספט׳ 2017, בשעה 17:41, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by igoro1975** [comment]
במערכת יש כבר משתנה הזה ואני רוצה לקבוע אותו תלוי גם ביתרה בחשבון. כאשר היתרה לא אפס אז לחסום שינוי המטבע.

**Comment by natan1957** [comment]
נבדק.
