### ISSUE TITLE
סטטוס רשומות רכישה ברישום מהאפליקציה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#303]
כאשר נרשמים מהאפליקציה ומפעילים את המתודה הסטטוסים נרשמים עם 
lesson_is_active
במקום
Lesson_is_active
יש לתקן את זה.

בתהליך השיעורים שלי יש לבדוק את הסטטוס ללא רגישות לאותיות גדולות/קטנות.

**Comment by igoro1975** [comment]
לא הבנתי איך לשחזר.
1. יוצרים משתמש מהאפליקציה
ומה אז?
על איזו מתודה מדובר?

**Comment by igoro1975** [comment]
נתן?

**Comment by natan1957** [comment]
[רישום משתמש באפליקציה.docx](https://github.com/natan1957/mymentor-portal/files/1291930/default.docx)

**Comment by igoro1975** [comment]
אני רואה שזה תקין כי תוקן במאי 2017.

**Comment by natan1957** [comment]
נבדק עם אנדרואיד בטסט ונמצא תקין
