### ISSUE TITLE
Unable uploading files at the dashboard

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#304]
אני לא מצליח לטעון קובץ
בזמנו, דבל קליק על שדה היה מאפשר לטעון קובץ מהמחשב.
כרגע ההודעה מופיעה אבל הקלקה עליה לא פותחת את הסייר לבחור ולטעון קובץ
![image](https://user-images.githubusercontent.com/6491631/30688433-cd52a118-9ec6-11e7-9a9c-8dbd6aa606af.png)

יש על כך דיון בקישור הבא, מישהו הוסיף משהו כדי שזה יעבוד..
https://github.com/parse-community/parse-dashboard/issues/480

**Comment by natan1957** [comment]
הטבלה היא 
ClipsV2
הרשומה היא
9IF2DiTyNA

שמתי לב שבטבלת העולמות לדוגמה, בעולם הרביעי, כשאני מנסה להעלות תמונה, זה כן פותח קבצים לבחירה...
![image](https://user-images.githubusercontent.com/6491631/30746930-2c0909e8-9fb4-11e7-9d5f-89a7ad495cdc.png)

**Comment by igoro1975** [comment]
תודה.

**Comment by igoro1975** [comment]
אני כרגע ניסיתי והצלחתי. העליתי את התמונה שלי :)

**Comment by igoro1975** [comment]
יש מצב שזה היה משהו זמני או תנסה למחוק את ה-
cache?

**Comment by natan1957** [comment]
ראיתי. מחקתי אותה ואני עדיין לא מצליח לטעון.
לפי דעתי עשיתי איתחול למחשב וזה לא עזר...
איך אני מנקה קש ?

**Comment by igoro1975** [comment]
אגב, איך אתה מוחק את התמונה שכבר עלתה?

לנקות Ctrl + Shift + Del

**Comment by natan1957** [comment]
דבל קליק על הפינה איפה שסימנתי נקודה אדומה
![image](https://user-images.githubusercontent.com/6491631/30747291-7584ca98-9fb5-11e7-9cc5-4e434eb254cc.png)

**Comment by igoro1975** [comment]
מטורף )))

**Comment by natan1957** [comment]
הקומבינציה פותחת הגדרות דפדפן..

**Comment by natan1957** [comment]
נראה לי שהצלחתי.

**Comment by natan1957** [comment]
אני שוב לא מצליח!!

**Comment by igoro1975** [comment]
אני כן מצליח. לא יודע מה לומר לך.
