### ISSUE TITLE
התהליך מודיע שלא מוצא סוכן

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#305]
כאשר מתבצעת רכישת שיעור, המורה זכאי לעמלה.
במידה ולמורה יש סוכן, גם הסוכן זכאי לעמלה.
אם למורה יש סוכן, שם הסוכן נרשם ברשומת המורה. אם אין סוכן, השדה ריק.
בתהליך החישוב, אם יש סוכן ברשומת המורה, מתבצעת גישה לסוכן (שהוא משתמש רשום במערכת) כדי להביא את גובה העמלה.
אם הסוכן לא נמצא, נשלח מייל שמתריע על כך והתהליך ממשיך כאילו אין סוכן.

אני מבצע רכישה ע"י משתמש תה4444 שיעור של המורה אלעד.
למורה אלעד יש סוכן סו4444.
המערכת שולחת מייל שהסוכן לא נמצא וגם לא מחשבת לו עמלה.
זה לא נכון, הסוכן נמצא. ובמכתב אפילו מוצג השם שלו.  השאלה למה התהליך מודיע שלא מוצא אותו.
התהליך הזה עבד בעבר.

בנוסף, נושא המכתב לא נכון אלא לקוח ממכתב אחר.
![image](https://user-images.githubusercontent.com/6491631/30746667-2ec22bb6-9fb3-11e7-8311-e9d427bf1f93.png)

**Comment by igoro1975** [comment]
כאשר אני נכנס לרשימה של המורה הזה ואז ל-
adminData
שלו, אז שם שדה 
agent
ריק.
https://image.prntscr.com/image/mu4j-kxjQVW1AmAu_TVNhA.png

**Comment by natan1957** [comment]
אבדוק את זה..
אבל אם זה ריק, אז מאיפה הוא יודע להביא למכתב את שם הסוכן ש״לא נמצא״? לא את שם המשתמש.. אלא את השם הפרטי ושם המשפחה... ז״א שהוא כן מצא את המשתמש. זה מוזר לי. 

נשלח מה-iPhone שלי

‫ב-22 בספט׳ 2017, בשעה 16:52, ‏‏Igor ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
כרגע יש למורה אלעד סוכן סו4444

**Comment by igoro1975** [comment]
אני גם ראיתי שהמערכת מביאה את הנתונים גם מאיזשהו מקום אחר, עדיין לא בדקתי מאיפה. אעדכן אותך כאשר אבדוק.

**Comment by igoro1975** [comment]
האם אפשר לסגור את הבאג?
