### ISSUE TITLE
חישוב עמלת סוכן

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#306]
תהליך זה נבדק פעמים רבות והיה תקין.
כרגע, משום מה עמלת הסוכן מחושבת לא נכון.
סוכן 4444 מקבל 25% במקום 20
סוכן 5555 מקבל 10% במקום 15
עמלת הסוכן רשומה ברשומת אדמין-דאטה של הסוכן בשדה עמלת סוכן.
הסוכן של המורה רשום ברשומת אדמין-דאטה של המורה בשדה סוכן.
כרגע סו4444 הוא סוכן של מו4444
סו5555 הוא סוכן של אלעד
![image](https://user-images.githubusercontent.com/6491631/32045886-1cefa16e-ba4a-11e7-99b8-d841fb75f02e.png)

**Comment by igoro1975** [comment]
האם אני מבין אותך נכון שירדו 5% מאחד והתווסף לשני? :)

**Comment by natan1957** [comment]
זה לא "עבר" אלא שגוי בשני המקרים. במקרה זה כאילו עבר.

**Comment by natan1957** [comment]
אחוז העמלה של הסוכן נלקח מרשומת הסוכן.
אם ברשומת הסוכן הערך הוא 999 (אין ערך) אז אחוז העמלה נלקח מרשומת עמלות
גלובלית.

2017-10-27 0:34 GMT+03:00 Natan Helfman <nhelfman@gmail.com>:

> זה לא "עבר" אלא שגוי בשני המקרים. במקרה זה כאילו עבר.
>

**Comment by igoro1975** [comment]
נתן, אני צריך הסבר נוסף (עם שמות השדות) מה צחושב ואיך. אם יותר קל להסביר בטלפון, אז נדבר.

**Comment by igoro1975** [comment]
![tcp](https://user-images.githubusercontent.com/4538009/32856137-9bc48a4c-ca4c-11e7-9373-70c15f58ea3f.png)

**Comment by igoro1975** [comment]
אני לא מבין איך זה עבד קודם כי מ-2 לאפריל 2016 זה תמיד היה עם שגיאה. במקום ACP נלקח לסוכן TCP.
