### ISSUE TITLE
רכישה עבור משתמש לא קיים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#307]
לגמרה במקרה הכנסתי ל "הרכישה עבור" שם משתמש לא קיים.
![image](https://user-images.githubusercontent.com/6491631/32233970-5897b71a-be64-11e7-87a9-6bd682beafa0.png)

לפי דעתי, בלחיצה על שלם או אשר המערכת צריכה לבדוק את זה.
לא בדקה.
יש לבדוק אם הבדיקה מתבצעת ולהשמיש אותה.
שלחה לי את המייל הזה:
![image](https://user-images.githubusercontent.com/6491631/32234031-790bb83e-be64-11e7-98a6-9aa42646a4c2.png)
יש לבדוק קיום המשתמש ולהציג הודעה מטבלת סטרינגים ולעצור את התהליך

**Comment by natan1957** [comment]
ראיתי שזה תוקן,
באיזה מקרים יוצא המייל הזה?
יש לשלוח אותו לכתובת אדמין ברשומת העולם

**Comment by igoro1975** [comment]
- המייל נשלח כל פעם כשיש שגיאה בתהליך. 
- זה נשלח לאדמין מייל של עולם
- הוספתי כותרת של שגיאה למייל
