### ISSUE TITLE
בטופס פרטי משתמש באזור מנהל בשמות השדות 

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#313]
עמלת מורה TPC  יש להוסיף "0.2=2%   999=עמלת ברירת מחדל"
עמלת סוכן APC יש להוסיף "0.2=2%   999=עמלת ברירת מחדל"

לא בוצע

**Comment by igoro1975** [comment]
לא הבנתי. תסביר לי בבקשה מה בדיוק להוסיף ואיפה. תודה.

**Comment by natan1957** [comment]
![image](https://user-images.githubusercontent.com/6491631/44018191-ac3981cc-9ee3-11e8-8e1e-ada3d1d60f56.png)

**Comment by natan1957** [comment]
מה עם זה ?

**Comment by igoro1975** [comment]
תוקן

**Comment by natan1957** [comment]
תקין
