### ISSUE TITLE
קביעת מדינה למשתמש חדש

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#316]
14.	בהקמת משתמש דרך האפליקציה, אם ממשק עברי – ישראל – ₪ אם ממשק אנגלי – ארה"ב - $.

בממשק אנגלי זה לא קובע ארה"ב אלא ישראל

**Comment by igoro1975** [comment]
איך אני יכול לדעת באיזו שפה הממשק של המשתמש? נשלח קלט מהאפליקציה ורק לפיו אני יכול להסיק מסקנות. אין לי גישה לממשק עצמו רק מה שנשלח. בקלט יש CultureName - אני יכול לקבוע מדינה לפי השדה הזה. האם מתאים?

**Comment by natan1957** [comment]
האם השדה
CultureName
נמצא בקלט ? האם הוא מאוכלס? אם כן, ניתן להתייחס אליו בקביעת המדינה והמטבע

**Comment by natan1957** [comment]
תקין
