### ISSUE TITLE
שינוי הודעה למורה בהעברה שיעור של עצמו לסל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#317]
16.	כאשר מורה  מעביר שיעור של עצמו לסל או מנהל כל שיעור, זה למעשה מעביר לו ישר את השיעור. ההודעה שצריכה להופיע היא : "השיעור הועבר לאפליקציה" או "החבילה הועברה לאפליקציה" ולא להציג את הכפתור שמוביל לקופה אלא רק את זה שמחזיר לשיעורים וחבילות.

בנוגע להעברת חבילות לסל, זה טעות שלי, לא צריך היה לשנות את ההודעה. יש להחזיר למצב הקודם.
בנוגע להעברות שיעורים, תקין.

**Comment by igoro1975** [comment]
אני לא הבנתי למה במקרה של חבילה צריך להחזיר רק את ההודעה. מה קורה עם החבילה עצמה כאשר אדמין (לדוגמה) לוחץ "הוסף לסל" לחבילה?

**Comment by natan1957** [comment]
כאשר מורה מעביר לסל שיעור של עצמו השיעור עובר מיד לסטטוס נרכש. 
כאשר אדמין מעביר שיעור כלשהו לסל, אותו דבר. 
כאשר מורה ואגמים מעבירים חבילה לסל, החבילה עוברת לסל וממתינה לביצוע רכישה. 
לכן ההודעה בחבילה צריכה להיות כמו למשתמש רגיל. 
בגללך לא ראיתי את השער של רונלדו ...

**Comment by natan1957** [comment]
בוצע
