### ISSUE TITLE
18.	לשנות את מספר השיעורים בדף (פרמטר). 

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#319]
איפה הפרמטר?

**Comment by igoro1975** [comment]
In web.config file. Key "DefaultPageSize"

**Comment by natan1957** [comment]
זה זמין לי ?
אני יכול לשנות את זה?

**Comment by igoro1975** [comment]
רק דרך ניהול האחסון של הפרויקט: https://prnt.sc/k49cas

**Comment by natan1957** [comment]
אפשר להעביר ל קונפיג? כמו בשיעורים שלי ?
![image](https://user-images.githubusercontent.com/6491631/44020075-6036331e-9ee9-11e8-92fb-9fc6d253e591.png)

**Comment by natan1957** [comment]
טופל
