### ISSUE TITLE
הצגת תקנון בהתאם לעולם, לשפה, לתלמיד ולמורה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#322]
לצורך הבדיקות, הכנסתי בעולם דמו ובעולם תורה באנגלית ועברית למורה ולתלמיד לינקים רלוונטיים.
בטופס עדכון תלמיד אין לינק לתקנון. 
בטופס רישום תלמיד אין התייחסות לעולם אם הוא השתנה
בטופס עדכון פרטי מורה, לחיצה על תקנון פותחת חלון עם התעופפות.

**Comment by natan1957** [comment]
גם תלמיד וגם מורה מפעילים את הלינק של התלמיד. מורה צריך להפעיל לינק של מורה.
![image](https://user-images.githubusercontent.com/6491631/44023766-fa994dc4-9ef3-11e8-80ac-5b71a974e550.png)
עולם התוכן שאליו פונים צריך להיות זה שמוצג האותו הרגע בטופס. ז"א שאם המשתמש בוחר עולם שונה ממה שהוצג קודם, ופונה לתקנון, זה צריך לפנות לעולם התוכן שהוא בחר ורוצה לעבור אליו ולא לעולם שהיה קודם.

**Comment by igoro1975** [comment]
תוקן

**Comment by natan1957** [comment]
זה לא עובד תקין.
אם אני משנה את עולם התוכן, ולפני שאני מעדכן את הרשומה, לוחץ על הלינק על התקנון, זה מציג תקנון של עולם התוכן הקודם.
זה צריך להציג את עולם התוכן הנבחר שמוצג על המסך גם אם טרם עודכן ברשומה.

**Comment by igoro1975** [comment]
תראה את הסרטון: https://drive.google.com/file/d/1SDTRwOxV00iv0fqbdET8vUqgxG_WaXpD/view

מה אני מפספס? נראה לי שהכל תקין.

**Comment by natan1957** [comment]
בעדכון פרטי מורה, הגישה לתקנון צריכה להיות מהלינק שבעמודה הנכונה
![image](https://user-images.githubusercontent.com/6491631/44469007-35239c00-a62f-11e8-98e6-54b8dfecc8c5.png)

**Comment by igoro1975** [comment]
סידרתי

**Comment by natan1957** [comment]
תקין
