### ISSUE TITLE
שינוי הסבר בסעיף 5

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#327]
חלק שני של סעיף 5 לא בוצע
את ההסבר השני (אחרי ההעברה לסל..) יש לשנות לטקסט: אחרי העברת החבילה לסל, יש לבצע את הרכישה. בסיום הרכישה יופיעו באפליקציה כל השיעורים שבחבילה. (גם באנגלית)

**Comment by MyMentorah** [comment]
After moving the package to the basket and checking out, all lessons in the purchased package  will appear in the app

**Comment by natan1957** [comment]
תקין
