### ISSUE TITLE
מורה11 לא רואה שיעורים של עצמו

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#33]
לאחר כל מיני בדיקות ושינויי סטטוסים, חל איזה שיבוש ונקלעתי למצב שלא ברור איך קרה, בו מורה11 לא מצליח לראות את השיעורים של עצמו.
למורה11 חמשה שיעורים, שניים מהם פעילים.
תלמיד11 מצליח לראות את שני השיעורים הפעילים של מורה11 אבל המורה לא מצליח לראות למרות שהסטטוס שלו פעיל.
תוך כדי הבדיקות שיניתי ידנית (ישירות בטבלה) את הרול של המשתמש ממורה לתלמיד, כמו כן שיניתי את השדה מבקש להירשם כמורה ל"שקר". 
באותו הרגע המשתמש חזר להתנהג כתלמיד.
לאחר מיכן נכנסתי דרך המערכת וסימנתי את מבקש להירשם כמורה ופתחתי את טופס מורה ושמרתי.
בהמשך נכנסתי כמנהל ואישרתי את המורה ל פעיל.
כעת, הסטטוסים שלו פעיל, אבל כאמור הוא איננו רואה את השיעורים של עצמו.

**Comment by tom-hollander** [comment]
מורה רואה שיעורים של עצמו בכל סטטוס של השיעור או של המורה
