### ISSUE TITLE
רכישת מנוי עם מחיר אפס

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#351]
המשתמש הוא מנוי פעיל, ובהעברת שיעור לסל, הוא מקבל מחיר אפס.
![image](https://user-images.githubusercontent.com/6491631/142867337-4afbcab7-124e-45f8-ae01-2af4fe49ef72.png)
![image](https://user-images.githubusercontent.com/6491631/142867502-32e331b6-d0a1-42e2-8e69-6c92217560de.png)
![image](https://user-images.githubusercontent.com/6491631/142868994-875c7892-f9d5-4fcd-bc81-5b8abb4adac8.png)

**Comment by igoro1975** [comment]
clipType is null

**Comment by natan1957** [comment]
תקין
