### ISSUE TITLE
חבילה צריכה לכלול שיעורים של מורה  יחיד

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#37]
חיפוש שיעורים צריך לסנן רק את השיעורים של המורה שמקים את החבילה
![image](https://cloud.githubusercontent.com/assets/6491631/5583134/94669bf8-907c-11e4-90ed-4280bb79f976.png)

**Comment by tom-hollander** [comment]
האם מדובר בבאג או שינוי\תוספת לאיפיון ?

**Comment by natan1957** [comment]
זה נמצא באפיון

**Comment by tom-hollander** [comment]
איפה ?

**Comment by tom-hollander** [comment]
ומה קורה כאשר מנהל בונה חבילה, האם גם למנהל יש להציג רק את השיעורים שלו ?

**Comment by natan1957** [comment]
חיובי. גם מנהל מקים חבילות של מורה יחיד. 
מנהל יכול להתחזות למורה ולהקים עבורו חבילה. כל השיעורים יהיו של אותו המורה. 
מסך חיפוש שיעורים להוספה לחבילה לא יציג שיעורים של מורים אחרים.
