### ISSUE TITLE
שערי מטבע

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#39]
האם עולים לקש?
האם עולים לקבצים?
אם אני משנה שער ידנית בטבלה, מתי אראה את השינוי בפורטל ?

**Comment by tom-hollander** [comment]
עולה לקש, וכאשר גולשים לכתובת mymentorapp.com/home/clearcache זה מתעדכן. אבל יכול להיות שיש בלבול מסויים . ישנה טבלה CurrencyExchangeRate שנראה שהיא לא בשימוש. אני מתייחס לשדות exchangeRate בטבלת Currency

**Comment by natan1957** [comment]
לא הבנתי כלום.
תערובת של עברית ואנגלית בלתי קריאה..
טקסט אנגלי יש לכתוב בשורה נפרדת.


2015-01-02 17:13 GMT+02:00 tom-hollander <notifications@github.com>:

**Comment by tom-hollander** [comment]
זה מתעדכן. כאשר גולשים לכתובת
mymentorapp.com/home/clearcache
נתוני שערי המטבע נלקחים מטבלת 
Currencty
ולא מטבלת 
CurrencyExchage
