### ISSUE TITLE
חישוב מחיר מינימום של חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#42]
במקרה הזה הסכומים המצטברים היו צריכים להיות
אפס אחוז הנחה ל 222 שווה 222
חמישים אחוז הנחה ל 150 שווה 75
תשעים אחוז הנחה ל 104 שווה 10.4
ובסך הכל 307.4
![image](https://cloud.githubusercontent.com/assets/6491631/5618266/eec8d938-951f-11e4-8af8-c87243c65d5b.png)

![image](https://cloud.githubusercontent.com/assets/6491631/5618208/3a24749c-951f-11e4-9bf9-b40654ac4523.png)

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/5646919/d634ad0a-9689-11e4-9b8c-f91076fe13e4.png)

222 - 0% = 222
200 - 50% = 100
150 - 90% = 15
90 - 90% = 9
total = 346
![image](https://cloud.githubusercontent.com/assets/6491631/5647004/98070d06-968a-11e4-8895-f05cd25903a2.png)

**Comment by tom-hollander** [comment]
ההנחה האחרונה אינה 90 אלא 60 מכיון שכבר קיים קליפ עם אותה קטגוריה 1 ו2

**Comment by natan1957** [comment]
אתה צודק.. טעות שלי.. הבדיקה של קיום קליפ עם אותה קטגוריה לשם מתן הנחה מסוג 2 צריך להתבצע על קטגוריה 3 ולא על קטגוריות 1 ו 2

**Comment by natan1957** [comment]
600 - 0% = 600
200 - 50% = 100
120 - 90% = 12
105 - 60% = 42  second maftir   discount2
100 - 95% = 5
total = 759

![image](https://cloud.githubusercontent.com/assets/6491631/5792807/52ccad52-9f33-11e4-8cd6-2c23c48119f5.png)

![image](https://cloud.githubusercontent.com/assets/6491631/5792804/39880580-9f33-11e4-8e6a-af51856169f0.png)

![image](https://cloud.githubusercontent.com/assets/6491631/5792850/b9b4894e-9f34-11e4-9a96-70cca8ec6ae7.png)
