### ISSUE TITLE
שם חבילה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#45]
יש לאפשר איפוס הקטגוריות שבונות את שם החבילה, כך שאם לא בוחרים / מאפסים קטגוריה, היא לא תופיע בשם.
למעשה ניתן לא לבחור / לאפס את כל הקטגוריות. והשם יהיה מורכב רק מתוספת לשם חבילה.
אם מאפסים קטגוריה, יש לסלק גם את הפסיק שאחריה.
אין לאפשר שם ריק.

**Comment by tom-hollander** [comment]
כעת ניתן לאפס את הקטגוריות. יש בעיה אבל שעולה מתוך האפיון . התבנית של שם החבילה מורכבת מערכים דינמיים ומערכים סטטיים, למשל "בנוסח" הינו ערך סטטי ולכן אני לא יודע להסיר אותו כאשר לא מזינים ערך בשדה נוסח מבלי לפגוע בגנריות של התהליך. כרגע "נוסח" ישאר בכותרת גם אם לא נבחר נוסח.
כדי לפתור את זה , אתה יכול לכלול את המילה "נוסח" בשם הקטגוריה עצמה ואז לתקן את התבנית בהתאם

**Comment by natan1957** [comment]
הוספתי ותיקנתי את התבנית.
עדיין יש איזה בעיה עם הפסיקים המפרידים בין המרכיבים של שם החבילה.
כאשר אין קריאה, קטגוריה3, לא מוצג פסיק אחרי קטגוריה2.
כאשר יש קטגוריה3, מתווסף הפסיק...
![image](https://cloud.githubusercontent.com/assets/6491631/5792170/c45609de-9f13-11e4-8e1f-4606953b596a.png)

![image](https://cloud.githubusercontent.com/assets/6491631/5792173/e263afee-9f13-11e4-94ea-253c0a686889.png)
