### ISSUE TITLE
לינק הצג חבילת מבצע

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#50]
אני רואה שהלינק לא מופיע בשיעור שנמצא בראש הדף.. האם זה מה שהבנת ממני ?
אני התכוונתי שאין להציג לינק בשיעור הנמצא בתוך חבילה, אם זו החבילה הפעילה היחידה שלו...
לא ברור לי אם מה שעשית מתייחס לבקשה הזאת או לאיזה...
![image](https://cloud.githubusercontent.com/assets/6491631/5723469/ead4192c-9b4c-11e4-91be-433966a51cc8.png)

**Comment by natan1957** [comment]
לא ברור מה טופל.
אין להפלות בין שיעורים בחבילה..
אם ניתן להחיל את החוק שקובע שאם אין לו חבילות נוספות(לחבילה שהוא מוצג בה) אין להציג לינק חבילה, אז אשמח.
אם לא ניתן, אז כל השיעורים בחבילה צריכים להציג לינק חבילה.

**Comment by tom-hollander** [comment]
האם אתה מבקש להציג קישור שמוביל לאותו עמוד שהמשתמש נמצא בו כרגע רק כדי לא
להפלות? נראה לי שהאתר לא יפגע רגשית מזה הוא יקבל את זה בהבנה...

**Comment by natan1957** [comment]
האתר ואני מעריכים את ההומור שלך..
האתר אפילו התפוצץ מצחוק.
בכל מקרה, מי שעלול להיפגע רגשית הוא המשתמש.. הרי  גם בחלק משמעותי של הלינקים של השיעורים האחרים הוא יחזור לאותה חבילה..
המצב הנוכחי נראה לא טוב..

**Comment by tom-hollander** [comment]
אבל אז העמוד משתנה .השיעור שנבחר יופיע בראש העמוד.ברגע שאתה לוחץ על קישור
שלא משנה את העמוד בכלל יש כאן התנהגות מוזרה שעלולה לשקף תקלה למשתמש.אני
חושב שבהעלמת הקישור מכניסים את המשתמש לקונטקסט הנכון בכך שמשקפים לו שהתצוגה
שהוא רואה היא בעקבות בחירה שהוא בחר. אבל אם בכל זאת אתה רוצה להציג את
הקישור זה לא בעיה

**Comment by natan1957** [comment]
מה דעתך להציג את המשפט במצב לא פעיל בצבע אפור..

נשלח מה-iPhone שלי

ב-Jan 18, 2015, בשעה 19:24, tom-hollander <notifications@github.com> כתב/ה:

> אבל אז העמוד משתנה .השיעור שנבחר יופיע בראש העמוד.ברגע שאתה לוחץ על קישור 
> שלא משנה את העמוד בכלל יש כאן התנהגות מוזרה שעלולה לשקף תקלה למשתמש.אני 
> חושב שבהעלמת הקישור מכניסים את המשתמש לקונטקסט הנכון בכך שמשקפים לו שהתצוגה 
> שהוא רואה היא בעקבות בחירה שהוא בחר. אבל אם בכל זאת אתה רוצה להציג את 
> הקישור זה לא בעיה

**Comment by tom-hollander** [comment]
לדעתי זה לא נכון מכיוון שאתה מציג למשתמש הודעה "הצג חבילת מבצע"  אבל לא ניתן ללחוץ על זה, זה לדעתי יהיה מוזר למשתמש.
מה ברצונך לעשות ? האם להציג את הקישור בכל מקרה , גם אם הלחיצה עליו מובילה לאותו עמוד ?

**Comment by natan1957** [comment]
הפתרון הוא להציג לינק רק בשיעורים שמחוברים ליותר מחבילה אחת והטקסט של הלינק יהיה: הצג חבילות נוספות

**Comment by natan1957** [comment]
זה לא קורה.
בדוגמה המצורפת, השיעור חנוכה עליה שניה מחובר רק לחבילה זו ולא לחבילות נוספות ובכל זאת מוצג הלינק.
הלינק צריך לניות מוצג רק אם השיעור מחובר ליותר מחבילה אחת.
more11@gmail.com
more11
![image](https://cloud.githubusercontent.com/assets/6491631/11975376/e0cbb222-a975-11e5-88ab-381c55bde12f.png)

**Comment by natan1957** [comment]
אני רוצה לפרט:
בהצגת חבילה מוצג מעליה השיעור עליו הקלקנו להצגת החבילה - מסומן 1.
השיעור הזה מופיע גם בתוך החבילה  - מסומן 1
אם שיעור 1 מחובר לחבילה נוספת הוא יציג קישור "הצג חבילות נוספות".
אם שיעור 1 לא מחובר לחבילות נוספות הוא לא יציג קישור בכלל.
אם שיעור 2 (וכל שאר השיעורים שאינם 1) מחובר לחבילות נוספות הוא יציג קישור "הצג חבילות נוספות".
אם שיעור 2 מחובר רק לחבילה זו הוא יציג קישור " הצכ חבילת מבצע".
![image](https://cloud.githubusercontent.com/assets/6491631/12017930/71735490-ad65-11e5-81fd-775482682d74.png)

**Comment by tom-hollander** [comment]
אני רואה שכרגע המצב הוא כפי שאתה מבקש בהודעה הקודמת , שהשיעור יציג קישור רק
אם הוא מחובר לחבילה נוספת. זה מה שביקשת.
בהודעה הבאה שלך מבקש בכל זאת להציג קישור אבל עם כיתוב אחר וזה לא צויין
בדרישה המקורית שלך.

[image: Inline image 1]

2015-12-28 13:20 GMT+02:00 natan1957 <notifications@github.com>:

**Comment by natan1957** [comment]
ההודעה הקודמת התייחסה ללינק המוצג בשיעורים מסוג 1. זה היה קונטקסט השיחה.  אתה מימשת את זה (אם אני לא טועה) על כלל השיעורים. 
ההתייחסות הנוספת היא לשיעורים מסוג 2, להבחין בין כאלה שמחוברים לחבילה אחת(הנוכחית) לכאלה שמחוברים לחבילות נוספות. זה לא חובה, אבל יש לזה ערך מוסף.

**Comment by tom-hollander** [comment]
נרכז תוספות בנפרד

**Comment by natan1957** [comment]
נמצא ב 141
