### ISSUE TITLE
אופן התשלום דרך פייפל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#59]
טופס פייפל צריך לאפשר תשלום באמצעות חשבון פייפל(למי שיש כזה חשבון ומעוניין לשלם איתו) או באמצעות כרטיס אשראי כפי שמוצג בתמונה ששלחתי לך. ישנה גם אופציה להצטרף לפיפל.

בטופס שמוצג לי כעת, אין אפשרות לשלם בכרטיס אשראי אלא רק בפיפל, או להצטרף לפיפל ואז כפי הנראה לשלם באמצעות חשבון פיפל.
אני מניח (מקווה) שמדובר בפרמטר.. אבל כאמור יש לאפשר למשתמש לשלם עם כרטיס אשראי בלי להיות חבר בפיפל.

מה המשמעות של תשלום בארגז החול? האם אני צריך להכניס כרטיס אמיתי? איפה נרשם התשלום? האם מתנהל חשבון?

![image](https://cloud.githubusercontent.com/assets/6491631/7100732/a28a6922-e03a-11e4-9920-50b0a81d4e1c.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7100743/584cfec8-e03b-11e4-8086-6b05436416d4.png)

**Comment by tom-hollander** [comment]
כפי שדיברנו, המסך של paypal בsandbox קצת שונה מהמסך בסביבת ייצור .

אין הרבה הבדל למעט בUI ( בייצור הנתונים של הרישום לpaypal מוסתרים, אני אשנה את הפרמטר שמכוון לsandbox ואבדוק את הנראות בייצור של paypal).

 

לגבי בדיקת הטרנסאקציות:

1.      המשתמש שלי הוא

 <mailto:Tomh.hollander@gmail.com> Tomh.hollander@gmail.com

matterhorn!1

 

2.      כנס developer.paypal.com

3.      בצע לוגין עם פרטי המשתמש שלי

4.      בראש העמוד תראה קישור “dashboard” לחץ עליו.

5.      מצד שמאל תחת Sandbox כנס לaccounts. תמצא שם 2 חשבונות *facilitator וbuyer.

6.      מעל החשבונות יופיע קישור כניסה לאתר בsandbox לחץ עליו ובצע כניסה לאתר sandbox  באמצעות פרטי המשתמש של הfaciliator.(את פרטי המשתמש והסיסמה תוכל למצא אם תלחץ על קישור profile מתחת לחשבון הfaciliator).

7.      לאחר הכניסה, אתה אמור להיות בעמוד פירוט החשבון, תוכל לראות שם את כל הפעילות של החשבון( אני לא חושב שזה מתעדכן בrealtime אבל תוכל לראות את הפעולות שבוצעו יום קודם)

 

אני אהיה זמין בשני בערב במידה ויהיו לך שאלות. תוכל במקביל לפנות לpaypal במידה ויש לך שאלות שקשורות אליהם.

 

תום
