### ISSUE TITLE
הצגת שיעורים בכפוף לסטטוס פרסום

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#60]
לא מוצגים שיעורים של מורה שסטטוס הפרסום שלו "טעון אישור". זה לא נכון.
הסטטוס (השדה) הזה לא משתתף בשיקול האם להציג או לא. אפילו הערך חסום בסטטוס הזה לא מונע הצגת שיעורים פעילים למורה עם סטטוס משתמש פעיל.
 רק סטטוס משתמש וסטטוס השיעור משתתפים בהחלטה.

**Comment by tom-hollander** [comment]
אם איזה משתמש נכנסת? תלמיד או מורה?

**Comment by natan1957** [comment]
תלמיד

נשלח מה-iPhone שלי

ב-Apr 13, 2015, בשעה 15:29, tom-hollander <notifications@github.com> כתב/ה:

> אם איזה משתמש נכנסת? תלמיד או מורה?

**Comment by tom-hollander** [comment]
אז אתה מבקש שלא משנה מהו הסטטוס פרסום של שיעור ,השיעור עדיין יופיע לתלמידים
וגם למשתמשים שלא ביצעו לוגין למערכת. נכון?

**Comment by natan1957** [comment]
אני לא מדבר על סטטוס השיעור. ברור שהוא חייב להיות פעיל. 
אני מדבר על סטטוס העלאת שיעור של המורה. אם הסטטוס לא פעיל ואפילו חסום זה לא אומר ששיעורים שהעלה בעבר ושהם פעילים לא יוצגו. 
אם ארצה למנוע את הצגתם אשנה את סטטוס המשתמש שלו. סטטוס המשתמש המורה כן משפיע על נראות השיעורים. סטטוס העלאת שיעור לא. 
מקווה שהבהרתי.. אם לא אז נדבר כי חבל שתעשה משהו שלא התכוונתי. 

נשלח מה-iPhone שלי

ב-Apr 13, 2015, בשעה 16:43, tom-hollander <notifications@github.com> כתב/ה:

> אז אתה מבקש שלא משנה מהו הסטטוס פרסום של שיעור ,השיעור עדיין יופיע לתלמידים 
> וגם למשתמשים שלא ביצעו לוגין למערכת. נכון?
