### ISSUE TITLE
הודעה בממשק אנגלי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#61]
זו ההודעה שמתקבלת
![image](https://cloud.githubusercontent.com/assets/6491631/7215816/c87d266e-e5ef-11e4-9345-284b4fe9f4b2.png)

**Comment by tom-hollander** [comment]
צריך לתרגם את ההודעה , זה תחת מפתח lblRegistrationConfirmationForStudent  בקבצים ששלחתי לך
