### ISSUE TITLE
מורה לא נמצא

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#63]
אני מנסה לעדכן שיעור ומקבל הודעת שגיאה.
un= more77@gmail.com pw= more77
![image](https://cloud.githubusercontent.com/assets/6491631/7215923/4e38232c-e5f4-11e4-9bb4-db0fd9500b2f.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7215928/74a64aac-e5f4-11e4-8a5b-9e4300bace04.png)

**Comment by tom-hollander** [comment]
יכול להיות שהגרש בשם המורה מפריע ?

**Comment by natan1957** [comment]
הורדתי את הגרש.
לא עזר

**Comment by tom-hollander** [comment]
הזנת את השם הפרטי עם רווח מיותר, תיקנתי כך שהמערכת תתעלם מרווחים

**Comment by natan1957** [comment]
האם טופל ?

**Comment by tom-hollander** [comment]
כעת ניתן לשמןר.התיקון של הרווחים עוד לא עלה
