### ISSUE TITLE
הבדלים בשאילתות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#65]
כשאני מסנן את כל השיעורים של אסתר אני מקבל 5 שיעורים
כאשר אני מוסיף מסנן "מפטיר" מופיע שיעור שלא הופיע קודם
כאשר אני מחפש שיעורים בתהליך הוספה לחבילה אני מקבל 6 שיעורים
ניתן לראות זאת גם כאורח, חוץ מאשר את שאילתת ההוספה בהקמת חבילה

![image](https://cloud.githubusercontent.com/assets/6491631/7483822/028875cc-f38b-11e4-8bfb-e8a37ba537dd.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7483888/a8cfaa04-f38b-11e4-9771-c9a22d216a46.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7483844/26153066-f38b-11e4-9e97-d45c64f5d8a3.png)

**Comment by tom-hollander** [comment]
אם איזה משתמש מתבצעת הבדיקה ?

**Comment by natan1957** [comment]
ניתן לראות את זה גם כמשתמש אורח.

**Comment by natan1957** [comment]
אם נכנסים כאורח לשיעורים וחבילות ומדפדפים קדימה, אפשר לראות 6 קליפים של אסתר.
אם מסננים לפי "אסתר" מקבלים רק 5 קליפים
![image](https://cloud.githubusercontent.com/assets/6491631/7488086/39e9e4dc-f3cd-11e4-9abb-ecf728070f1f.png)

![image](https://cloud.githubusercontent.com/assets/6491631/7488074/1630da3c-f3cd-11e4-851a-6288f7823564.png)
