### ISSUE TITLE
שם שיעור לא מתעדכן

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#70]
לאחר שינוי שם מורה מ מורה11 מורה11 ל אסתר ברגר
ולאחר עדכון השיעורים שלה, שם השיעור לפורטל חלק2 מתעדכן אבל שם שיעור לא מתעדכן

![image](https://cloud.githubusercontent.com/assets/6491631/7563373/44b10f00-f7e5-11e4-9e8a-0e71d9ba4311.png)

**Comment by tom-hollander** [comment]
זה יכול להיות כבד כי זה אומר שצריך לרוץ על כל השיעורים והחבילות

**Comment by tom-hollander** [comment]
נא להתעלם מההערה הקודמת

**Comment by natan1957** [comment]
זה לא טופל. השדות שם שיעור לא מתעדכנים  אלא רק שדות שם שיעור לפורטל חלק2
ראיתי ששינוי שם מורה מעדכן גם את שמות כל השיעורים  של המורה בהתאם. אבל שינוי ישוב של מורה לא מגיע לשמות השיעורים.
