### ISSUE TITLE
סינון משתמשים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#71]
אמנם מבט מנהל טרם פותח, אבל בכל זאת, אני נכנס כמנהל ורואה תנועות של אחרים מבלי לאפס את המשתמש בכותרת
![image](https://cloud.githubusercontent.com/assets/6491631/7563646/a5e36118-f7e7-11e4-9236-c3f0ae405f8a.png)

**Comment by tom-hollander** [comment]
זה עדיין לא פותח, אין מה לפתוח על זה באג

2015-05-11 14:12 GMT+03:00 natan1957 <notifications@github.com>:
