### ISSUE TITLE
שיעור לא מוצג לאורח

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#73]
שיעור זה שמסומן בחץ, משום מה לא מוצג כאשר אני נכנס כאורח.
הוא כן מוצג אם אני נכנס עם המורה או משתמש אחר שאיננו המורה
![image](https://cloud.githubusercontent.com/assets/6491631/7593359/4513c8cc-f8e2-11e4-8720-601dc83cf76d.png)

**Comment by natan1957** [comment]
בינתיים שמתי לב שרענון הקש פותר את הבעיה.
השאלה מי דואג לרענון הזה לאחר פרסום שיעור ע"י הסטודיו?

**Comment by natan1957** [comment]
יש מצב שהקש שמחקתי לטובת הצגת קליפים חדשים רענן גם את עניים הישוב .
אחרי מחיקת הקש, פתאום אני גר בכפר ברוך שזה הנתון העדכני...
שוב נשאלת השאלה מי דואג למחיקת הקש.

**Comment by tom-hollander** [comment]
לאחר עדכון מחוץ לממשק של הפורטל אם זה ישירות בטבלאות של הparse או אם זה דרך סטודיו
 יש לבצע קריאה לכתובת http://mymentorapp.com/home/clearcache

**Comment by natan1957** [comment]
ככה זה מופיע אצלי.. לא מצליח להבין..
[image: Inline image 1]

2015-05-23 13:04 GMT+03:00 tom-hollander <notifications@github.com>:

**Comment by tom-hollander** [comment]
צריך לבצע קריאה ל

 <http://mymentorapp.com/home/clearcache> http://mymentorapp.com/home/clearcache

 

כאשר מעדכנים נתונים מחוץ לפורטל ( דרך הparse או סטודיו)
