### ISSUE TITLE
בילבול בין שם משתמש לכתובת דוא"ל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#77]
כאשר אני חוזר מטופס2 של יצירת קופון לטופס1, שם המשתמש שמוצג בטופס הוא כתובת הדוא"ל ולא שם המשתמש שהקלדתי קודם.
יש להציג את שם המשתמש ולא את כתובת הדוא"ל.

**Comment by tom-hollander** [comment]
לפי האפיון "המורה צריך להזין את שם המשתמש של התלמיד (כתובת אימייל) עבורו הוא מייצר את הקופון ואת המחיר לתלמיד."
זה פותח מול כתובת האימייל כפי שצויין. 
זה תוקן ,אבל אני מבקש להבא לרשום באפיונים את שם השדה בבסיס הנתונים

**Comment by natan1957** [comment]
אין מניעה להזין את שם המשתמש ולשלוח לפי כתובת הדוא"ל.
אבל אין צורך להביא את כתובת בדוא"ל לשדה המשתמש..

בשלב ראשון הם זהים.. אבל בהמשך, משתמש עשוי לשנות את כתובת הדוא"ל שלו..
לעבור לספק אחר.. במקרה כזה אפשר יהיה לשנות לו את כתובת הדוא"ל ולהשאיר את שם
המשתמש. הוא ימשיך להזדהות עם השם הישן ויקבל מכתבים לדוא"ל החדש.

2015-05-23 12:20 GMT+03:00 tom-hollander <notifications@github.com>:

**Comment by tom-hollander** [comment]
אני מניח שאין בעיה לעשות את רוב הדברים אבל צריך להגדיר אותם.

כאמור תיקנתי ככה שיעבוד מול שם משתמש ולא מול כתובת דוא"ל

 

לא הבנתי מהטקסט האחרון שלך האם זה בסדר או שאתה מבקש שינוי כל שהוא
