### ISSUE TITLE
בקשה להירשם כמורה באנגלית

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#78]
כאשר מתקבלת ההודעה הזאת והמשתמש בוחר לחזור לאתר, הוא מועבר לאתר בעברית

![image](https://cloud.githubusercontent.com/assets/6491631/7720645/711e2948-fed8-11e4-9380-bfd337abd1f8.png)

**Comment by tom-hollander** [comment]
נראה לי שזה בגלל שבהעדפות השפה של המורה נבחר עברית

**Comment by natan1957** [comment]
זה קורה כפי הנראה כתוצאה מכך שבעת רישום תלמיד, שפת המשתמש לא נרשמת בטבלה.
ואז, אם התלמיד פותח טופס עדכון פרטים, מוצג לו שדה שפת ממשק עם ברירת מחדל עברית.
כשהוא מעדכן ואם לא נגע בברירת המחדל, נרשם בטבלה עברית. ואז המערכת עוברת לעברית.

הפתרון:
בהקמת משתמש יש לאכלס את שדה שפת המשתמש בשפת הממשק בה הוא נמצא.
אם בחר להירשם בעברית - עברית
אם בחר להירשם באנגלית - אנגלית
