### ISSUE TITLE
חיפוש לפי תאריך

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#80]
בחיפוש לפי תאריך, במקרים רבים אני מקבל את ההודעה הזאת
![image](https://cloud.githubusercontent.com/assets/6491631/7797914/59149eaa-02fb-11e5-887d-b10363a607a6.png)

בממשק האנדלי לא מוצג אייקון תאריכון

**Comment by tom-hollander** [comment]
יש לך דוגמה לתאריך כזה ?

**Comment by tom-hollander** [comment]
מדובר על חיפוש שיעורים נכון?

**Comment by natan1957** [comment]
8/8/2015.
כן.
באותה ההזדמנות שאתה נמצא באזור.. אולי אתה יכול לבטל את הרגישות לאותיות קטנות/גדולות בחיפוש לפי שם מורה..
