### ISSUE TITLE
הקמת קופון עם יתרה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#82]
טענתי ידנית את היתרה של מורה11 עם 800 דולר
רכשתי דרך החשבון קופון בעלות של 10 דולר
הסכום קוזז מהיתרה.
אני מנסה לאחזר את האירוע ואני מתעופף
אני לא רואה כל תנועה חיובית בחשבון האתר.
![image](https://cloud.githubusercontent.com/assets/6491631/8146050/5a7e3022-122c-11e5-9371-20f1ef4b6dcc.png)

**Comment by tom-hollander** [comment]
העמוד נופל כיוון שהקופון בסטטוס 
pending.
ישנה טבלת המרה 
couponStatus 
שהערך חסר בה. יש לך מושג איך זה קרה ?

**Comment by natan1957** [comment]
סטטוס פנדינג הוא זמני מרגע הקמת הקופון ועד סיום התהליך
בסופו של תהליך תקין הוא צריך להשתנות לפעיל.
לא הקמתי כזה סטטוס. הקמתי אותו עכשיו.
עכשיו האירוע מוצג ולא עף.
עדיין לא ברור מספר דברים
מדוע הסטטוס לא פעיל
מדוע לא נרשמה תנועה חיובית לזכות חשבון האתר
נא ראה הערכים בקופון לפי דעתי הם לא נכונים
מחיר השיעור 100 ש"ח
המורה קבע לתלמיד 10 ש"ח
מתוך ה 100 המורה ויתר על 50 שמגיעים לו ושילם מתוך היתרה שבחשבונו 40 ש"ח כדי שלתלמיד יישארו 10  ש"ח לתשלום
סכום זה היה צריך להתקבל בחשבון האתר.
כאשר התלמיד יפעיל את הקופון הוא יצטרך לשלם 10 ש"ח שיילכו לטובת האתר (ובכך האתר מקבל סה"כ 50 ש"ח)  ואפס ש"ח למורה
אלה צריכים להיות הערכים בקופון
![image](https://cloud.githubusercontent.com/assets/6491631/8149543/2cda777c-12cf-11e5-88e0-13f4aba29afa.png)

**Comment by tom-hollander** [comment]
לפי הדוגמה שנתת, more11 לא נדרש לשלם בעבור הנחה מיוחדת כיוון שיש לו מספיק יתרה. יתכן שיש חוסר באפיון במקרה זה או שאני לא ראיתי את הסעיף שמדבר על התהליך החשבונאי במקרה של הנחה כזו לרבות שינוי הסטטוס בסופו.

במידה וזה קיים באפיון אשמח אם תוכל להפנות אותי לשם.

 

תודה, 

תום

**Comment by natan1957** [comment]
ייתכן ואתה צודק..
הזיכוי הרלוונטי של האתר התרחש(היה אמור להתרחש) במועד יצירת הזכות אצל המשתמש.
עדיין הסכומים שמופיעים וסטטוס הקופון לא ברורים לי.

**Comment by tom-hollander** [comment]
נושא המספרים טופל, לא לקחתי בחשבון את השוני בחישוב בין סוגי ההנחות, כעת זה תקין.

לגבי מהלך הסטטוסים ורשומות נלוות אם ישנן, אנא הוסף לאפיון

On Jun 14, 2015 8:24 PM, "natan1957" <notifications@github.com <mailto:notifications@github.com> > wrote:

ייתכן ואתה צודק..
הזיכוי הרלוונטי של האתר התרחש(היה אמור להתרחש) במועד יצירת הזכות אצל המשתמש.
עדיין הסכומים שמופיעים וסטטוס הקופון לא ברורים לי.

**Comment by natan1957** [comment]
בדקתי את האפיון.
רשומת האירוע על פי האפיון מקבלת סטטוס
success_event
רק ב "עדכון תשלום מוצלח" וזה קורה כשיש תשלום פייפאל.
ובכל זאת במצב של רכישה כשהתשלום הוא מהיתרה, בסופו של דבר רשונת האירוע נקבלת סטטוס הצלחה.
וזו פעולה נכונה.
אני מניח שמצאת את המיקום שבו יש לעדכן את הסטטוס גם כשאין תשלום.
אם כך, באותו המקום, לפני עדכון סטטוס האירוע יש לעדכן את סטטוס הקופון לפעיל.

מנגנון ההתאוששות צריך לטפל גם במסלול רכישת קופון מיוחדת כשהתמורה היא מהיתרה של הרוכש ולא מתשלום בפועל.

**Comment by tom-hollander** [comment]
תוקן, אבל אני מבקש שתוסיף לאפיון . אני עובד מול האפיון בלבד אין לי אפשרות לודא את הפיתוחים מול הgithub
