### ISSUE TITLE
מטבעות בקופון לא מתורגמים נכון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#83]
במקרה זה הסכום המקורי השקלי נכון והסכום הדולרי לא.
![image](https://cloud.githubusercontent.com/assets/6491631/8170877/74753fca-13bc-11e5-9cc0-4cc54fbc2375.png)

![image](https://cloud.githubusercontent.com/assets/6491631/8170837/2b8bcb3a-13bc-11e5-8bde-43e479d3906a.png)

**Comment by tom-hollander** [comment]
יש קצת בלאגן. למורה יש currency , לקופון יש currency ובלי קשר ניתן לבחור מטבע להצגת הנתונים. אני צריך שתתאר את התהליך בהקשר של הcurrency מהשלב שבו יוצרים קופון. איזה מטבע נרשם בשדה הcurrency בקופון ?

**Comment by natan1957** [comment]
הקופון הוא מעיין הרחבה של השיעור/חבילה. לכן המטבע יילקח מהשיעור/חבילה. 
עדיין, חיוב הרוכש הוא במטבע הרוכש וזיכוי הנהנים (אתר, מע״מ וכו׳) במטבע הנהנים. 

נשלח מה-iPhone שלי

‫ב-18 ביוני 2015, בשעה 09:23, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
ישם 3 שדות שלא ברור לי המטבע בהם יש לרשום אותם
originalPrice
siteCouponFee
teacherCouponFee
אנא התייחס לכל אחד מהשדות , באיזה מטבע יש לרשום אותם.
מהו אם כך השימוש בשדה currency ברשומת הקופון ?

2015-06-18 9:30 GMT+03:00 natan1957 <notifications@github.com>:

**Comment by tom-hollander** [comment]
ארחיב את השאלה , בחלונית הקופון אתה מבקש להציג עמלת מורה,עמלת אתר , מחיר
מקורי, ומחיר הנחה. לא ריאיתי התייחסות מפורשת לגבי סוג המטבע (כאשר לא מדובר
בשקלים) ומכאן הבלבלול שכן אני מציג את הכל במטבע הקופון וזה כנראה לא נכון

2015-06-18 9:41 GMT+03:00 Tom Hollander <tomh.hollander@gmail.com>:

**Comment by natan1957** [comment]
הקופון יורש את המטבע מהשיעור/חבילה.
השדות שהזכרת נרשמים במטבע השיעור ובנוסף בשקלים בשדות השקליים
