### ISSUE TITLE
לא מזהה אותי

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#90]
בניסיון להזמין דמו או להוסיף לסל, לא מזהה אותי.
לאחר חזרה לפורטל והפעלת שיעורים וחבילות - מוציא אותי מהמערכת.

אולי זה קשור להודעה שקיבלתי (חד פעמי) כמה דקות לפני כן...

![image](https://cloud.githubusercontent.com/assets/6491631/8212909/3408781e-1527-11e5-809c-28636b0a6d90.png)
![image](https://cloud.githubusercontent.com/assets/6491631/8212972/9ad81b30-1527-11e5-97ea-a4de3768b42d.png)

![image](https://cloud.githubusercontent.com/assets/6491631/8212833/b4399d84-1526-11e5-8a4b-62571d3b4cdb.png)

**Comment by tom-hollander** [comment]
לא הצלחתי לשחזר, אבל אם המערכת הוציעה אותך לאחר רענון, כנראה שהsession עבד ( אולי עשו משהוא על השרת או שאני העלתי גרסה) .

**Comment by tom-hollander** [comment]
קשור לבעיית הזיכרון שנפתרה
