### ISSUE TITLE
הודעת שגיאה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#91]
הפעם ההודעה התקבלה כשניסיתי להקים משתמש חדש.
זה הנוסח:
<h2>Global Page Error</h2>
<p>The anti-forgery token could not be decrypted. If this application is hosted by a Web Farm or cluster, ensure that all machines are running the same version of ASP.NET Web Pages and that the <machineKey> configuration specifies explicit encryption and validation keys. AutoGenerate cannot be used in a cluster.</p>
Return to the <a href='Default.aspx'>Default Page</a>

**Comment by tom-hollander** [comment]
לא הצלחתי לשחזר , ביצעתי רישום מלא בהצלחה

**Comment by tom-hollander** [comment]
נבע מבעית הזיכרון , השרת ביצע איתחול מחוסר זיכרון וגרם לשגיאה זו. כעת תקין
