### ISSUE TITLE
תאריך עדכון בטופס עדכון שיעור לא מוצג נכון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#93]
![image](https://cloud.githubusercontent.com/assets/6491631/8476849/fe14032e-20cd-11e5-891f-bae2ff1eafa0.png)

**Comment by tom-hollander** [comment]
היה פיספוס במיפויי השדות כעת עובד מול שדה updatedByMyMentor

**Comment by natan1957** [comment]
תאריך עדכון לא מתחלף כשמשנים שיעור דרך הפורטל.
