### ISSUE TITLE
הכנסת null

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#94]
בעדכון שיעור כאשר השדות 
description_en_us/he_il
remarks_en_us/he_il
לא מלאים, העדכון משנה את התוכן שלהם ל
(null)
זה גורם להתעופפות האפליקציה
מצורפת תמונה של רשומה לפני ואחרי עדכון בפורטל
![image](https://cloud.githubusercontent.com/assets/6491631/8477905/5d41f9c0-20d6-11e5-89af-b45d0f9462e1.png)

**Comment by tom-hollander** [comment]
לא מצליח לשחזר את התרסקות הפורטל, האם תוכל לשלוח צילום מסך של הודעת השגיאה ואת מזהה הרשומה של השיעור ?

**Comment by natan1957** [comment]
הפורטל לא מתרסק. 
האפליקציה מתרסקת כשהיא מפעילה שיעור שעודכן בפורטל ושהוכנסו בו ערכי null. 

נשלח מה-iPhone שלי

‫ב-8 ביולי 2015, בשעה 20:44, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

**Comment by tom-hollander** [comment]
אכניס מחרוזת ריקה במקום אבל אני חושב שהאפליקציה לא צריכה להתרסק בגלל זה. אני מציע לתקן גם שם

**Comment by natan1957** [comment]
בדוק שהמחרוזת הריקה לא מתווספת לשם השיעור. 

נשלח מה-iPhone שלי

‫ב-8 ביולי 2015, בשעה 20:51, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬
