### ISSUE TITLE
דף אחרון מיותר

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#95]
השיעורים מסתיימים בדף הלפני אחרון. בדף האחרון אין כלום
![image](https://cloud.githubusercontent.com/assets/6491631/8644064/5ba24ac2-2944-11e5-9d70-5440eff18afe.png)

**Comment by tom-hollander** [comment]
עם איזה משתמש וסיסמה נכנסת ?

**Comment by natan1957** [comment]
More33@gmail.com
more33

נשלח מה-iPhone שלי

‫ב-13 ביולי 2015, בשעה 09:59, ‏‏tom-hollander ‏<notifications@github.com> כתב/ה:‬

> עם איזה משתמש וסיסמה נכנסת ? 
>

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/9306962/2b909218-4504-11e5-8ae4-53e95654ae13.png)

**Comment by natan1957** [comment]
נכנסתי כמנהל ללא סינון וקיבלתי  17 דפים. הדף האחרון מלא. זהעורר בי חשד כי תמיד הדף האחרון מלא..
אז הוספתי שיעור ואני מצפה לקבל 18 דפים כשבדף האחרון שיעור אחד.. להלן שני המסכים האחרונים שקיבלתי.
נראה לי שהוא מציג דף אחרון מלא בלבד, ואם אייננו מלא, הוא לא מוצג..
שים לב שבהתחלה יתרו היה השיעור האחרון. לאחר הוספת שיעור, הוא עבר לדף הבא ואחריו יש עוד ארבעה שיעורים.

זה הדף האחרון לפני הוספת שיעור
![image](https://cloud.githubusercontent.com/assets/6491631/9328647/1e77b0b6-45b3-11e5-8508-7bfdda078bac.png)
זה הדף הלפני אחרון והאחרון אחרי הוספת שיעור אחד 
![image](https://cloud.githubusercontent.com/assets/6491631/9328711/c1d2555e-45b3-11e5-8ba8-d274462f3649.png)

![image](https://cloud.githubusercontent.com/assets/6491631/9328724/e4ed2bae-45b3-11e5-8326-b61fc0345500.png)
