### ISSUE TITLE
משתמש שנרשם דרך האפליקציה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#96]
משתמש כזה שמבצע לוג אין לפורטל מקבל יחס כמו אורח.
ברגע שהוא מנסה לבצע פעולה מעבר למה שמותר לאורח, הוא צריך לקבל הודעה שעליו להשלים את הרישום עם כפתור המאפשר לו לעבור לעדכון רישום.
זה לא קורה בכל המקרים.

בטופס תלמיד, יש לרשום את שם פרטי ושם משפחה בשדות העברית וגם בשדות האנגלית.
לאחר עדכון תקין של טופס המשתמש יש לשנות את הסטטוס שלו לפעיל.

כרגע, כשאני נכנס כמנהל לשנות אותו לפעיל, אני מקבל הודעת שגיאה לא תקינה המודיעה לי ששם המשתמש כבר קיים
![image](https://cloud.githubusercontent.com/assets/6491631/9105411/22862eb8-3c20-11e5-91bd-cd8202c56763.png)

**Comment by tom-hollander** [comment]
אנא צרף שם משתמש וסיסמה

**Comment by natan1957** [comment]
un = talmid33@gmail.com
pw = talmid33
עדכון הסטטוס שאני בצעתי היה ממנהל

**Comment by natan1957** [comment]
בהשלמת רישום של משתמש שנרשם דרך האפליקציה שם המשתמש עדיין לא נרשם בשדה העברי ו באנגלי אלא רק באחד מהם.

בנוגע למשתמש שנרשם דרך האפליקציה וטרם השלים פרטים, כפי שכבר אמרתי לך, הוא יכול להגיע לטופס פרטים ו"לברוח" משם למערכת.
אין לי בעיה עם זה ובלבד שבכל מקרה של ניסיון לבצע פעולה מעבר למה שמותר לאורח, יקבל הודעה שעליו להשלים פרטים + הפניה למסך העדכון.

**Comment by tom-hollander** [comment]
שם פרטי ומשפחה כעת נרשמים בעברית ובאנגלית
בנוסף לפי דרישתך בבאג קודם , הכניסה לעמוד שיעורים תמנע במידה והמשתמש לא השלים רישום. במקרה זה המשתמש יועבר לעמוד השלמת פרטים
