### ISSUE TITLE
מתי מופיעה הודעה זו ?

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#97]
![image](https://cloud.githubusercontent.com/assets/6491631/9106709/e5dc3c86-3c2a-11e5-8f48-426ed548a7af.png)

**Comment by tom-hollander** [comment]
אני צריך יותר פרטים.מה הצעדים שעשית לפני ועם איזה משתמש

**Comment by natan1957** [comment]
הקמתי שלושה משתמשים
un =mo4444 pw= mo4444
un= ta4444 pw= ta4444
un= so4444 pw= so4444
הקמתי שיעור ע"י מורה4444
מחיר השיעור 112 ש"ח
הקמתי קופון  עם מחיר לתלמיד 55 ש"ח, זה הנחה מיוחדת אבל שלא מצדיקה טרנזקציה.
ואכן זה מציג קיזוז מהחשבון.
אבל בהקשה על אישור הוא מציג את ההודעה הנ"ל
לפני כן הקמתי קופון הנחה רגילה וזה הוקם תקין

![image](https://cloud.githubusercontent.com/assets/6491631/9108044/506a2bb8-3c34-11e5-8696-ba0ec6311aad.png)

**Comment by tom-hollander** [comment]
טופל, שכחתי לטפל במקרה שבו אין סוכן
