### ISSUE TITLE
חישוב רכישת קופון עם יתרה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-portal#98]
לא נדרש  לרשום תנועת רכישת קופון בסכום אפס
באירוע זה התמורה ניתנה מיתרת המורה, זיכוי האתר במכירת קופון צריך להיות חיובי לפי החישוב בשורה 212 באקסל

![image](https://cloud.githubusercontent.com/assets/6491631/9122746/bd483a68-3c93-11e5-89f2-e36ba309ba25.png)

**Comment by tom-hollander** [comment]
רק להבהיר , מדובר על 2 נושאים , 
1. רישום של תנועות בסכום 0 ( לא זכור לי שהתייחסת לכך באפיון )
2. חישוב לא נכון של זיכוי אתר.

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/9132454/521c5242-3cfc-11e5-84ce-980c8fcfa634.png)

**Comment by natan1957** [comment]
למה לי זה לא מצליח ?
![image](https://cloud.githubusercontent.com/assets/6491631/9132775/b89e4f82-3cfe-11e5-8eb8-338e7e471a29.png)

**Comment by tom-hollander** [comment]
היתה בעיה עם הפריסה לייצור, פרסתי שוב, כעת אמור להיות תקין
